### ISSUE TITLE
Set up metadata source

### ISSUE THREAD

**Issue by ta264** [Readarr/Readarr#1]
Goodreads sounds like the optimal source of we can work around the API limits.

There are some nuget projects that wrap the API that might be worth trying to get us off the ground.

https://www.nuget.org/packages/Goodreads/

API key as discussed on discord.

**Comment by TomW1605** [comment]
have you thought about using Audible for audio books?

there is already a plex metadata agent project that uses audible so that might help to be using the same source.

https://github.com/macr0dev/Audiobooks.bundle

**Comment by adamcstephens** [comment]
What about Open Library by Internet Archive?

https://openlibrary.org/developers/api

**Comment by ta264** [comment]
Goodreads is the current plan with a hosted cache to speed it up

**Comment by ta264** [comment]
Goodreads it is

**Comment by adamcstephens** [comment]
Looks like the goodreads api is going away. 

https://www.goodreads.com/api
