### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Readarr/Readarr#1009]
.

**Comment by bakerboy448** [comment]
Closing; this is expected, no immediate plans to support audiobooks.

Readarr does not support audiobooks at this time nor has it ever.  Any audio-esque references are holdovers from Lidarr

Will be re-visited when/if audiobook support is implemented

**Comment by ghost** [comment]
Not saying it has ever supported but back in the previous versions when you used to be able to type in _any_ indexer categories, readarr would be able to `find` audiobooks via interactive search and display them and I would download them. You can even still download audiobooks eg in MAM category 100013. Not saying I was looking for support for Audiobooks but just the ability to search that particular category like we were able to before.

**Comment by bakerboy448** [comment]
No point in supporting a category for media types that are not supported; no plans to either.

Categories are now determined based on a capabilities call to your indexer and filtered for e-book categories only.

**Comment by Paul5656** [comment]
cool
