### ISSUE TITLE
[Feature Request] Add Join test server as an option for notifications

### ISSUE THREAD

**Issue by ChronoStriker1** [Readarr/Readarr#1074]
In connections add a dropdown, checkbox, or seperate entry to use the Join test server instead of the normal one.
This is usefull to people currently using the Join Destop App due to using firefox or other non compatible browsers instead of google chrome.

Normal APIAddress: https://joaomgcd.appspot.com
Test API Address: https://testsjoaomgcd.appspot.com

**Comment by bakerboy448** [comment]
Closing per https://www.reddit.com/r/JoinApp/comments/o69c7k/dev_join_30_works_in_firefox_and_edge_local/
