### ISSUE TITLE
Author Folder Format requires {Author Name}

### ISSUE THREAD

**Issue by flippedcracker** [Readarr/Readarr#1087]
When trying to set the Author Folder Format, it won't let you save unless you have {Author Name} in the field. You should be able to set it to something else without that tag. For instance, {Author SortName}

[AB#116](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/116)

**Comment by bakerboy448** [comment]
Version
0.1.0.757
