### ISSUE TITLE
The word Track shows up in Webhook settings.

### ISSUE THREAD

**Issue by davidnewhall** [Readarr/Readarr#1110]
**Describe the bug**

The word `track` shows up in some places it shouldn't. 
**Recommend running `git grep -i track` to find all instances of text that may be replaceable.**

**To Reproduce**

Just add a web hook. See screenshot.

**Expected behavior**

It should say `Edition` or `Book`

**Screenshots**

![Screen Shot 2021-07-03 at 9 23 27 PM](https://user-images.githubusercontent.com/2402929/124373243-82307500-dc45-11eb-941a-0629fa9f9f6c.png)

**Platform Information (please complete the following information):**
 - OS:  unRAID
 - Docker:  Yes
 - Mono or .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Readarr Version:  0.1.0.261
 - Readarr Branch:  nightly / hotio

[AB#1197](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1197)

**Comment by ta264** [comment]
This has been fixed.  Your readarr is incredibly out of date!
