### ISSUE TITLE
Manual Import - Select Author page uses "Filter book" as suggested text instead of "Filter author"

### ISSUE THREAD

**Issue by azuravian** [Readarr/Readarr#1122]
**Describe the bug**
The Manual Import - Select Author page has a input box to filter the list.  This box says "Filter book" as a hint for what to do, but it should be "Filter author".

**To Reproduce**
1. Go to 'Unmapped Files'
2. Click on 'Manual Import' button for any entry.
3. Click author to select correct author.
4. The screenshot shown below appears.

**Expected behavior**
I expect the Import page to mention "Filter author" instead of "Filter book"

**Screenshots**
![Readarr Filter book](https://user-images.githubusercontent.com/7379812/124832780-2f0f3880-df4b-11eb-9cf0-935365762b03.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.0.7
 - Browser and Version (Only needed for UI issues): Edge Version 91.0.864.64
 - Readarr Version: 0.1.0.851
 - Readarr Branch: nightly-d801349

**Trace Logs**
No entry for this in Trace Logs.  I wasn't even sure this was a "bug" per se, but I asked in discord and was told it couldn't hurt to report it.

[AB#1233](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1233)

**Comment by bakerboy448** [comment]
@PearsonFlyer  probs an easy one
