### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by rodalpho** [Readarr/Readarr#1126]
Running 0.1.0.851 on linux x86-64, non-docker install. I installed Readarr this afternoon and let it sit for a couple of hours, so it isn't scanning a new library or anything.

Sitting completely idle, nothing showing scheduled in tasks, Readarr CPU usage trends between 25% and 90%. This is on an i5-6500 CPU, not a raspberry pi etc. 

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1002     1851181 59.7  1.1 3940392 191024 ?      Ssl  20:42   0:07 /opt/Readarr/Readarr -nobrowser -data=/opt/ReadarrData/
```

[AB#1236](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1236)

**Comment by bakerboy448** [comment]
Please fill out the bug report template it appears you wiped out.

Especially:
> **Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by rodalpho** [comment]
Will do-- I somehow had a second Readarr process running originally, after manually killing it and restarting the CPU usage is much lower. Previously it was up to like 190%, which is insane. Now it's pretty steady around 9% or so, which is still pretty high for a download app running in the background.  Sonarr for example is steady around 3% CPU, and Radarr like 0.6%.

Edit: As I write this, the CPU usage is dropping steadily, it was like 30%, now it's 9%. Going to see what happens, if it stays 3 times Sonarr I'll provide a trace.

**Comment by ta264** [comment]
This is not something I have ever seen. It idles just like the others for me. Definitely need logs if you want this looking at.

**Comment by rodalpho** [comment]
Loading the Wanted page was very slow, and it came up with something like 978 pages, so there may be a scaling issue there. Anyway this spiked CPU usage up to 46%. 

It was doing a RSS sync also so I figured it wasn't actually idle, but now that's done and it's still at 42%. It does seem to be _ever so slowly_ dropping back down, though. I'm going to keep messing with it and will upload logs if it doesn't drop back to <6%, which would be triple Sonarr.

```
root@nzb:~# ps auxwww|grep -i 'sonarr\|radarr\|readarr'|grep -v grep       
root      681223  2.3  3.9 2441460 639176 ?      Ssl  Jun28 344:06 /usr/bin/mono /opt/sonarr/Sonarr.exe -nobrowser
root     1537926  0.6  1.6 4737428 262544 ?      Sl   Jun29  89:50 /opt/Radarr/Radarr /restart /nobrowser
1002     1851181 34.1  1.6 4677156 261092 ?      Ssl  20:42   6:42 /opt/Readarr/Readarr -nobrowser -data=/opt/ReadarrData/
```

Edit: OK, so now I feel like a dumbass. I've actually worked as a sysadmin, if you can believe it, and I forgot that %CPU in ps is based on the total time the process was live, while ps in top/htop is current. _Currently,_ Readarr's CPU usage is 0.1% at idle. Sorry for wasting your time, and thank you for the software!
