### ISSUE TITLE
Bug on Manual Import, Reading Tags?

### ISSUE THREAD

**Issue by silentArtifact** [Readarr/Readarr#1128]
**Describe the bug**
When attempting to manually import a book, I get the error `Error occurred while executing task ManualImport: Nullable object must have a value.` As well as errors about failure reading tags.

**To Reproduce**
1. Select manual import under an Author's listing
2. Select a book and click import

**Expected behavior**
The books selected should import into Radarr and be associated with their selected titles.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.0.7
 - Readarr Version: 0.1.0.869
 - Readarr Branch: Nightly

**Trace Logs**
https://0bin.net/paste/vK-krEnP#etC3SKIpmrIS3eB6w2GSqI5rqW-7NMuQAHirUSAIgEN

[AB#1238](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1238)

**Comment by 2fst4u** [comment]
This seems to be affecting files that already existed in readarr and a recent update has caused readarr to ignore them and show all files for authors as nonexistent.

The files are still there but forcing a rescan gives the error 

`Tag reading failed for /shared/Books/Text/Cassandra Clare/Bitter of Tongue/Cassandra Clare - Bitter of Tongue.epub: /shared/Books/Text/Cassandra Clare/Bitter of Tongue/Cassandra Clare - Bitter of Tongue.epub (taglib/epub)
Exception
TagLib.UnsupportedFormatException: /shared/Books/Text/Cassandra Clare/Bitter of Tongue/Cassandra Clare - Bitter of Tongue.epub (taglib/epub)
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at NzbDrone.Core.MediaFiles.AudioTag.Read(String path) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\AudioTag.cs:line 63`

For all my files now.
