### ISSUE TITLE
[BUG]: (Good Reads Error?) - Unable to add author due to book refresh failing due to encoding error

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No books will load for the author due to the refresh / pull of books from good reads failing

### Expected Behavior

Books should all be pulled; we should handle these types of failures in a more graceful manner.

### Steps To Reproduce

1. Add Author `Andre Norton`
2. Wait for Refresh task to finish
3. No books added

### Environment

```markdown
- OS: agnostic
- Readarr: 0.1.0.919
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Nightly

### Anything else?

trace logs https://gist.github.com/bakerboy448/f817588684abadecf26dc926dc6aca55

Good Reads API link via browser

```
error on line 157 at column 17: Input is not proper UTF-8, indicate encoding !
Bytes: 0x03 0x48 0x65 0x20
```
https://gist.github.com/bakerboy448/dbc42847e6ed1e1b7e82e06d1b79ce7f
![image](https://user-images.githubusercontent.com/55419169/128926805-02f5ece1-d363-49bc-872f-630dd4083e84.png)

[Reddit Post](https://www.reddit.com/r/Readarr/comments/p1ue7g/author_information_not_updating_andre_norton/)

**Comment by Johnson90512** [comment]
I'm seeing this on another author: Stephen King

**Comment by bakerboy448** [comment]
Stephen king has nothing to do with this encoding error. That is a separate issue with "large authors" details in the discord in the pinned message.

**Comment by bakerboy448** [comment]
Closing; not really relevant anymore.
