### ISSUE TITLE
[BUG]: Deleting Author -> Delete Files: {path} variable not defined [UI]

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/55419169/128927589-0abf14c0-1cdc-4d2b-a1dc-06f338b76b7b.png)

### Expected Behavior

Path should be displayed not the variable

### Steps To Reproduce

1. Go to Author
2. Delete Author
3. Select Delete Files

### Environment

```markdown
- OS: agnostic
- Readarr: 0.1.0.919
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Nightly

### Anything else?

N/A - UI

[AB#1896](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1896)

**Comment by ta264** [comment]
I think this is fixed in the book-index pr
