### ISSUE TITLE
[BUG]: Login page redirects to [host listen address]/login and does not retain original browser address

### ISSUE THREAD

**Issue by ACiDGRiM** [Readarr/Readarr#1192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When accessing readarr via readarr.domain.com without an authenticated session, the login page redirects to 10.4.4.5:15005/login instead of readarr.domain.com:15005/login

If I manually type in readarr.domain.com:15005/login, I'm able to login and use readarr with the DNS name. I can also use the DNS name to load readarr everytime until my cookie expires.

### Expected Behavior

Readarr login page respects the host address in the request when redirecting to the login page, similar to sonarr, lidarr, and radarr

### Steps To Reproduce

1. set listen host to 127.0.0.1 or another IP
2. access readarr via hostname, such as localhost or another DNS name

### Environment

```markdown
- OS: Centos 8
- Readarr: 0.1.0.919
- Docker Install: no
- Using Reverse Proxy: ssh proxyying the IP's
- Browser: Brave Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (64-bit)
```

### What branch are you running?

Nightly

### Anything else?

In my specific case, readarr is listening on 127.0.0.1 and I use an SSH port forward connection to access readarr from a remote network. However this issue is not a problem in the upstream sonarr project. It was at one point and I used the workaround until it was no longer an issue.

[AB#1430](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1430)

**Comment by ta264** [comment]
Your reverse proxy is misconfigured
