### ISSUE TITLE
[FEAT]: File Name Tokens - Book Series

### ISSUE THREAD

**Issue by DreadDragoon** [Readarr/Readarr#1207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

The ability to add the Series Metadata from goodreads to the file/folder names for renaming. 

### Describe alternatives you've considered

n/a

### Anything else?

n/a

[AB#1471](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1471)

**Comment by DreadDragoon** [comment]
ala, {Book Title} - **_{Book Series} {Book SeriesNumber:00}_**/{Author Name} - {Book Title}{ - Part PartNumber:00}

**Comment by bakerboy448** [comment]
>  I have searched the existing issues

clearly not 

Duplicate of https://github.com/Readarr/Readarr/issues/26

parts Duplicate of https://github.com/Readarr/Readarr/issues/25
