### ISSUE TITLE
[BUG]: Improve logic for selecting proper ISBN

### ISSUE THREAD

**Issue by PearsonFlyer** [Readarr/Readarr#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some improvement can be made to the logic for selecting the correct ISBN. The attached log has an example. This results in a low (35-45%) match and failure to automatically import a valid release.

### Expected Behavior

If the correct ISBN is selected, import should occur automatically with match percentage threshold met.

### Environment

```markdown
- OS: Windows 10
- Readarr: 0.1.0.943
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Brave
```

### What branch are you running?

Nightly

### Anything else?

Logs at https://0bin.net/paste/N-hk-Ma+#RYW04WwCRlSmI6bxupPwNxBAc4gNoN2f-jz506R9Avn

Invalid ISBN picked:

07:14:54.2|Trace|DistanceCalculator|isbn: '4087738574' vs '9780752859699'; 0.625

Valid ISBN in the list:

"identifiers": [
    {
      "id": "uid",
      "identifier": "4087738574"
    },
    {
      "identifier": "65c862c1-9a21-4e54-b363-9f3e917a8633"
    },
    {
      "identifier": "B00ECEA37K"
    },
    {
      "identifier": "9781455546176"
    },
    {
      "identifier": "B00ECEA37K"
    },
    {
      "identifier": "18296145"
    },
    {
      "identifier": "63FTnwEACAAJ"
    }
  ],

[AB#1484](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1484)

**Comment by ta264** [comment]
In particular I think we should favour 13 digit IDs beginning with 978/979 rather than taking the first thing that passes an ISBN checksum. Here 4087738574 would be a valid ISBN but I don't think it is an ISBN in this case (and if it were it would be for a Japanese book)
