### ISSUE TITLE
[FEAT]: Adding {Series} and {Series Part}  Filename Tokens for media management.

### ISSUE THREAD

**Issue by spinzthewiz** [Readarr/Readarr#1216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

It would be great to be able to sort books by what series they appear in (ie, Frank Herberts Dune Saga), and also what # that book is in the series, for instance:

Frank Herbert\Dune Saga\01 - Dune (1965)\

### Describe alternatives you've considered

I've looked at all the Filename Tokens.

### Anything else?

No.

[AB#1500](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1500)

**Comment by ta264** [comment]
search properly next time :)

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Readarr/Readarr/issues/26
