### ISSUE TITLE
[FEAT]: Add Metadata "None" to Mass Editor

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#1230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It is not possible to bulk change author metadata to None

### Describe the solution you'd like

Add None as an option on mass editor

### Describe alternatives you've considered

1x1 editing each author

### Anything else?

None

[AB#1567](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1567)

**Comment by ta264** [comment]
Done

**Comment by bakerboy448** [comment]
https://github.com/Readarr/Readarr/commit/615acdaebef0d61b60c601cc08d164a8a297f4fd
