### ISSUE TITLE
[BUG]: interactive import stops at one file because id3 tags of all the files I selected are not exactly the same

### ISSUE THREAD

**Issue by zombiehoffa** [Readarr/Readarr#1240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

right now I get one file of 30-50 imported for a book if the tags are not exactly the same (or if the track tag is the same). 

### Expected Behavior

Doing an interactive import this should allow me to correct and import all of them and if it is importing non interactively it should not default to pulling 1 file and stopping. It should either error out and force me to interactively import it or try and figure out the correct track numbers from the file name (and failing that then force me to interactively import to correct).

### Steps To Reproduce

put an arbitrary number of files greater than one with the same id3 info and all the same track number and try to import them as a spoken book.

### Environment

```markdown
- OS: hotio docker image ubunut 20.04
- Readarr: all nightlies I have tried
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: brave
```

### What branch are you running?

Nightly

### Anything else?

na

[AB#1600](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1600)

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/135670991-37aad1b1-9185-47c8-9a5d-1f07a7aab298.png)

Logs as the template notes are required?
