### ISSUE TITLE
[BUG]: Importing a large Calibre library is taking longer than expected

### ISSUE THREAD

**Issue by M4YH3M81** [Readarr/Readarr#1283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Performing an import on a large Calibre library (appox 33.5k) running on a docker is taking longer than expected. Currently has taken over 24 hours. 

### Expected Behavior

Import should take less then 24 hours, maybe closer in the range of 4-6 hours (could be off).

### Steps To Reproduce

1. Create large Calibre library in a docker on Unraid server
2. Configure Readarr to point to Calibre library
3. Perform rescan folders task

### Environment

```markdown
- OS: Unraid 6.9.2
- Readarr: 0.1.0.990
- Docker Install: hotio/readarr:pr-book-index
- Using Reverse Proxy: No
- Browser: Google Chrome 93.0.4577.82
```

### What branch are you running?

Develop

### Anything else?

- Unraid server is a Supermicro server with dual Xeon processors
- Calibre docker and library database is stored on SSD
- Reader docker is stored on same SSD
- Books are stored on array of three 4TB spinning disks with one parity 4TB disk

https://pastebin.ubuntu.com/p/h9YRC2F2nj/

[AB#1757](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1757)

**Comment by ta264** [comment]
I think this was resolved with 3d3292fd3d29e21abfee49394522dc365e03f66c
