### ISSUE TITLE
[FEAT]: Make author a clickable link in the book page

### ISSUE THREAD

**Issue by lyz-code** [Readarr/Readarr#1285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I want to browse an author books, getting into the book view to see the synopsis and then go back to the author page

### Describe the solution you'd like

In the book page, make the displayed author name link to the author page for easier navigation 

### Describe alternatives you've considered

Open the books in other tabs, or press back in the browser

### Anything else?

No right now

[AB#1769](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1769)

**Comment by ta264** [comment]
Click the up arrow
