### ISSUE TITLE
[FEAT]: Plex Notifier to Trigger Audiobook Library Update

### ISSUE THREAD

**Issue by dagwood90** [Readarr/Readarr#1287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No problem today

### Describe the solution you'd like

It would be nice to add a Plex Notifier (similar to Sonarr and Radarr) for audiobooks in a Plex library.

### Describe alternatives you've considered

Scheduled scans but would like real-time communication

### Anything else?

N/A

[AB#1772](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1772)

**Comment by Bokaii** [comment]
Would love this feature! Has anyone find a way around this, apart from more aggressive scheduling?
