### ISSUE TITLE
[BUG]: Import error after download completed

### ISSUE THREAD

**Issue by jeff47** [Readarr/Readarr#1299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My download has completed in the client, and Readarr shows it in the Queue at 100%.  However, the process seems to stall at this point and the import never proceeds.  I see some errors in the log (attached) related to Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.

It looks like it's related to naming/renaming?  In Settings, I have the boxes under Book Naming unchecked.

### Expected Behavior

File would be imported after download is complete

### Steps To Reproduce

Download a file.

### Environment

```markdown
- OS: Ubuntu 20.04
- Readarr:10.0.0.20676
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:Brave
```

### What branch are you running?

Develop

### Anything else?

[readarr.log](https://github.com/Readarr/Readarr/files/7403823/readarr.log)

[AB#1801](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1801)

**Comment by bakerboy448** [comment]
> - Readarr:10.0.0.20676

Self builds of Readarr are not supported as we have no idea what commit they were based from nor what changes were made.

> What branch are you running?
Develop

There is no develop version.

> Anything Else / Logs

Info logs are useless for any sort of debugging. The template explicitly says TRACE logs are needed.
> Trace Logs (https://wiki.servarr.com/readarr/troubleshooting#logging-and-log-files)
Links? References? Anything that will give us more context about the issue you are encountering!
Generally speaking, all bug reports must have trace logs provided.

Closing; invalid bug report & self builds are not supported
