### ISSUE TITLE
How to select e-book language?

### ISSUE THREAD

**Issue by gurabli** [Readarr/Readarr#13]
I just came upon this project, looks really interesting.
I wonder if I can create rules to download nn English ebooks? If yes, how?

**Comment by ta264** [comment]
Only what's on Goodreads. There's a language filter to filter which books from Goodreads show up.

**Comment by kesm** [comment]
Hi, 

Can you point where it is in goodreads? I'm trying to find french books, I added fr-fr,fr,fre,french in metadata profile and tried to find J.K Rowling books to try it and it only find 3 books 
![image](https://user-images.githubusercontent.com/6907912/95726024-ad6ad280-0c78-11eb-9812-a51ee565ae1a.png)
![image](https://user-images.githubusercontent.com/6907912/95726074-c1aecf80-0c78-11eb-8d5c-5febb65bb931.png)
