### ISSUE TITLE
[BUG]: Very high CPU usage during RSS sync

### ISSUE THREAD

**Issue by rodalpho** [Readarr/Readarr#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running 0.1.0.1019 with .NET Core 5.0.8 on Linux x86-64. 

During RSS syncs Readarr consumes ~95% of an entire core on my i5-6500 host. Looking at the events log, RSS syncs are scheduled every 15 minutes and take ~6-7 minutes to complete. 

For example, the most recent Readarr RSS sync processed 1048 releases and took from 4:05PM to 4:12PM to complete. That core was pegged the whole time. So that's not great.

Comparing to Sonarr, its most recent RSS sync finished in less than 1 minute at 3:49PM, processing 1084 releases. Then Radarr took from 4:00PM to 4:01PM for 1156 reports.

Is this expected behavior? I imagine many people run Readarr on slower setups than mine, I can easily imagine RSS syncs taking >15 minutes on a slow Atom or Raspberry Pi or something.

### Expected Behavior

I would expect RSS syncs to finish in under a minute, as with Sonarr and Radarr.

### Steps To Reproduce

see above

### Environment

```markdown
- OS: Ubuntu 20.04.3 LTS x86-64
- Readarr: 0.1.0.1019 with .NET core 5.0.8
- Docker Install: no
- Using Reverse Proxy: no
- Browser: n/a
```

### What branch are you running?

Nightly

### Anything else?

n/a

[AB#1899](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1899)

**Comment by bakerboy448** [comment]
Trace logs?

**Comment by rodalpho** [comment]
So then this is not expected and other users don't have RSS sync taking >5 minutes and pegging their CPU? If so, happy to generate logs and provide them.

Edit: trace is here: https://0bin.net/paste/BVGJKSUy#Tc9d0sr1m5MJHGarZM3LF+C8FcrnE6W+-j8l0eW150q

This trace was taken during a RSS sync and I verified high CPU usage during the period. The CPU usage came from the Readarr process, not Prowlarr or anything else.

**Comment by ta264** [comment]
This take a handful of seconds for me. Please join the discord channel if you want to debug further.

**Comment by rodalpho** [comment]
I don't have time for that, but happy to provide any further information/logs you require. If that's not sufficient I guess close the issue.

**Comment by ta264** [comment]
Debugging stuff via github is not fun.  I'm going to go ahead and close this, but if someone else finds something similar, do swing by the discord and we can look into it.
