### ISSUE TITLE
[BUG]: Download link for Windows installer fails with error

### ISSUE THREAD

**Issue by mcgarrah** [Readarr/Readarr#1356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using this link: https://readarr.servarr.com/v1/update/develop/updatefile?os=windows&runtime=netcore&arch=x64&installer=true

Getting back this error message:
{"errorMessage":"Update file for develop- not found."}

### Expected Behavior

Expecting a download of the installation.

### Environment

```markdown
- OS: Windows 10 Pro x64
- Readarr:
- Docker Install:
- Using Reverse Proxy:
- Browser: Chrome
```

### What branch are you running?

Develop

### Anything else?

trying to do initial install

[AB#2002](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2002)

**Comment by ta264** [comment]
Expected behaviour until we make a stable release

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/readarr/installation
