### ISSUE TITLE
[BUG]: Author Ryk Browns missing 11 books

### ISSUE THREAD

**Issue by apastuszak** [Readarr/Readarr#1358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A search and add for Ryk Brown adds 15 books from his first series, and 4 books form his second series

### Expected Behavior

I should see 15 books from his first series, 15 books from his second series and 1 book from his third series.

### Steps To Reproduce

1. Add Ryk Brown
2. Look at list of books.

### Environment

```markdown
- OS: Ubuntu 20.04
- Readarr:0.1.0.1060
- Docker Install:Yes
- Using Reverse Proxy:No
- Browser:Firefox
```

### What branch are you running?

Nightly

### Anything else?

I'm sure this is an issue with the metadata provider, but I figured it might be good to have a look and make sure it wasn't Readarr related.

[AB#2006](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2006)

**Comment by ta264** [comment]
I think you just need to adjust your metadata profile appropriately
