### ISSUE TITLE
[BUG]: Windows Installer Broken

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Windows Installer fails

> hangs on "removing previous installation". After ignoring that (close the installer), readarr wont start. It says in the logging that there is already a process and then kill the starting process

### Expected Behavior

installer should install as expected

### Steps To Reproduce

n/a

### Environment

```markdown
- OS: Server 2019 standard or W10 professional
- Readarr: 0.1.0.1060
- Docker Install: No
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Nightly

### Anything else?

https://discord.com/channels/642870877901422592/683138610287083627/914901616929427456

Meneer iCy on discord

[AB#2012](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2012)

**Comment by RetroDadson** [comment]
@ta264 does this need doing for Radarr etc as well? i.e. is this dotnet 6 related

**Comment by Qstick** [comment]
> @ta264 does this need doing for Radarr etc as well? i.e. is this dotnet 6 related

Yep
