### ISSUE TITLE
UI: Allow custom text in HTML title bar

### ISSUE THREAD

**Issue by KarmicIT** [Readarr/Readarr#1383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

A common question lately for the *arr's is to allow a single instance of the application to support multiple versions of a download (i.e. ebook and audiobook versions). This is not currently possible and the workaround is to run multiple instances instead, one per type.

I'd like to request the ability to "name" an instance and have that name shown in the HTML title bar, either next to - or replacing - the existing text of "Readarr". This would let people easily see which instance they are currently browsing without needing to remember that the instance on port 1234 is for ebooks versus the instance on port 4321 which is for audiobooks.

This feature could be added within the Settings>General>Host area, with a freeform text box that is only visible when showing advanced options is enabled.

### Describe alternatives you've considered

Raw HTML files are not available to edit and would be overwritten by any updates.

### Anything else?

This capability already exists for hard-coded menus and book names when you browse the GUI. I.e. if you go to the Settings menu the HTML title bar shows "General Settings - Readarr". Likewise, if you are looking at an ebook it will say "Columbus Day - Readarr".

This request would enable the HTML title bar to show something similar to "Indexer Settings - ebooks - Readarr" or "Columbus Day - All Your Base Are Belong To Us - Readarr", etc.

[AB#2088](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2088)

**Comment by bakerboy448** [comment]
https://github.com/Readarr/Readarr/commit/41615fe02682a18e0edaffefba8cd881229a1a40
