### ISSUE TITLE
Windows installer links do not work for x64 and x86

### ISSUE THREAD

**Issue by Relki** [Readarr/Readarr#1418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installer links accessible from url: https://readarr.com/#downloads-v1-windows

X64
**https://readarr.servarr.com/v1/update/develop/updatefile?os=windows&runtime=netcore&arch=x64&installer=true**

X86
**https://readarr.servarr.com/v1/update/develop/updatefile?os=windows&runtime=netcore&arch=x86&installer=true**

both return an error page with this message;
**{"errorMessage":"Update file for develop- not found."}**

### Expected Behavior

Windows installer exe file download starts in browser.

### Steps To Reproduce

In Windows Edge browser, navigate to url: https://readarr.com/#downloads-v1-windows.
Then click either the X86 or X64 windows installer download links. Both buttons produce the error web page.

### Environment

```markdown
- OS: 
- Readarr:
- Docker Install:
- Using Reverse Proxy:
- Browser: Windows Edge (Chromium)
```

### What branch are you running?

Develop

### Trace Logs?

Haven't installed the product yet. Attempting to yields web page error.

[AB#2216](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2216)

**Comment by ta264** [comment]
#1356
