### ISSUE TITLE
Root folder confusion

### ISSUE THREAD

**Issue by tessierp** [Readarr/Readarr#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the YML file we have to specify the root folder for all of our books which is fine and expected. What doesn't help is we also have a Media Management where we could specify (at least I interpreted it this way), different root folders for categories like normal books and comics (this is how ubooquity devides them at least). But that doesn't seem to work or there is no way to specify this in the system that when certain books are done downloading where they should go, at least not that I have seen anyway. When books are done downloading, they wont even import because it claims it cannot find the folder of a given author in the root.

Perhaps I did not understand how to configure readarr yet but it is a bit confusing as how this should really work.

### Expected Behavior

A bit more clarity on where certain books should go and if this doesn't exist yet it would be nice to have a way to do this.

### Environment

```markdown
- OS: Linux / Docker
- Readarr: latest
- Docker Install: latest
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

[AB#2246](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2246)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/readarr/) or  [Discord](http://readarr.com/discord) for support/questions.

a docker YML file has nothing to do with the configuration of Readarr itself, only it's environment

**Comment by ta264** [comment]
I suspect you're talking about the linuxserver docker container, and I think you're getting confused by the default path suggestion 
```
- /path/to/books:/books #optional
```

This is just a docker thing, as it says the path is optional and you can add as many or as few as you want there.  Configuration of where books go after download is done in Readarr's UI

**Comment by tessierp** [comment]
> I suspect you're talking about the linuxserver docker container, and I think you're getting confused by the default path suggestion
> 
> ```
> - /path/to/books:/books #optional
> ```
> 
> This is just a docker thing, as it says the path is optional and you can add as many or as few as you want there. Configuration of where books go after download is done in Readarr's UI

Thank you ta264 I totally disregarded the #optional tag..
