### ISSUE TITLE
Switch Edition directly from Book page

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Right now, if the edition that Readarr selects on book import is wrong, you need to go to Manual Import on the author page, load all the mapped files, then switch edition. The edition drop down on book edit is read-only. This is cumbersome because it is not at all intuitive that is how to switch edition -- Edition is not even a column in the manual import modal. Also, this requires loading data for all the author's books. First load unmapped, then switch to mapped, select the book you want, then click on the dropdown to edit editions, then select edition.

### Describe the solution you'd like

It would be much more convenient, intuitive, and quicker to enable switching edition directly from the Book Edit page
![image](https://user-images.githubusercontent.com/39887349/147587259-4b978b8b-a9e5-4db4-9df8-df6ae91f4121.png)

### Describe alternatives you've considered

Going through manual import each time

### Anything else?

Manual import triggers the retag options, which I suspect it respects. I assume switching editions in this dropdown should do the same.

[AB#2280](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2280)

**Comment by rg9400** [comment]
Didn't realize you can just turn off auto-switch editions to edit the dropdown

**Comment by Lonewolf147** [comment]
I know you found a way to fix your issue, on a per book basis. Do you know (or anyone else reading this) how to turn off the Automatically Switch Edition feature for all books rather than having to go in to each one separately?
