### ISSUE TITLE
Switching edition from Book Page is not reflected in retags

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#1437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you switch an edition from the dropdown on Book Edit, Readarr does not seem to consider the new metadata for retags. On the other hand, if you manually import the book from the author page and switch editions, metadata is reflected properly.

### Expected Behavior

Switching editions should automatically trigger a retag based on the user's settings for retagging. It should also use the metadata from the new edition. In other words, it should behave the same as if the user had manually imported the book from the author page with a different edition.

### Steps To Reproduce

1. Add a book with multiple editions
2. Note metadata in the Calibre/book tags
3. Turn off auto-switch edition on Book Page
4. Switch Edition from Book Edit
5. Note the metadata in Calibre/book tags does not change. Comments/Summary is the easiest to track for this
6. Click Preview Retag. Most likely, it will suggest fields to update, but hitting retag does not update those fields. Noticeably, the Comments it was populating in this window were from my *old* edition, not the *new* edition, and they tracked with what was already in Calibre. I suspect Readarr is recognizing the mismatch between the existing tags and the new edition, but trying to update the tags using data from the old edition.
7. Switch back to the original edition, go to the Author page, click manual import, All Files, select book, select new edition, reimport
8. Verify tags have been properly changed now

### Environment

```markdown
- OS: WSL
- Readarr: 0.1.0.1144
- Docker Install: Yes
- Using Reverse Proxy: N/A
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

Trace responses for retag are not being logged it seems. I just see the below

```
2021-12-28 10:50:09.6|Trace|Http|Req: 2799 [GET] /readarr/api/v1/retag?authorId=1606&bookId=28387 (from 173.*.*.14)
2021-12-28 10:50:09.6|Trace|HttpClient|Req: [GET] http://calibre:8081/ajax/books/books?ids=5668
2021-12-28 10:50:09.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-12-28 10:50:09.6|Trace|HttpClient|Res: [GET] http://calibre:8081/ajax/books/books?ids=5668: 200.OK (6 ms)
2021-12-28 10:50:09.6|Trace|Http|Res: 2799 [GET] /readarr/api/v1/retag?authorId=1606&bookId=28387: 200.OK (25 ms)
2021-12-28 10:50:12.4|Trace|Http|Req: 2800 [GET] /readarr/api/v1/config/host (from 173.*.*.14)
```

[AB#2281](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2281)

**Comment by StudioNirin** [comment]
Did you find any solutions to this? I have the same problem. 
Coupled with, unfortunately, some books that have multiple editions, but readarr isn't finding them all in the 'editions' list when you first import a book. They only show up if you go into an already-added book, and change edition in there. Which is the version of editions which isn't working lol.

**Comment by Kyle-B** [comment]
Can confirm that this is still happening.

**Comment by ta264** [comment]
This is by design. If you want to tell readarr you have a different edition, use manual import. Book / edit tells readarr what edition you **want**, manual import tells it what you **have**

**Comment by KaiStarkk** [comment]
This UX doesn't seem to quite stack up. If you already have the book, and you're on the book page in readarr looking at the book you have, and you change the edition, it should change the edition of the book you have.
