### ISSUE TITLE
Unable to import books

### ISSUE THREAD

**Issue by kamtschatka** [Readarr/Readarr#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to manually import(wanted-->manual import-->automatic import) a book into my library and it failed.
I already did some debugging on it and it turns out it should be able to find the book and it actually sees the book as a candidate, but it is ignored, because it exits at IdentificationService.cs:139:

`x.Edition.Book.Value.Id > 0 && x.Edition.Book.Value.AuthorId > 0` is false (both parts of the condition are wrong) and therefore it excludes the book from the candidates and does not import the book.

### Expected Behavior

Book is imported in the library

### Steps To Reproduce

1. Go to wanted
2. Click "manual import"
3. Select the folder of the book (uploaded the folder to https://drive.google.com/file/d/1Np-ohRHI2XTKonTr2EJ7wyuCVhjd_5Hr/view?usp=sharing)
4. Automatically import it

### Environment

```markdown
- OS: Windows
- Readarr: latest (pulled today)
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Chrome 97
```

### What branch are you running?

Develop

### Trace Logs?

[trace.txt](https://github.com/Readarr/Readarr/files/7913463/trace.txt)

Note: I was using Fiddler to record the requests, just in case...

[AB#2417](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2417)

**Comment by ta264** [comment]
This works as expected for me.  By design, the books need to be in readarr already for manual import to match them.  Given your comment about the Ids being zero, they are not already in readarr.

Add them and it will work.

PS please join the discord for first round support with these sort of issues.
