### ISSUE TITLE
Add link back to author(s) from book page

### ISSUE THREAD

**Issue by bossanova808** [Readarr/Readarr#1502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Often I find myself going through the 'wanted' list and wanting to unmark a few books as monitored (foreign language or bonus editions etc., that have made their way in).

So I click on the book and unmonitor it. But next, I'd like to go to the author and refresh the author, do a general check/tidy up. But there's no easy link for the book back to the author..meaning I have to then manually search for the author.

Am I missing something obvious? Or could such a link be added? Would be very handy.

(I have just noticed I can unmonitor them directly from the 'wanted' index, so that's great...but still such a link would be useful and feels like it should be there...)

I am aware of meta profiles and using those to reduce things appearing in the wanted list that should not, but it's a delicate balance of missing out on things that should, so some manual work is often required (with a wide author list).

### Describe the solution you'd like

A link on the book page back to the author

### Describe alternatives you've considered

None.

### Anything else?

No.

[AB#2494](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2494)

**Comment by ta264** [comment]
It's already there, it's the up arrow top right

**Comment by bossanova808** [comment]
Right - thought I must be missing something!  Sorry for the noise...
