### ISSUE TITLE
Ignore deleted books setting wont save

### ISSUE THREAD

**Issue by klepp0906** [Readarr/Readarr#1505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to get readarr off the ground and while working my way through the settings i attempted to enable/check the "ignore deleted books" option. 

upon hitting save, the option reverts/un selects itself.

### Expected Behavior

the ability to enable/save or disable/save the "ignore deleted books" option.

### Steps To Reproduce

settings > media management > file management > ignore deleted books
enable the checkbox
attempt to save the change and notice it has reverted

### Environment

```markdown
- OS: Windows 10
- Readarr:0.1.0.1225
- Docker Install:
- Using Reverse Proxy:
- Browser: Brave
```

### What branch are you running?

Nightly

### Trace Logs?

[trace.txt](https://github.com/Readarr/Readarr/files/7946681/trace.txt)

[AB#2507](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2507)

**Comment by tehniemer** [comment]
Same issue here.
```
Version 0.1.1.1302
Package Version 0.1.1.1302-ls107 by [linuxserver.io](https://www.linuxserver.io/)
.NET Core Yes (6.0.3)
DB Migration 21
```

**Comment by EoinGohery** [comment]
Same issue still present on version 0.1.1.1320
Has anyone found a workaround or attepted to manully set this, in file?

**Comment by PREngineer** [comment]
Also having this issue.  Checked the **RootFolders** table in the **_readarr.db_** to see if I could check it in there but I don't see an option for that checkbox.  Wondering where that is being set.
