### ISSUE TITLE
"Sequence contains no matching element" when trying to add specific book

### ISSUE THREAD

**Issue by plmcgrn** [Readarr/Readarr#1514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to add [this book](https://www.goodreads.com/book/show/23360975-nazi-hunter)

Readarr fails with "Sequence contains no matching element".  Trace logs don't really indicate what the issue is in parsing the response from the API.  I did see a couple other closed issues with this error, as well, so I'm guessing it's something specific to this book that causes Readarr to fail parsing.

### Expected Behavior

Search completes and book is add-able

### Steps To Reproduce

1. Click Add New
2. Search "Nazi Hunter: Atlantis" or really anything that would include this book in results
3. Error is thrown

I've tried variations on the title, author plus title, as well as the Goodreads book ID directly.

### Environment

```markdown
- OS: macOS Monterrey 12.1
- Readarr: 0.1.0.1232
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Chrome 97
```

### What branch are you running?

Nightly

### Trace Logs?

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/8007831/Readarr.trace.txt)

[AB#2540](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2540)

**Comment by plmcgrn** [comment]
I found that searching for a different edition title does work.  I think case "I am Cowboy" does bring up results in Readarr.

https://www.goodreads.com/work/editions/25479780-i-am-cowboy-milos-vesely

**Comment by Qstick** [comment]
Closing in favor of #2153
