### ISSUE TITLE
Only monitor books in specific wanted series, not all books by author.

### ISSUE THREAD

**Issue by ghost** [Readarr/Readarr#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

If you set an author to be monitored for new books right now, all new books by that author is downloaded regardless of what series they belong to, or what series of the author is selected as monitored on the author page.

This means that unwanted books are being downloaded, costing resources in sorting/deleting and diferent sources from which books are gotten.

### Describe the solution you'd like

I'd like to be able to set the monitor status of specific series, to ignore certain series and to download all new books by the author NOT BELONGING to any series.

So that you could specify the following scenarios:
Author has two series, Series A and B.
1: Set monitor setting on series A to be all future books, and ignore series B.
    If the author comes out with a book in B it is not downloaded.

2: Download all future books in series B, and all books not belonging to any other series.
    Author writes a new book that is neither in series A or B, and so readarr downloads it.

### Describe alternatives you've considered

Unsure of alternatives

### Anything else?

Perhaps a dropdown on each series? With a toggle at the top to turn all on or off. Or a button to push which lists all current series of the author, with a box next to each series?
![bilde](https://user-images.githubusercontent.com/11895930/152978294-6d1bcc61-791c-4b95-9c40-139f6ef6b999.png)

Or perhaps an option in the author edit box?
![bilde](https://user-images.githubusercontent.com/11895930/152978654-9bbfdb7e-ebbb-4ef3-9a9b-d854405d74d6.png)

[AB#2559](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2559)

**Comment by ta264** [comment]
Use an import list to add the series
