### ISSUE TITLE
Independant control of Series or Individual book path/name string

### ISSUE THREAD

**Issue by galacticat** [Readarr/Readarr#1530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In this example:
{Book Series}/Book {Book SeriesPosition} - {Book CleanTitleNoSub}/{Book CleanTitleNoSub} - {PartNumber:000 of PartCount:000}
The Single Book naming format appears as follows:
Series Title/Book 1 - The Edition Title/The Edition Title
and this results in the following when a series isn't found
Book - The Edition Title

The Series Book naming format appears as follows:
Multi-part Book: Series Title/Book 1 - The Edition Title/The Edition Title - 001 of 002

### Describe the solution you'd like

The Single Book naming format should have it's own configuration line
The existing configuration line looks fine for a series

Preferred output format would appear as follows
The Edition Title

Currently using the previous example it appears as follows
Book - The Edition Title

### Describe alternatives you've considered

The system could automatically handle series and individual books resulting in the desired strings above.

### Anything else?

The {Book SeriesPosition} parameter needs the :00 modifier available

[AB#2613](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2613)

**Comment by bakerboy448** [comment]
This `{Book Series/Book }{Book SeriesPosition - }` /should/ work to partly address that?

It'll only add the extra pieces (sub folder, dash, etc) if and only if those exist.

**Comment by galacticat** [comment]
> This `{Book Series/Book }{Book SeriesPosition - }` /should/ work to partly address that?
> 
> It'll only add the extra pieces (sub folder, dash, etc) if and only if those exist.

That stops treating the {Book Series} as a variable and results in this example:
/books/E.B. White/{Book Series/Book }Stuart Little/Stuart Little .m4b

**Comment by bakerboy448** [comment]
Consolidating into https://github.com/Readarr/Readarr/issues/1920
