### ISSUE TITLE
Ability to suppress warning about Completed Download Handling not being enabled

### ISSUE THREAD

**Issue by plmcgrn** [Readarr/Readarr#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There's a persistent warning about this not being enabled.  I don't see a way to suppress it.  I prefer to place downloaded content by hand, because the platform doesn't allow me to update file metadata with the level of precision I prefer.  

### Describe the solution you'd like

I'd like to be able to suppress this warning, since I'm away of the ramifications of not enabling it already.

### Describe alternatives you've considered

Enabling it isn't practical for me, because I prefer to name my files and edit metadata with a level of customization that Readarr lacks.

### Anything else?

![image](https://user-images.githubusercontent.com/889547/154985679-2ba3060b-15d0-4aa2-ad82-1255915532f7.png)

[AB#2614](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2614)

**Comment by bakerboy448** [comment]
No plans for this

what type of customization for naming?  Metadata wise - can't you update metadata after import or via a custom script?

**Comment by plmcgrn** [comment]
@bakerboy448  I prefer to name my books, and their metadata based on Series.  Like

`Expeditionary Force 13 - Fallout`

Instead of 

`Fallout - Expeditionary Force book 13`

The metadata options at present don't allow for this level of precision, only whatever Goodreads has, and that can be wildly inconsistent for books that are part of a series.  While I could use a script to rename the actual files, I don't know how I'd automate updating the metadata/tags.

**Comment by bakerboy448** [comment]
Naming can be handled for that without issue I think

Metadata @ta264 any thoughts there?

Also easier to hash/discuss things out on discord
