### ISSUE TITLE
International users

### ISSUE THREAD

**Issue by dutchpete25** [Readarr/Readarr#1547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I am from Holland , cant use Readarr because goodread does not support foreign books.

### Describe the solution you'd like

I would like the option to change Goodreads for a different provider, like Calibre plugins  , in Cailibre there many international plugins like bil.com. amazon . google books etc.

### Describe alternatives you've considered

there are no good alternatives alternatives, lazylibrarian has the same problem.

### Anything else?

![IMG_20220223_111425](https://user-images.githubusercontent.com/19827237/155302023-e3491887-d506-44e0-bc1e-fe444c070ad8.jpg)

[AB#2654](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2654)

**Comment by ta264** [comment]
No plans to allow changing metadata providers.
