### ISSUE TITLE
Add leading zero to Book SeriesPosition

### ISSUE THREAD

**Issue by oranje-boven** [Readarr/Readarr#1585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Sorting filenames with the Book SeriesPosition prefix does not work properly without a leading zero for books 1-9.

### Describe the solution you'd like

In the Book Naming section of the Media Management settings, please add the functionality to use leading zeros in the Book SeriesPosition file name token. I'd imagine it would look like {Book SeriesPosition:00}. 

### Describe alternatives you've considered

I tried entering {Book SeriesPosition:00} manually in the field, but this does not result in leading zeros added to the positions 1-9.

### Anything else?

No.

[AB#2776](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2776)

**Comment by ta264** [comment]
No immediate plans for this. SeriesPosition is a text string, ii may not be a number.  It could be e.g. `1-3`.
