### ISSUE TITLE
Unable to blacklist releases

### ISSUE THREAD

**Issue by realcanadrian** [Readarr/Readarr#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Readarr is configured to download audiobooks only. Completed Download Handling is disabled so I can manually tag audio files and import interactively to avoid partial/incorrect imports. When browsing to activity history and marking a grab as "failed", nothing happens in the GUI, and nothing is added to the blacklist. A subsequent manual search for the audiobook usually downloads the exact same unwanted release.

### Expected Behavior

Add the relevant release to the blacklist and attempt to re-download a different release.

### Steps To Reproduce

1. Browse to any book > History tab
2. Click the x under the Actions column
3. Click the Mark As Failed button

### Environment

```markdown
- OS: Ubuntu 20.04.4 LTS
- Readarr: 0.1.1.1278-ls101 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome 99.0.4844.51
```

### What branch are you running?

Nightly

### Trace Logs?

The following two lines appear in the trace logs each time the Mark As Failed button is clicked:

```
2022-03-15 10:30:54.7|Trace|Http|Req: 14529 [POST] /readarraudio/api/v1/history/failed (from 173.*.*.41)
2022-03-15 10:30:54.7|Trace|Http|Res: 14529 [POST] /readarraudio/api/v1/history/failed: 400.BadRequest (0 ms)
```

[AB#2797](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2797)

**Comment by ta264** [comment]
Please try without the reverse proxy

**Comment by realcanadrian** [comment]
Same thing again. Getting the following two lines every time I try:
```
2022-03-15 12:35:26.5|Trace|Http|Req: 205 [POST] /readarraudio/api/v1/history/failed (from 172.x.x.1)
2022-03-15 12:35:26.5|Trace|Http|Res: 205 [POST] /readarraudio/api/v1/history/failed: 400.BadRequest (0 ms)
```

**Comment by realcanadrian** [comment]
From Chrome dev tools network recording:

![image](https://user-images.githubusercontent.com/19540360/158455175-dcc7f2f5-fa63-4c61-a3ff-f6dea0d56c0a.png)
![image](https://user-images.githubusercontent.com/19540360/158455206-9c8dea8e-306b-4528-9701-54dd039e61a8.png)
![image](https://user-images.githubusercontent.com/19540360/158455232-82041452-f379-4d78-ba7f-79de9a518f5c.png)
