### ISSUE TITLE
Receiving errors "Unable to load history. - Unable to load queue. - Failed to load Queue." when attempting to load their respective pages

### ISSUE THREAD

**Issue by newb23** [Readarr/Readarr#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Watching the network tab in dev mode I can clearly see that there is data being loaded in terms of books and authors, but, after said loading, I receive (one of) the title error messages from the Activity - Queue and Activity - History pages. 

The amount of data loaded before the failure is (roundabout): Author: 7.2MB, Books: 97.3MB - I am suspect that the issue may involve the very large size of my current collection, and the time it is taking to fill my HTTP/XHR requests. Collection size: 

Authors: 7798
Books: 17185
Files: 10664
Total File Size: 23.4 GB

When attempting to look at the response data, I get an error "Failed to load response data: content was evicted from inspector cache."

Edit: This also is affecting looking at the list of books in an author's page with the error: "Loading books failed" Screenshot attached.

![brave_2BPXd5iCbT](https://user-images.githubusercontent.com/7065115/160259208-4d5f43bd-b950-4f0f-8447-30c6f1edeadb.png)
![brave_9Ouldy6V98](https://user-images.githubusercontent.com/7065115/160259408-21651fe0-39a0-4c2e-b497-d137d5a29fdd.png)

### Expected Behavior

The Activity: Queue page to populate for content ingest or rejection, and the Activity: History page to load download history.

### Steps To Reproduce

1. Open the Queue/History page
2. Attempt the Refresh command or a "hard (F5) refresh"
3. Observe the error after a period of time

### Environment

```markdown
- OS: Version 6.9.2 2021-04-07
- Readarr: 
Version
0.1.1.1287
Package Version
0.1.1.1287-ls104 by linuxserver.io
.NET Core
Yes (6.0.3)
Docker
Yes
- Docker Install: Yes
- Using Reverse Proxy: Yes and No
- Browser: Brave [Version 1.36.119 Chromium: 99.0.4844.83 (Official Build) (64-bit)]
```

### What branch are you running?

Nightly

### Trace Logs?

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/8356473/Readarr.trace.txt)

[AB#2854](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2854)

**Comment by ta264** [comment]
Please join the discord channel to debug if you want to progress this.
