### ISSUE TITLE
ignore non english leading definite articles when importing

### ISSUE THREAD

**Issue by janaxhell** [Readarr/Readarr#1706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In Italian (and obviously many other languages) there are many leading definite articles, mostly starting with L, like Lo, La, Le, L', so a HUGE amount of titles are grouped under L. Besides I, GLI, UN, UNO, UNA, UN', that are not as many, but still fall in the wrong part of the alphabetical order. Also "I" (=masculine plural of The) needs to be tied to language to avoid conflict with English "I", see examples below.

### Describe the solution you'd like

An entry or profile where to set leading articles to ignore and postpone after title with comma when sorting Library view.
i.e
La Badessa di Castro > [IF language = Italian THEN ignore "La"] > YES > Badessa di Castro, La
Il Deserto dei Tartari > [IF language = Italian THEN ignore "Il"] > YES > Desterto dei Tartari, Il
I Malavoglia > [IF language = Italian THEN ignore "I"] > YES > Malavoglia, I
I am Legend > [IF language = Italian THEN ignore "I"] > NO > I am Legend

These are all variants of English "The"
IL, LO, LA, I, GLI, LE, L', UN, UNO, UNA, UN'

### Describe alternatives you've considered

I don's see any.

### Anything else?

No. See above.

[AB#3244](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3244)

**Comment by ta264** [comment]
I don't think this is something I want to get into.  Listing all the possible definite articles in all languages is too much.

**Comment by janaxhell** [comment]
No, the user sets those!

**Comment by bakerboy448** [comment]
The user does not set articles anywhere in readarr currently. And generally no plans to add manual inputs that users can then easily created support privileges with.
