### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by seaniedan** [Readarr/Readarr#1708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no installation instructions in the README or anywhere that I could find.

### Describe the solution you'd like

Information about availability on Operating Systems. Instructions on how to install.

### Describe alternatives you've considered

Searched the code base, issues.

### Anything else?

Look at other repos, e.g. https://github.com/raspberrypi/rpi-imager

[AB#3252](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3252)

**Comment by bakerboy448** [comment]
The readme and website both link to the wiki.
