### ISSUE TITLE
Metadata providers

### ISSUE THREAD

**Issue by damomato** [Readarr/Readarr#1710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The only way to automatically write metadata to ebook files is through installing Calibre and linking it to Readarr.

### Describe the solution you'd like

Not require the installation of Calibre to automatically write metadata to ebook files in Readarr.

This could maybe be done by adding metadata providers such as Goodreads.

### Describe alternatives you've considered

Editing book metadata manually by using EPub Metadata Editor software.

### Anything else?

Similar to Sonarr and Radarr having the option of XBMC to generate metadata.

My knowledge on this is limited so apologies if I have misunderstood anything.

[AB#3257](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3257)

**Comment by ta264** [comment]
Goodreads has nothing to do with writing metadata. At the moment no plans to reimplement calibre functionality.

**Comment by damomato** [comment]
Ok so just to clarify, I'm required to install Calibre just to write metadata to my books?

**Comment by ta264** [comment]
Yes

**Comment by damomato** [comment]
Alright. That's a shame. I'll have to look into using Calibre.
