### ISSUE TITLE
Select book edition using MetaData Profile.

### ISSUE THREAD

**Issue by varoOP** [Readarr/Readarr#1723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

May books have multiple editions, which end up changing the title of the book slightly at times.

A series with multiple volumes, sometimes has different editions of those volumes in Readarr, which is not ideal. It would be better to have the ability to populate Readarr with a single edition of all those volumes.

### Describe the solution you'd like

Make it possible for Readarr to only have one edition of the book. This may be achieved by adding another option to the MetaData profile where the edition can be chosen.

### Describe alternatives you've considered

Currently, it is possible to change edition during Manual Import. However, being able to automate the process would be much better.

### Anything else?

Here is an example: https://imgur.com/a/TLZd2ad

The first volume is the hardback edition instead of Kindle edition like the others. It makes the naming completely different.

[AB#3298](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3298)

**Comment by ta264** [comment]
I don't understand what you're asking for. In the screenshot you posted what are you hoping for instead?

**Comment by varoOP** [comment]
Apologies for the late reply. I am unable to create a screenshot which would have what I am hoping for instead so I will write it out.

In the screenshot, the first title; `The Undead King` should be `Overlord, Vol. 1: The Undead King` but it is just `The Undead King`. 

This difference is because, Readarr is using this edition of Overlord Vol 1: https://www.goodreads.com/book/show/27415387-the-undead-king

Instead of this one: https://www.goodreads.com/book/show/31146718-overlord-vol-1

It would be great if we could get Readarr to stick to a single edition of a series.

**Comment by ta264** [comment]
I don't think I have any plans to do this. Right now it takes the most popular release for each book. Trying to correlate that across series to keep it consistent is too much effort for minimal gain in my opinion. As soon as you import a file it will swap to the closest matching edition anyway.
