### ISSUE TITLE
Manual Import only contains one edition (all numbers) to select from

### ISSUE THREAD

**Issue by PearsonFlyer** [Readarr/Readarr#1738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There appears to be a problem with selecting editions in the latest (nightly) Readarr on manual import. This behavior has been reported by multiple users. When importing, if you select edition, it only shows one edition with just a bunch of numbers (ASIN number?). After import, if you edit the edition, a bunch show.  Here is a link to an import log:
https://0bin.net/paste/LkCHrJ1Q#KIghQxKfmhdH4HYDOvywctLhFddyKrqFr-gmKTyNziE

Here is the (entire) drop-down for a manual import:

![image](https://user-images.githubusercontent.com/15488393/178257280-35be1e60-d82c-412d-9a51-524ece224119.png)

And here are all the editions available after import to choose from:

![image](https://user-images.githubusercontent.com/15488393/178257330-1cd0feb6-5f18-464f-aaca-18ebc5954e39.png)

### Expected Behavior

When manual import is done, the entire selection of editions should be available for selection. They used to be, but something changed in a recent update.

### Steps To Reproduce

1. Go to Wanted / Manual Import
2. Choose book file(s) to import
3. Select Edition

### Environment

```markdown
- OS: Windows 10
- Readarr: 0.1.1.1377
- Docker Install: No
- Using Reverse Proxy: Both ways tested
- Browser: Brave / Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

Linked above.

[AB#3354](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3354)

**Comment by bakerboy448** [comment]
Per Ta - possibly caused by https://github.com/Readarr/Readarr/commit/a59706ceb42acbdb2128143ce027340cf0d9858e

Edition was ripped out of the book resource
