### ISSUE TITLE
External self-hosted library integration

### ISSUE THREAD

**Issue by pkreuzt** [Readarr/Readarr#1858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Reading ability for the collections is out of scope for Readarr. Apart from Calibre Server (which is way too heavy on dependencies), there's no other way to access collection and keeping track of reading progress. It would be nice to integrate a self-hosted alternative to Calibre capable of doing (mostly) the same.

### Describe the solution you'd like

I find Kavita the most interesting. It's in early stages of development, though. Supports running on a browser frame and has an API for automation, so it could be integrated somehow inside Readerr itself.

### Describe alternatives you've considered

There are some alternatives but they are mostly abandoned or depend on Calibre themselves (like Calibre-Web). Ubooquity is Java based so has extra dependencies and it's heavy too.

### Anything else?

Kavita has a running demo:

https://wiki.kavitareader.com/en/kavita-demo

[AB#3768](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3768)

**Comment by ta264** [comment]
What exactly do you want readarr to do that it doesn't currently?

**Comment by pkreuzt** [comment]
Provide links or even (if possible) run a sub-frame connecting to Kavita to read the books in the collection directly inside, instead of having to connect to the other app separately. I think "embeding" is the word.
