### ISSUE TITLE
Cutoff Unmet Unable to Load - SQL logic error near ")": syntax error

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#1911]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Cutoff Unmet does not load due to invalid sql logic

likely
` WHERE ("Editions"."Monitored" = @Clause5_P1) AND () AND (("Books"."Monitored" = @Clause7_P1) AND ("Authors"."Monitored" = @Clause7_P2))`

### Expected Behavior

Cutoff Unmet should load

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: agnostic
- Readarr: 0.1.1.1426
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
- Database: Sqlite 3.31.1
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/bakerboy448/05808456ef34c36d70998d3491998856

[AB#3987](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3987)

**Comment by bakerboy448** [comment]
Appears to be likely that the postgres commit broke it @RobinDadswell 
https://github.com/Readarr/Readarr/commit/46c2e0ba82b7625f13b9d28f6384cac95d37b496

**Comment by Qstick** [comment]
Can't reproduce this

**Comment by Qstick** [comment]
Not PG related, this is an upstream bug if all cutoffs are the lowest quality
