### ISSUE TITLE
SABnzdb Can not connect when api is not on root folder

### ISSUE THREAD

**Issue by kanine** [Readarr/Readarr#1912]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When trying to configure SABnzdb Download Client, there is no space to specify a URL Base as in other arr apps like sonarr. When trying to configure the base in the host field (eg host.com/sabnzdb) an error occurs.

Unable to connect to https://host.com/sabnzdb:443/api?mode=get_config&apikey=xxxx

Current workaround is to use the SABnzdb blackhole.

### Expected Behavior

If a URL Base folder can be specified then the correct connection is:

https://host.com**:443**/**sabnzdb**/api?mode=get_config&apikey=xxxx

### Steps To Reproduce

1. Seedbox install (ultra.cc)
2. SABnzdb App Install
3. Readarr App Install
4. Configure SABnzdb connection client

### Environment

```markdown
- OS: Linux (Seedbox)
- Readarr: 0.1.1.1426
- Browser: Chrome
- Database: Sqlite 3.38.5
```

### What branch are you running?

Nightly

### Trace Logs?

`Unable to connect to https://host.com/sabnzdb:443/api?mode=get_config&apikey=xxxx`

[AB#3988](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3988)

**Comment by ta264** [comment]
Enable advanced settings before opening up the "add download client" modal
