### ISSUE TITLE
Importing Goodreads List doesn't mark books as monitored

### ISSUE THREAD

**Issue by sgtcoder** [Readarr/Readarr#1957]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Importing Goodreads List doesn't mark books as monitored

### Describe the solution you'd like

Importing Goodreads List should mark books as monitored

### Describe alternatives you've considered

Manually click each book to be monitored

### Anything else?

The setting is set to only monitor imported books.

[AB#4128](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4128)

**Comment by ta264** [comment]
Logs required

**Comment by sgtcoder** [comment]
I believe this is because I unmonitored the author/books, and didn't have the monitoring existing books checked in Readarr. But there also isn't a way to monitor all authors and not all their books.

**Comment by bakerboy448** [comment]
> isn't a way to monitor all authors and not all their books

There is and this is controlled with the monitor settings you specify for the list.

Also please stop opening feature requests for every `bug` or issue you encounter.  it's best to vet things out on discord first.
