### ISSUE TITLE
Missing Book Covers

### ISSUE THREAD

**Issue by sgtcoder** [Readarr/Readarr#1961]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some books are missing book covers: https://gyazo.com/21c75ab964a5848924befaac54c49934

Book link: https://www.goodreads.com/book/show/56964166-devoted

### Describe the solution you'd like

Ability to pull in book covers from GoodReads

### Describe alternatives you've considered

I would have to manually add the book cover

### Anything else?

Book link: https://www.goodreads.com/book/show/56964166-devoted

[AB#4136](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4136)

**Comment by bakerboy448** [comment]
Readarr already uses Goodread's data as noted on the [FAQ](https://wiki.servarr.com/readarr/faq#why-can-i-not-add-a-new-book-or-author-to-readarr).
The linked book does not have a cover on Goodreads.

**Comment by sgtcoder** [comment]
This is the book: https://www.goodreads.com/book/show/52287403

As you can see there is an image. When it imported into Readarr, it doesn't have an image.

**Comment by sgtcoder** [comment]
Does Readarr pull in the GoodReads ID? https://gyazo.com/911da458f3931a4af3a49790e5754a5b

**Comment by bakerboy448** [comment]
Those are completely different editions and are not the same.
- https://www.goodreads.com/book/show/56964166-devoted does not have the cover
- https://www.goodreads.com/book/show/52287403-devoted does have the cover

The edition you presumably have selected Readarr to use for the book is the coverless one.

Also a reminder as the docs note - if you use Readarr with calibre integration then you absolutely cannot ever make any changes directly in calibre. If you do so you'll need to blow away your readarr database and start from scratch.

**Comment by sgtcoder** [comment]
The Book ID is: 52287403, but Readarr chose to import 56964166 instead.

**Comment by bakerboy448** [comment]
Again, readarr matches based on numerous file metadata properties and tries to best select the edition if automatically choose edition is enabled.

You can change the edition of the book if you do not believe Readarr determined the correct one.

**Comment by sgtcoder** [comment]
Thanks. I will look into the logs. You would think it would use the GoodReads ID like Calibre does.

**Comment by sgtcoder** [comment]
Maybe we can have an option that we can enable like:

```
Use GoodReads ID to identify Book (if it's set)

Otherwise, it would do the existing logic
```

**Comment by bakerboy448** [comment]
https://github.com/Readarr/Readarr/blob/565fb7771399d3fd28d77a908751912834e88650/src/NzbDrone.Core/MediaFiles/BookImport/Identification/CandidateService.cs#L251-L270

id is already used to find editions and then the various comparisons of the book metadata to the goodreads data is applied to determine if it is a match.

**Comment by sgtcoder** [comment]
This issue is then related to the metadata server: https://github.com/Readarr/Readarr/issues/1962#issuecomment-1322496732
