### ISSUE TITLE
Books Identify Wrong

### ISSUE THREAD

**Issue by sgtcoder** [Readarr/Readarr#1962]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Imported books with existing GoodReads ID, identify with the wrong book

https://gyazo.com/e8417a82824306d7bcacb65f636d1dab

### Describe the solution you'd like

When importing books, it would be nice to have the ability to use the metadata from the book to identify.

### Describe alternatives you've considered

Re-identify the book manually

### Anything else?

Books have metadata written properly by Calibre.

[AB#4137](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4137)

**Comment by bakerboy448** [comment]
- File tags are already used to identify books.
- Books can be managed and re-assigned via the Manual Import on the author page
- Import how?  There's several import methods.
- Your metadata profile also influences this as well.

What specifically are you asking for? Readarr is file tag property based already and it sounds like that is what you're asking for?

**Comment by sgtcoder** [comment]
The problem is the imported books are not using GoodReads ID and using some other ID.

To Kill A Mocking Bird for example is ID: 2657, but Readarr chose to use ID: 26037867

**Comment by bakerboy448** [comment]
- Trace logs of readarr importing the book and using some other id it'd detail out all the data and comparisons done.  Book matching is not based on a singular field.
- If Calibre is being used with Readarr's library then you need to use Calibre's Integration with Readarr. You also cannot make any edits in/with Calibre without needing to start over your Readarr DB from scratch as the docs note.

**Comment by sgtcoder** [comment]
I will look into the logs to see what's going on.

I definitely don't want to use Calibre Content Server and I don't want Readarr managing Calibre. I am only using Calibre to correctly identify the book.

**Comment by sgtcoder** [comment]
I also discovered that not all editions show up which might be why it doesn't identify properly: https://gyazo.com/ac426cd8ae198484c72efa515261162e

ID: 52287403

**Comment by bakerboy448** [comment]
Yeah definitely seems to be some hiccups going on with the readarr metadata server

**Comment by sgtcoder** [comment]
Let me know if you need any help or testing. That might resolve all the issues I have been having.

**Comment by bakerboy448** [comment]
Closing given no FR is needed and the options exist - no change needed.

selection issues for missing editions seems to be meta server issues

Also please stop opening feature requests for every bug or issue you encounter. it's best to vet things out on discord first. :)
