### ISSUE TITLE
Author Books in Separate Folders / Directory

### ISSUE THREAD

**Issue by ozdeadmeat** [Readarr/Readarr#1967]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like the ability to have each audiobook placed in a separate folder. Some of the audiobooks I have contain hundreds of files and having them all dumped in a single folder / directory is not really an option for me.

### Describe the solution you'd like

Under the book naming, have the ability to separate the books into individual folders / directories under the authors.

### Describe alternatives you've considered

Not using the rename functionality in readarr

### Anything else?

Please make this a thing.

[AB#4148](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4148)

**Comment by bakerboy448** [comment]
This already exists.


pseudo naming schema, note the /
```
{Book Name}/ {file naming tokens}
```

Please use one of the support channels: [Reddit](https://www.reddit.com/r/readarr/) or  [Discord](http://readarr.com/discord) for support/questions.
