### ISSUE TITLE
Decide on entity schema

### ISSUE THREAD

**Issue by ta264** [Readarr/Readarr#2]
Goodreads seems to have authors and books.

Books seem to be tied to series using an add-on to the title (and you can query title with and without the add-on)

Stick with authors and books as the entities?

**Comment by Code-Slave** [comment]
series can be books by diff authors too. High level you will likely need author,book and series as "tables"

**Comment by ta264** [comment]
We have authors, book and series.

There is some confusion around editions - effectively books are works rather than individual editions at the moment
