### ISSUE TITLE
HTTP 405 on Manual Import

### ISSUE THREAD

**Issue by opswhisperer** [Readarr/Readarr#2042]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I end up doing a lot of manual imports for books I'm adding outside of Readarr. When I go to Wanted --> Manual Import, if I accept all the matches as-is then there is no problem.

If I change the author or book name then the green Import button is deactivated and I can't import anything. The only error in any of the logs (trace and debug) also shows up in the browser console is an HTTP/405

I did try this via my traefik proxy and direct to the container with the same results. 

### Expected Behavior

I should be able to map manual imports to wanted titles if the automatic match fails. 

### Steps To Reproduce

1. Place files in a folder to import (epub in my case)
2. Go to wanted, Manual Import
3. Select a folder
4. Select Interactive Import
5. Select an item and change the author or title
6.  Import button is deactivated
7. HTTP 405 in the logs and browser console

### Environment

```markdown
- OS: Ubuntu 20.04.5 LTS (Focal Fossa)
- Readarr:0.1.1.1504
- Docker Install: Yes
- Using Reverse Proxy: traefik
- Browser: Safari, Chrome
- Database: Sqlite 3.38.5
```

### What branch are you running?

Nightly

### Trace Logs?

```
2022-12-09 13:10:02.2|Trace|Http|Res: 190 [PUT] /api/v1/manualimport/658655983?forceSave=true: 405.MethodNotAllowed (1 ms)
2022-12-09 13:10:02.3|Debug|Api|[PUT] /api/v1/manualimport/658655983?forceSave=true: 405.MethodNotAllowed (1 ms)

```
<img width="1064" alt="Screenshot 2022-12-09 at 8 14 40 PM" src="https://user-images.githubusercontent.com/4588615/206828425-254ad982-d175-4f59-9f92-6241ecc2ff78.png">

<img width="1108" alt="Screenshot 2022-12-09 at 8 14 13 PM" src="https://user-images.githubusercontent.com/4588615/206828432-db763136-4427-4734-a4a2-c5fbe48bbfd2.png">

[AB#4399](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4399)

**Comment by Snuffy2** [comment]
I am also unable to do a Manual Import if the Author and Book aren't matched automatically. Looking in the Trace logs, I see the same 405 Errors.

https://hastebin.com/pagovoqose.yaml

**Comment by feerlessleadr** [comment]
I was just about to open a new issue on this as this has been happening to me as well. 

https://paste.ubuntu.com/p/p8FhTvVb4n/

I tried on different browsers with no extensions enabled to rule out any quirks there, but the same behavior remains.

**Comment by Qstick** [comment]
Thanks guys, issues have been identified, we are working on fixing this in Lidarr and Readarr
