### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by RudyBzhBzh** [Readarr/Readarr#2082]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As discussed on Discord from [here](https://discord.com/channels/264387956343570434/1028840624864120872/1055958614940057640).
Same issue as #815 which is closed for a long time (but not the same as #1573).
Trying to add the book "Révérence à la vie" from "Théodore Monod" without success.
Error "Sequence contains more than one matching element"

### Expected Behavior

The book is added without any issue.

### Steps To Reproduce

In last dev (0.1.1.1320) or in nightly (0.1.1.1497 tested by @thezak48) :
- Search the book "Révérence à la vie" in the top search)from Théodore Monod
- Click on the book to add it
- Click on "Add Révérence à la vie"

### Environment

```markdown
- OS: Debian
- Readarr: dev (0.1.1.1320) or nightly (0.1.1.1497)
- Docker Install: 0.1.1.1320-ls25 by linuxserver.io
- Using Reverse Proxy: no
- Browser: Firefox
- Database: Don't know ?! This perhaps : "Migration de la base de données     21"
```

### What branch are you running?

Develop

### Trace Logs?

Dev log : [LOG](https://gist.github.com/RudyBzhBzh/47c10ee592e525e2aaebe94a6aaed895)
Nightly log (from @thezak48) : [LOG](https://gist.github.com/thezak48/fdeeff66c800f2f1e838cb4680c11929)

[AB#4532](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4532)

**Comment by RudyBzhBzh** [comment]
Hi,
Just a small input to notice that I found other books with the same error for me :
- ["Proie idéale"](https://www.goodreads.com/book/show/17317664) from "Charlotte Bourquet"
- ["Aigue Marine"](https://www.goodreads.com/book/show/16300411) from "Jean-Claude Dunyach"
Just in case it could be usefull to troubleshoot.
Regards.

**Comment by klepp0906** [comment]
same issue with Owned by Fate - Tessa Bailey, cannot import it without getting `Sequence contains more than one element`

**Comment by Qstick** [comment]
Closing in favor of #2153
