### ISSUE TITLE
On Author Added Notification

### ISSUE THREAD

**Issue by dexn** [Readarr/Readarr#2102]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There is a notification trigger for an authors deletion but not for addition.

### Describe the solution you'd like

Implement a trigger for "On Author Added", similar to Radarr's "On Movie Added".

### Describe alternatives you've considered

N/A

### Anything else?

N/A

[AB#4619](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4619)

**Comment by strike84** [comment]
+1 I would also like a trigger for new book added in addition to author
