### ISSUE TITLE
Manual import requires edition selection to complete

### ISSUE THREAD

**Issue by PearsonFlyer** [Readarr/Readarr#2138]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When doing a manual import, after selecting author and book, frequently the import button remains grayed out. It requires selecting the Edition as well. The edition selection is "blank" and you have to actually choose one.

I think the issue is that it's selecting a null edition, rather than a default of some sort.

![image](https://user-images.githubusercontent.com/15488393/213331959-295e1855-6b4d-4023-94dd-97f7309495a5.png)

![image](https://user-images.githubusercontent.com/15488393/213332011-5578903a-1a93-42c3-917e-d277d719b934.png)

![image](https://user-images.githubusercontent.com/15488393/213332047-40ed3577-3c6c-41ec-bf46-2846f0c98306.png)

### Expected Behavior

Manual import should have a default edition, and selecting only author and book should be enough to import it.

### Steps To Reproduce

Do a Wanted / Manual Import, and select author and book. It doesn't happen 100% of the time, but often enough to be noticeable.

### Environment

```markdown
- OS: Windows
- Readarr: 0.1.1.1527
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: Sqlite 3.36.0

Note, this has been reported by several users over the last 2 weeks.
```

### What branch are you running?

Nightly

### Trace Logs?

Log files are unhelpful for this, because it's just the UI showing the import until the actual import is done.

[AB#4757](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4757)

**Comment by satmandu** [comment]
Thanks for mentioning this!
