### ISSUE TITLE
Partial book imports

### ISSUE THREAD

**Issue by zelestcarlyone** [Readarr/Readarr#2152]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When importing books, sometimes for some books for some authors, the import is only partial without any warnings in the logfile, error messages or the like. It just says "Completed" after import, but there are still files in the "unmapped files" tab, and if you look at the actual book, only a fraction of the total files are there.

**Folder View**: Showing the folder of 225 files.
![image](https://user-images.githubusercontent.com/13156143/214562612-c0b0479f-7a61-485b-b655-4dacf44f36c1.png)

**Imported book**: Showing the book tab, with all files it imported.
![image](https://user-images.githubusercontent.com/13156143/214562866-5d02844f-1120-48b4-920c-6a0cbb407287.png)
Only 18 of the 225 files seems to have been imported.

**Unmapped Files**: Showing the unmapped files for the book.
![image](https://user-images.githubusercontent.com/13156143/214563145-07d28cb5-42b0-43be-aeb5-0c956b122d42.png)
Only 11 of the 207 missing files show up in Unmapped Files.

**Manual Import**: Showing the manual Import.
![image](https://user-images.githubusercontent.com/13156143/214563652-433bc1b8-252f-40d2-afc0-7741136a14fa.png)
If trying a manual import, all 225 files show up. The book is matched correctly.

The log files output this:
```
2023-01-25 13:28:57.3|Info|ImportDecisionMaker|Reading file 1/207
2023-01-25 13:28:57.3|Info|ImportDecisionMaker|Reading file 2/207
...
2023-01-25 13:28:57.4|Info|ImportDecisionMaker|Reading file 206/207
2023-01-25 13:28:57.4|Info|ImportDecisionMaker|Reading file 207/207
2023-01-25 13:28:57.4|Info|TrackGroupingService|Grouping 207 tracks
2023-01-25 13:28:57.4|Info|IdentificationService|Identifying book 1/1
2023-01-25 13:29:04.8|Info|ImportDecisionMaker|Reading file 1/225
2023-01-25 13:29:04.8|Info|ImportDecisionMaker|Reading file 2/225
...
2023-01-25 13:29:04.9|Info|ImportDecisionMaker|Reading file 224/225
2023-01-25 13:29:04.9|Info|ImportDecisionMaker|Reading file 225/225
2023-01-25 13:29:04.9|Info|TrackGroupingService|Grouping 225 tracks
2023-01-25 13:29:04.9|Info|IdentificationService|Identifying book 1/1
2023-01-25 13:31:01.9|Info|ImportApprovedBooks|Importing book 1/1 [849585][The Shining]
2023-01-25 13:31:02.2|Info|ImportApprovedBooks|Importing 225 files
```
(I've added ellipsis for the `Reading file` parts, since none of them fail and there are so many of them).

### Expected Behavior

All files should be imported.

### Steps To Reproduce

- Set up the folder according to standard (Author\Book)
- Refresh the folder and wait for automatic import
- Error occurs, sometimes.

Once this error occurs, I can't do a manual match either.

### Environment

```markdown
- OS: Ubuntu 22.04 (5.15.0-58-generic)
- Readarr: 0.1.2.1532
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave Browser/Chrome/Firefox
- Database: Sqlite 3.40.1

- Package Version: 0.1.2.1532-ls30 by linuxserver.io
- .NET Core: Yes (6.0.7)
- DB Migration: 23
- Database: Sqlite 3.40.1
- AppData directory: /config
- Startup directory: /app/readarr/bin
- Mode: Console
```

### What branch are you running?

Develop

### Trace Logs?

[Readarr.txt](https://github.com/Readarr/Readarr/files/10499312/Readarr.txt)

[AB#4801](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4801)

**Comment by PearsonFlyer** [comment]
This is not a bug, this is bad tagging on your files. Filenames are not used for imports, tags are. So when the tags change (for example, back to "track 1", it's a "new book" to Readarr.

**Comment by zelestcarlyone** [comment]
> This is not a bug, this is bad tagging on your files. Filenames are not used for imports, tags are. So when the tags change (for example, back to "track 1", it's a "new book" to Readarr.

So, tagging with disc/track doesn't work? I have the tags set up like this:
![image](https://user-images.githubusercontent.com/13156143/214568622-02de2ff0-4c6e-45fb-843d-6fc7bc0f45db.png)
The proper way to do it would to just have a running number, rather than separated by the original discs?

**Comment by PearsonFlyer** [comment]
Correct, disc/track is not supported currently. There is a github issue for that implementation, but it's open. You want your tracks sequentially, 1 through however many tracks there are.
