### ISSUE TITLE
Manual Import - Apply author, book, group to all files

### ISSUE THREAD

**Issue by Jdiesel87** [Readarr/Readarr#2179]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When manually adding an unmapped file or unreconized book via the manual import function the author, book, and group must be selected from the dropdown for each file in the folder. These can be extremely tedious for audiobooks that have individual mp3s for chapters

### Describe the solution you'd like

A option to apply selections to all files in the manual import wizard

### Describe alternatives you've considered

None considered

### Anything else?

![Screenshot 2023-02-12 2 37 10 PM](https://user-images.githubusercontent.com/14824476/218335768-0909f48f-d12a-4379-92e3-20b464ed1131.png)

**Comment by PearsonFlyer** [comment]
That checkbox right at the top left, above the first line of book content? That's a select-all.  Click that, select book and author and stuff from the bottom and you're all good.

Closing as not an issue.
