### ISSUE TITLE
multi language separated books and audiobooks

### ISSUE THREAD

**Issue by wieluk** [Readarr/Readarr#2339]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hey, I would like to have a library each for German and English books and audio books.
Is there a solution if I have the same authors for some books/audio books?

### Describe the solution you'd like

Having multiple libraries in readarr.

### Describe alternatives you've considered

Right now my solution is having 4 instances of readarr running but that's not really ideal.

### Anything else?

Is this possible or will it be mandatory to run multiple instances of readarr?

**Comment by bakerboy448** [comment]
duplicate of https://github.com/Readarr/Readarr/issues/1329
