### ISSUE TITLE
Unable to connect to Newshosting Indexer

### ISSUE THREAD

**Issue by iJasonWade** [Readarr/Readarr#2377]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When attempting to connect to Torznab (news.newshosting.com) indexer the following error message is shown in the logs
`[v0.1.4.1596] System.Net.Http.HttpRequestException: Received an invalid status line: '200 NNTP unlimited.newshosting.com Service Ready - support@newshosting.com'.`

### Expected Behavior

The indexer connects as expected.

### Steps To Reproduce

Version: 0.1.4.1596
Package Version: 0.1.4.1596-ls39 by [linuxserver.io](https://www.linuxserver.io/)
.NET Core: Yes (6.0.7)
DB Migration: 27
Database: Sqlite 3.40.1
AppData directory: /config
Startup directory: /app/readarr/bin
Mode: Console

### Environment

```markdown
- OS: Ubuntu 22
- Readarr: 0.1.4.1596
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Safari
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

[Readarr.txt](https://github.com/Readarr/Readarr/files/11266654/Readarr.txt)

**Comment by PearsonFlyer** [comment]
Newshosting is not an indexer, it's a provider. Readarr connects to indexers, your DL client connects to providers.

Also, please use normal support channels (discord, reddit), for support issues. Github is only for bug reports, and this is not a bug.
