### ISSUE TITLE
Book rejected due to author mismatch caused by metadata containing multiple authors

### ISSUE THREAD

**Issue by tingtom** [Readarr/Readarr#24]
**Describe the bug**
During development of LibGen integration I ran in to an issue with a book called [A Regency Christmas VI](https://www.goodreads.com/book/show/933138.A_Regency_Christmas_VI) which has multiple authors in Goodreads but Readarr doesn't seem to be parsing multiple authors from the metadata.

**To Reproduce**
1. Somehow download the book in question
2. See how the EbookTagService is finding authors
3. Watch the distance calculator cause you pain

**Expected behavior**
Either parse the main author or support multiple authors in books

**Screenshots**

**Logs**
[Link to debug logs.](https://pastebin.com/CGhA1RVc)

**System info (please complete the following information):**
 - Readarr Version: 10.0.0.2736
 - Operating System: Windows 10
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**
Check Discord developer channel for minor discussion, I'm not sure why the file name is different to the metadata will make sure it's not me and it's the source instead.

**Comment by bakerboy448** [comment]
Is this still occurring on recent builds?

**Comment by ta264** [comment]
Fixed by #913
