### ISSUE TITLE
Successful results on Prowlarr or Manually Searching on Indexer/Tracker but not displaying on Readarr?

### ISSUE THREAD

**Issue by TechnicianOnline** [Readarr/Readarr#2480]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching for a specific peice of material on Readarr, I get limit and often no results. However, if I run the same search on Prowlarr, or on the indexer/tracker directly; I find the results I seek. I have Prowlarr setup with all my trackers/indexers and confirm within Prowlar under  Settings > Apps > Readarr, I have it set to Full Sync + Audio (all options selected) categories. So next I check Readarr to confirm under Settings > Indexers > Tracker/Indexer the categories are indeed updated to match my Powlarr categories of Audio/MP3 + AudioBook + Etc + Etc + Etc. 

### Expected Behavior

Readarr should be providing me the same results as Prowlarr. Categories match, why does it not? :(

### Environment

```markdown
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

### What branch are you running?

Master

### Trace Logs?

https://privatebin.net/?f5f1fdf615a3618f#BNTJBd14UZNWdzeqKDcfZcBLAZoK9KAY7kqqzZqjwPeG

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by TechnicianOnline** [comment]
Thank you all in advance, your time is valued! Hope I can figure out what I should change to allow my results to show.

**Comment by TechnicianOnline** [comment]
Okay, I did some more digging and can confirm this is a bug. Upon checking my logs, Readarr sends a query for the book in this term <Author> <BookTitle> example: Homer Simpson Why We Want You To Be Rich Today

If I log into my indexer and manually search using that, it fails and gives me no results. However, if I search using the book title only, it yields my results. Example: Why We Want You To Be Rich Today

I think it's a bug that Readarr isn't searching by book title and including the author instead of searching for both? Thank you.

**Comment by TechnicianOnline** [comment]
> 👋 @TechnicianOnline, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please hop over onto our [Discord](https://readarr.com/discord) or [Subreddit](https://reddit.com/r/readarr)

I hate to ask but can you view my last post here, I still think it's a bug which should be fixed. I initially thought it was a problem with my software but identified it's caused by Readarr's method of search which yields negative results.

**Comment by TechnicianOnline** [comment]
@bakerboy448 maybe it should be set as a feature request or bug vs support? Thank you for everything you do! 👍

**Comment by bakerboy448** [comment]
Searching by author and book is not a bug and is intentional.

No plans to not search with author.

Getting different results in prowlarr vs readarr for the same search term is 100% a support issue and likely a category misconfiguration.

**Comment by TechnicianOnline** [comment]
@bakerboy448 thank you for the quick reply brother! I double checked and confirmed it's not a category misconfiguration. The way I determined this is by replicating the problem and matched that with the Readarr log file.

I can validate that with links and the **usenet indexer** _(don't know how much I should dislcose of the workflow)_ but I can post with screenshot proof of how searching for Audiobooks with the **Booktitle** only yields better results vs searching like **Readarr** does with the **Author + Book Title** _(Read also searches Book Title + Author)_ Since the root issue is that **Readarr** is searching by **Author + Booktitle** instead of just Booktitle - is there anyway I can change that?  Maybe I should open a new ticket as a feature request and place the title as "_Give Readarr the ability to search by Booktitle vs Author + BookTitle for better results on Audiobooks._"

**Comment by TechnicianOnline** [comment]
I created a new thread with the proper details/info and filed it as a feature request to enhance Audiobook detection. Thank you!
