### ISSUE TITLE
Include book number of the series as part of the book naming options

### ISSUE THREAD

**Issue by jlasky** [Readarr/Readarr#25]
**Is your feature request related to a problem? Please describe.**
I don't always remember which book comes next in the series (does Order of the Phoenix come before the Half Blood Prince, for example).

**Describe the solution you'd like**
I would like to see in the "Standard Book Format" the ability to add {Book 00} to allow for custom naming with the book number. E.G. 05 - Order of the Phoenix, 06 - Half Blood Prince

**Describe alternatives you've considered**
We could also have the {Book 0} if people want 5 - Order of the Phoenix, 6 - Half Blood Prince

**Additional context**
I love the project, and I wish that I knew C so I could contribute. I'm a Python / data science guy so if there is anywhere that I can help then let me know.

[AB#1057](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1057)

**Comment by tingtom** [comment]
The position of the doesn't seem to be a number but a string, I'm not entirely sure why though.

**Comment by bakerboy448** [comment]
Is this still occurring on recent builds or did we fix it and forget to tag this?

**Comment by Jacob-Lasky** [comment]
I don't see anything within the "File Name Tokens" of the media management tab that references series information. Unless I'm mistaken, that would mean that this is not fixed.

**Comment by bakerboy448** [comment]
Include with #26

**Comment by Budlyte** [comment]
Is this where I put my +1 ?
For #26 & this one!
