### ISSUE TITLE
Include series as part of the book naming options

### ISSUE THREAD

**Issue by jlasky** [Readarr/Readarr#26]
**Is your feature request related to a problem? Please describe.**
Sometimes I forget which series a book is in. For example, is the The Way of Kings in Mistborn or in the Stormlight Archive?

**Describe the solution you'd like**
In the Media Management, I'd love to have the ability to include {Series} in the rename. E.G. The Stormlight Archive - The Way of Kings

[AB#1059](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1059)

**Comment by tingtom** [comment]
An issue with this and the other naming option is a book can be in multiple series, an easy fix is to just take the first one which for most books should be fine.

**Comment by bakerboy448** [comment]
Is this still occurring on recent builds or did we fix it and forget to tag this?

**Comment by Jacob-Lasky** [comment]
I don't see anything within the "File Name Tokens" of the media management tab that references series information. Unless I'm mistaken, that would mean that this is not fixed.

**Comment by DreadDragoon** [comment]
Ahh, didn't see this one under open, was looking under feature requests.

If the book series has the option to be multiple series, and the metadata is there since its processed for the series tab, couldnt you make it a selectable option like edition ?

**Comment by bakerboy448** [comment]
Include with #25
