### ISSUE TITLE
Readarr does not recognise book "Bobby March Will Live Forever"

### ISSUE THREAD

**Issue by HairyScot** [Readarr/Readarr#2724]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a number of books by Alan Parks in my Calibre library, but for some reason Readarr does not recognise one of them, "Bobby March Will Live Forever".
The book does exist in Goodreads with the ISBN 9781609456856 which matches that of the book in my Calibre library.

### Expected Behavior

I'd expect Readarr to recognise the book in the same as those by the same author.

### Steps To Reproduce

Try finding the book with Readarr.

### Environment

```markdown
OS: Windows 10 Pro X64 22H2 Build 19045.3271
Readarr: Readarr 0.2.4.1999
Docker Install: No
Using Reverse Proxy: No
Browser: Firefox 115.0.2
Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[Readarr.2.txt](https://github.com/Readarr/Readarr/files/12189206/Readarr.2.txt)
[Readarr.1.txt](https://github.com/Readarr/Readarr/files/12189207/Readarr.1.txt)
[Readarr.0.txt](https://github.com/Readarr/Readarr/files/12189208/Readarr.0.txt)
[Readarr.txt](https://github.com/Readarr/Readarr/files/12189210/Readarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Info logs are not the required trace logs
Multiple log files are not needed
Simple checking the box saying the wiki was followed does not make the wiki followed

**Comment by HairyScot** [comment]
I will make use of Reddit and Discord, however I am convinced that there is
a bug
