### ISSUE TITLE
no file extensions for audiobooks

### ISSUE THREAD

**Issue by TomW1605** [Readarr/Readarr#28]
despite having audio quality profiles there are no file extensions listed for audio files in [MediaFileExtensions.cs](https://github.com/Readarr/Readarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs)

**Comment by ta264** [comment]
There's a lot of work to do to support audiobooks. I plan to sort regular books first so don't expect progress for a while

**Comment by TomW1605** [comment]
that's fine i just figured it might as well be documented

**Comment by madknave** [comment]
I know this is down the line and low priority at the moment, but is there a plan for audiobooks with multiple files (i.e. separated chapters)? I'm all about merging these type of abooks (and maybe standardizing to an m4b file type).

Just wanted to leave a floating thought for when you start working on developing this part.
