### ISSUE TITLE
Title Search info before colon

### ISSUE THREAD

**Issue by kahn10** [Readarr/Readarr#29]
Most books have their slug included in their name (e.g. Pooping: The Story of our Productivity by Jane Austen), but that is not always included in torrents. Between the title and the author, this slug probably isn't needed, so could be filtered out from searches (e.g Jane Austen Pooping)

**Comment by bakerboy448** [comment]
How's this looking on recent builds?

**Comment by kahn10** [comment]
It's hard to prove a negative. Without seeing the code that executes the search I can't say if this feature request has been implemented.
