### ISSUE TITLE
Crash Loop with 2207

### ISSUE THREAD

**Issue by jordanfelle** [Readarr/Readarr#2911]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After upgrading from 2203 to 2207 readarr is stuck crash looping. I have 2 instances and both experienced this bug. Moving back to 2203 fixed the issue. Attempted restoring DBs from a backup, and deleting the cache.db.

### Expected Behavior

Readarr starts after upgrade

### Steps To Reproduce

Run 2203
Upgrade to 2207
See logs of crashloop

### Environment

```markdown
- OS: Ubuntu 22.04
- Readarr: 0.3.4.2207
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: 116.0.5845.180 (Official Build) (64-bit)
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

```
[Info] Bootstrap: Starting Readarr - /app/readarr/bin/Readarr - Version 0.3.4.2207 
[Debug] Bootstrap: Getting windows service status 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Trace] EventAggregator: Publishing ApplicationStartingEvent 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/readarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationController: Took: 00:00:00.0849860 
[Info] MigrationController: *** Migrating data source=/config/cache.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationController: Took: 00:00:00.0021988 
[Trace] EventAggregator: ApplicationStartingEvent -> InstallUpdateService 
[Trace] EventAggregator: ApplicationStartingEvent <- InstallUpdateService 
[Info] Bootstrap: Starting Readarr - /app/readarr/bin/Readarr - Version 0.3.4.2207 
[Debug] Bootstrap: Getting windows service status 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Trace] EventAggregator: Publishing ApplicationStartingEvent 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/readarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationController: Took: 00:00:00.0841762 
[Info] MigrationController: *** Migrating data source=/config/cache.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationController: Took: 00:00:00.0023008 
[Trace] EventAggregator: ApplicationStartingEvent -> InstallUpdateService 
[Trace] EventAggregator: ApplicationStartingEvent <- InstallUpdateService 
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- logs from the log file not console output as the wiki specifies
- Updater logs as well as it looks like it's looping and trying to install an update...but that shouldn't be possible with docker
- anything configured on your system to start or restart readarr?
- Is the container set to restart always?
- Who's container?

**Comment by mynameisbogdan** [comment]
Considering the only differences between them are some translations and a fix for qbittorrent, I doubt it's any of them.

c4850505b011af6313e4c5dea561e4bdafb44629...75efbd45e14dbbd6a2ac328343cc5237e7758dcf

**Comment by bakerboy448** [comment]
Invalid bug report; closing.
