### ISSUE TITLE
Readarr raise a lot of `BookInfo returned 429, backing off for 10s`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Readarr/Readarr#2970]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Readarr raise a lot of (every 10s):

```
BookInfo returned 429, backing off for 10s
```

### Expected Behavior

Maybe `readarr` could increase the backoff time ? maybe use an exponantial backoff with a upper-limit :thinking: 

On the other hand I don't know why `bookinfo` return a `429 too many request` 🫤

### Steps To Reproduce

With docker:

```shell
mkdir /tmp/readarr-data /tmp/readarr-books
docker run \
  -it --rm --user $UID:$GID \
  --volume /tmp/readarr-data:/config \
  --volume /tmp/readarr-books:/books \
  --publish 8787:8787 \
  firelightflagbot/readarr:0.3.6.2232
```

After goto <localhost:8787> and search for an author.

In the log of `docker run ..` I see the `BookInfo returned 429, backing off for 10s` appearing

### Environment

```markdown
- OS: alpine-3.18
- Readarr: 0.3.6.2232
- Docker Install: Yes (kubernetes)
- Using Reverse Proxy: No
- Browser: N/A
- Database: 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

[readarr-2023-10-06.log](https://github.com/Readarr/Readarr/files/12829149/readarr-2023-10-06.log)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by FirelightFlagboy** [comment]
~Hello @bakerboy448~

~I've already included the log with the trace level (cf the file `readarr-2023-10-06.log`).~

I see what I'm missing sadly I'm currently getting that type of error

```

[Warn] BookInfoProxy: Error mapping search results 

[v0.3.6.2232] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapBulkBook(BulkBookResource resource) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 510
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
   at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 297
```

I'll retry later

**Comment by bart-kooi** [comment]
I am also getting the above error.
Tried a fresh install in both docker and windows with v0.3.6.2232 and immediately getting the Error mapping search results error

**Comment by FirelightFlagboy** [comment]
I'm not able to replicate this issue as of today (2023-10-11) with the version `0.3.6.2232` (nothing change on my side)

So I'll close this issue

**Comment by albertomrossi** [comment]
error still happening both on the latest release and on #nightly:0.3.6.22

**Comment by bakerboy448** [comment]
https://github.com/Readarr/Readarr/issues/2783#issuecomment-1798940946

**Comment by scuppasteve** [comment]
This is happening to me as well. I am unable to search for new authors or books. I am on the nightly build

Version
0.3.10.2287
Package Version
nightly-b025e94 by [hotio](https://github.com/hotio)

[readarr.txt](https://github.com/Readarr/Readarr/files/13325880/readarr.txt)

**Comment by laserjet25** [comment]
Can confirm this is happening to me as well on a fresh install.
v0.3.10.2287
Windows 10 x64 installer from website.

![image](https://github.com/Readarr/Readarr/assets/7650139/1ab5ee0d-bd42-4452-bbf6-d097d7f698c5)

**Comment by scuppasteve** [comment]
> Can confirm this is happening to me as well on a fresh install. v0.3.10.2287 Windows 10 x64 installer from website.
> 
> ![image](https://user-images.githubusercontent.com/7650139/284761419-1ab5ee0d-bd42-4452-bbf6-d097d7f698c5.png)

Hey if you go on the discord you will see the Metadata provider is not working and its going to be a bit before it gets fixed.

**Comment by laserjet25** [comment]
> > Can confirm this is happening to me as well on a fresh install. v0.3.10.2287 Windows 10 x64 installer from website.
> > ![image](https://user-images.githubusercontent.com/7650139/284761419-1ab5ee0d-bd42-4452-bbf6-d097d7f698c5.png)
> 
> Hey if you go on the discord you will see the Metadata provider is not working and its going to be a bit before it gets fixed.

While I appreciate your note, I have already found this being alluded to through other issues (#2783) opened here. Discord is not the right place to be informing people of these issues. If anything, this issue should be pinned alongside the above and/or there should be a notice on the Radarr website. Not much point if *tracking* issues on Github if the conversation about said issues goes elsewhere.

/rant over, Discord is 0/10 and I'm already in too many servers I used once.

**Comment by bakerboy448** [comment]
@laserjet25 https://github.com/Readarr/Readarr/issues/2783#issuecomment-1798940946 and this thread

also the healthcheck RE the metadata server in App

> We are currently experiencing issues with our metadata provider, this will prevent user searches and author refreshes from working. We are working to solve the issue.

**Comment by bakerboy448** [comment]
Latest update / [pinned discord post ](https://discord.com/channels/264387956343570434/1028840624864120872/1176254480593997904)

> Currently the Readarr metadata server is mostly down. This will prevent you from doing searches for or adding books and authors. There is no timeline for getting it back up, but the devs are still working on it. It's been reported to be slightly up currently, and some users are able to occasionally perform a search and add an author. The metadata server is not open source, and there is nothing you can do to help get it back up. Please be patient and it will be operational soon. Also a reminder that Readarr is (very) beta software and will have issues like this fairly regularly, and if that is a deal-breaker for your book library you may want to explore alternatives until it's more stable. You can add SOME authors by finding the author ID number on goodreads (it's part of the URL) and adding it to readarr by using author:authorid in the search. Note that this is a separate issue from the "large author" issue which is ongoing and will not be solved when this comes back up. We know, it's been down for a long time. We know this is an inconvenience to you. We do not have an ETA. It is not a regular occurrence. This also does not impact searching for downloads of books and authors you already have in Readarr, and importing those.

Current as of 2033-11-27 1143UTC
