### ISSUE TITLE
system health message "Download client sabnzbd is set to remove completed downloads..." displaying although the remove option is not enabled in my sabnzbd client 

### ISSUE THREAD

**Issue by geolaw** [Readarr/Readarr#2972]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

system health warning is displaying 
Download client sabnzbd is set to remove completed downloads. This can result in downloads being removed from your client before Readarr can import them.

the remove option is not set in my download client ... 

trace logs with a fresh restart and screenshots attached

### Expected Behavior

health warning should not be displayed as the "remove downloads" is not set in sabnzbd

### Steps To Reproduce

my sabnzbd is also containerized, running on the same host machine.
as soon as I restart the readarr container, the health warning pops up.
i did a fresh pull on the container image. 

I am on fedora 38, so I am using podman and not docker

### Environment

```markdown
- OS:  fedora 38
- Readarr:0.3.6.2232-ls66 by linuxserver.io
- Docker Install: yes  (podman) 
- Using Reverse Proxy: no
- Browser: firefox
- Database:Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

[readarr.trace.txt](https://github.com/Readarr/Readarr/files/12839450/readarr.trace.txt)
![Screen Shot 2023-10-07 at 7 53 33 PM](https://github.com/Readarr/Readarr/assets/1840954/08b767ee-1d78-43b4-9346-ecc02c27f86c)
![Screen Shot 2023-10-07 at 7 53 15 PM](https://github.com/Readarr/Readarr/assets/1840954/9b6feaa1-8818-4695-921a-d8e8c52bf41a)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
This should be already fixed in 4a6c7042fe65c4adf5a8f613d86944f0c92721ea

**Comment by geolaw** [comment]
What version is the fix in? 
I'm running     0.3.6.2232 - which just before I submitted the bug report, I did a fresh podman pull of the container.

**Comment by mynameisbogdan** [comment]
It's in nightly only, soon it will be in develop too.
