### ISSUE TITLE
Unable to import audiobook.  Get Value cannot be null. (Parameter 'fileName') Error

### ISSUE THREAD

**Issue by SpartacusIam** [Readarr/Readarr#3012]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I try to do an automatic or interactive import, I get the following error:

`Value cannot be null. (Parameter 'fileName')`

### Expected Behavior

Book should import from downloads to audiobooks root folder

### Steps To Reproduce

1.  Go to Wanted
2.  Choose Manual Import
3. Browser to location of audiobook
4. Hit interactive import
5. Confirm it matches the intended book
6. Hit import

### Environment

```markdown
- OS: Debian
- Readarr: 0.3.7.2260
- Docker Install: hotio
- Using Reverse Proxy: yes
- Browser: Chrome
- Database: internal
```

### What branch are you running?

Master

### Trace Logs?

[readarr.trace.txt](https://github.com/Readarr/Readarr/files/13043603/readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
This should be fixed, but it seems to me that you're trying to import an audio book media to a spoken book. That's correct?

**Comment by SpartacusIam** [comment]
> This should be fixed, but it seems to me that you're trying to import an audio book media to a spoken book. That's correct?

Are spoken books and audio books not the same in readarr?  I choose spoken book because the only options I see are eBook and Spoken book.  I assumed spoken book meant audio book.

**Comment by mynameisbogdan** [comment]
Yeah, sorry. My head is in multiple places. That's correct, audiobook to ebook.

**Comment by SpartacusIam** [comment]
> Yeah, sorry. My head is in multiple places. That's correct, audiobook to ebook.

Are you saying I should be importing audiobooks (m4b in this case) to ebooks instead of spoken books?

**Comment by mynameisbogdan** [comment]
I'm saying you should be importing audiobooks to spoken books, because in the error it looks like you're trying to import m4b to an ebook. I'm not familar with calibre, but it only checks for ebooks formats here:

https://github.com/Readarr/Readarr/blob/64fafc599c58f466970972af131e55527c92b139/src/NzbDrone.Core/Books/Calibre/CalibreProxy.cs#L73

**Comment by SpartacusIam** [comment]
I'm not trying to import to ebooks.  See the screenshots below.

![image](https://github.com/Readarr/Readarr/assets/16405200/24ec927c-6053-4500-a9bb-6bd62e1977e1)
![image](https://github.com/Readarr/Readarr/assets/16405200/cfbbfda1-cd51-4450-b6f6-8539df1741b8)
