### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by HammyHavoc** [Readarr/Readarr#3018]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm trying to organize my library of public domain books, and I just don't see a lot of the options mentioned on https://wiki.servarr.com/readarr/quick-start-guide, e.g., "Folders" or "Importing".

### Expected Behavior

That the options would be there.

### Steps To Reproduce

1. Go to `/settings/mediamanagement`

### Environment

```markdown
- OS: Unraid
- Readarr: 0.3.9.2272-1 by fryfrog
- Docker Install: binhex/arch-readarr
- Using Reverse Proxy: No, only available on my LAN
- Browser: Vivaldi
- Database: Whatever comes with binhex/arch-readarr, assumedly sqlite.
```

### What branch are you running?

Master

### Trace Logs?

N/A.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
Make sure show advanced is on.

**Comment by HammyHavoc** [comment]
> Make sure show advanced is on.

OK, now I just feel silly! Lmao, thank you! :- )
