### ISSUE TITLE
Ability to Set Release Group from UI for BookFiles

### ISSUE THREAD

**Issue by Indemnity83** [Readarr/Readarr#3109]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

the Readarr API appears to support the "ReleaseGroup" concept that is common in the 'arr' apps, but there doesn't seem to be any way to actually see or edit it from the UI (the edit wrench is missing on the files interface). I'd like to set a "release group" for some of my files which have been collected manually (like buying the audiobook on a kickstarter) so I can then remember where the book came from. 

### Describe the solution you'd like

Can the wrench/edit be re-enabled on the book file interface, or is there something holding that up?

### Describe alternatives you've considered

I can also "unmonitored" the books that I've manually imported, but then its not easy to determine where the book came from or why it is unmonitored. I would like to just set a custom format to score my manual release groups extremely high to prevent them from being replaced in the future.  

### Anything else?

Missing wrench icon location: 

<img width="1206" alt="Screenshot 2023-12-01 at 1 06 31 PM" src="https://github.com/Readarr/Readarr/assets/35218/cc51accd-c534-43aa-9378-e6fd6b2ab464">

**Comment by mynameisbogdan** [comment]
You can already, use have to use `manual import` from the author's page with the filter all files and do a re-import.
