### ISSUE TITLE
Base Url support for Deluge

### ISSUE THREAD

**Issue by jokob-sk** [Readarr/Readarr#3137]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm unable to connect to my existing Deluge instance the same way as from the other *arr apps, like Radarr as the Base URL configuration option is missing

### Describe the solution you'd like

I'd like the same Base URL option on the Deluge download client as in Radarr

![image](https://github.com/Readarr/Readarr/assets/96159884/ba695ffe-2e77-4f51-8e6b-ae73d2d3099b)

### Describe alternatives you've considered

Using a different downloader (e.g. ruTorrent), but ruTorrent seems unreliable and I have to manage two different download clients

### Anything else?

This would also bring the Deluge downloader to feature parity with the other *arr suite apps. Thanks in advance 🙏

**Comment by bakerboy448** [comment]
Turn on advanced options.

**Comment by jokob-sk** [comment]
thanks a lot @bakerboy448 - I completely missed this
