### ISSUE TITLE
Goodreads Import List skipping books

### ISSUE THREAD

**Issue by Rubicj** [Readarr/Readarr#3169]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have a Goodreads list. It has 59 items on it. When I run a sync in Readarr, the logs say 71 items was imported. However, at least 1 of the books on the Goodreads List is not imported to Readarr.

I also confirmed similiar behavior for a Goodreads bookshelf import -- 550 books in Goodreads, 479 in logs.

### Expected Behavior

59 books should be imported to Readarr.

### Steps To Reproduce

1. Set up a Goodreads list with a sizeable number of books.
2. Import to Readarr
3. Compare -- some are missing.

### Environment

```markdown
- OS: Unraid
- Readarr: 0.3.14.2358
- Docker Install:Yes - hotio/readarr:latest
- Using Reverse Proxy:No
- Browser:Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

https://privatebin.net/?4b9a08cde868ab14#DxXfjgk5ypKMoa9v8Y4pppSQxqeXhw3q8r3PixB66eXx

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
```
2024-01-08 18:38:57.2|Trace|HttpClient|Res: HTTP/2.0 [GET] https://api.bookinfo.club/v1/work/151574980: 302.Redirect (0 bytes) (336 ms)
2024-01-08 18:38:57.2|Error|AddBookService|Book with Foreign Id 151574980 was not found, it may have been removed from Goodreads.
2024-01-08 18:38:57.2|Error|AddBookService|Failed to import id: 151574980 - 

[v0.3.14.2358] FluentValidation.ValidationException: Validation failed: 
 -- GoodreadsId: A book with this ID was not found
 ```

**Comment by Rubicj** [comment]
@bakerboy448 Sorry, I should have been more specific. That error is for book [151574980](https://www.goodreads.com/book/show/151574980), which makes sense. I am looking for the book with Goodreads ID 58395042, which is clearly present on Goodreads list 189595, and yet is not present in the 71 imported books.

**Comment by Rubicj** [comment]
I can confirm this is still happening after the metadata server issues today. There are _many_ books on list 189595 that don't show up. I spot checked seven -- 4 don't show up in the logs, 3 do:

On the list, and not in the logs:
- [58395042](https://www.goodreads.com/book/show/58395042-the-league-of-gentlewomen-witches)
- [145624782](https://www.goodreads.com/book/show/145624782-the-city-of-stardust)
- [3974470](https://www.goodreads.com/book/show/3974470-crooked-houses)
- [195820807](https://www.goodreads.com/book/show/195820807-just-for-the-summer)

On the list, and in the logs:
- [157981739](https://www.goodreads.com/book/show/157981739-faebound)
- [196726166](https://www.goodreads.com/book/show/196726166-the-honey-witch)
- [122494718](https://www.goodreads.com/book/show/122494718-in-the-weeds)

I also spot checked 8 of the 71 ids in the logs, and they're also split

In the logs, and on the list:
- [75673878](https://www.goodreads.com/book/show/75673878)
- [48988286](https://www.goodreads.com/book/show/48988286)
- [60784419](https://www.goodreads.com/book/show/60784419)
- [127306440](https://www.goodreads.com/book/show/127306440)
- [6043781](https://www.goodreads.com/book/show/6043781)

In the logs, and NOT on the list: (Where the hell did these come from???)
- [59747519](https://www.goodreads.com/book/show/59747519)
- [16299](https://www.goodreads.com/book/show/16299)
- [59441717](https://www.goodreads.com/book/show/59441717)
