### ISSUE TITLE
Unable to Save General Settings Changes with a Modified Instance Name

### ISSUE THREAD

**Issue by hibes** [Readarr/Readarr#3367]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

With a modified instance name
```
$ cat listenarr/config/config.xml | grep Insta
  <InstanceName>listenarr</InstanceName>
```

An attempt to save changes results in a 400 bad request and does not change the config:
![image](https://github.com/Readarr/Readarr/assets/5987489/a073349e-684c-4ced-8c07-f1ab8ee7a9a0)

An immediate workaround is to revert to the default instance name (`readarr`) and then restart the container, refresh the page, perform the changes, change the instance name back to the desired name, and then restart again.

### Expected Behavior

With a modified instance name, saving settings should result in a 200 and successfully change the underlying settings.

### Steps To Reproduce

1. Configure a custom instance name
2. Restart to apply the custom instance name
3. Open Settings=>General
4. Toggle the checkbox for Analytics => Send Anonymous Usage Data
5. Open the browser's inspector to the console tab
6. Click Save Changes
7. Observe the 400 error in the console (it does not show up in the network tab so you can only observe it in the console as far as I know)

### Environment

```markdown
- OS: Linux
- Readarr: 0.3.19.2437
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 123.0.1 (64-bit)
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs?

![image](https://github.com/Readarr/Readarr/assets/5987489/a073349e-684c-4ced-8c07-f1ab8ee7a9a0)
[readarr.trace.txt](https://github.com/Readarr/Readarr/files/14627791/readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mynameisbogdan** [comment]
That's correct, instance name must contain `Readarr` to be valid. If you enable `Show Advanced` you will see the validation errors more properly.

https://github.com/Readarr/Readarr/blob/28f64d9a4665c69e7d327cc706cd6c9af1a0100c/src/Readarr.Api.V1/Config/HostConfigController.cs#L43
