### ISSUE TITLE
Trying to add a any new item fails

### ISSUE THREAD

**Issue by t3knoid** [Readarr/Readarr#34]
**Describe the bug**
Trying to add any new item fails. For example, entering "War and peace" yields "Failed to load search results, please try again." error in the UI.

**To Reproduce**
1. Click on 'Add New" from left menu
2. In the search text box, enter "War and peace"
3. Observe "Failed to load search results, please try again." is displayed.

**Expected behavior**
Entered book should show.

**Logs**
Here's a log snippet using trace level. Notice 404 error accessing api.readarr.com

> 20-6-1 13:26:41.6|Trace|ReadarrErrorPipeline|Handling Exception
20-6-1 13:26:41.6|Trace|Http|Res: 8700 [GET] /api/v1/search?term=War%20and%20pea: 503.ServiceUnavailable (137 ms)
>20-6-1 13:26:41.6|Debug|Api|[GET] /api/v1/search?term=War%20and%20pea: 503.ServiceUnavailable (137 ms)
>20-6-1 13:26:42.8|Trace|Http|Req: 8701 [GET] /api/v1/search?term=War%20and%20peace
>20-6-1 13:26:42.8|Trace|ConfigService|Using default config value for 'metadatasource' defaultValue:''
>20-6-1 13:26:42.8|Trace|HttpClient|Req: [GET] https://api.readarr.com/v0.2/search?q=war%20and%20peace
>20-6-1 13:26:42.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
>20-6-1 13:26:42.9|Trace|HttpClient|Res: [GET] https://api.readarr.com/v0.2/search?q=war%20and%20peace: 404.NotFound
404 page not found
 (110 ms)
>20-6-1 13:26:42.9|Warn|HttpClient|HTTP Error - Res: [GET] https://api.readarr.com/v0.2/search?q=war%20and%20peace: 404.NotFound
404 page not found

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.105

**Additional context**
Readarr running in a Docker container.

**Comment by ta264** [comment]
API is down, not sure when it'll be back

**Comment by t3knoid** [comment]
I was prompted to enter this issue after running into it I looked in Reddit and Discord and read of others seeing this issue.

**Comment by t3knoid** [comment]
> API is down, not sure when it'll be back

Understood. Hope to see it get back soon. Is there a possible workaround?

**Comment by ta264** [comment]
Lazylibrarian ;)

See the discord channel for details

**Comment by t3knoid** [comment]
Thanks. Stood up Lazylibrarian. Looking forward to see Readarr back up. Thanks again for the tip.

**Comment by codywarmbo** [comment]
Are we able to use our own API key for this?

**Comment by ta264** [comment]
Fixed
