### ISSUE TITLE
Magazines

### ISSUE THREAD

**Issue by Nautilus34** [Readarr/Readarr#3451]
Hello

Is it possible to add a function for magazines ?

It seems to me that a lot of people are asking for this feature.

Thank you

**Comment by bakerboy448** [comment]
> It seems to me that a lot of people are asking for this feature.

not a single prior GitHub issue exists.

> Is it possible to add a function for magazines ?

no plans to add specific support for magazines

**Comment by manuelkamp** [comment]
how unfortunate, that would be the only usecase for me to use Readarr, to get new Magazines as soon as they are downloadable. I do not see any usecase in automatic downloads for books, it is easier to direct download them instead via Readarr...

**Comment by Nautilus34** [comment]
Hello @bakerboy448 

Has your thinking on the subject evolved? 
The topic of magazines has been discussed in several conversations. 

Would it be possible to consider this feature? 
Maybe we can help? 

Thank you for your work.

**Comment by bakerboy448** [comment]
> no plans to add specific support for magazines

does not and will not change the answer.

Readarr also currently has no active developers at this time.
Similarly due to ongoing goodreads issues it's likely the metadata and app need to be rewrote to switch to openlibrary from goodreads
