### ISSUE TITLE
Display error message if search is down

### ISSUE THREAD

**Issue by ThatDeltaGuy** [Readarr/Readarr#3488]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, if the Add new search functionality is down, it will still return the message “Couldn't find any results for '*****'”, the same as if it couldn't actually find anything. 

### Describe the solution you'd like

It should display a different message to indicate that the search functionality is currently down and to wait for a bit.

### Describe alternatives you've considered

There arent any

### Anything else?

Currently, as there's no distinction between it being down or just not found, people will try to hammer the search with different variations and waste time trying to get it to work, which is bad UX but can also slow the recovery time of the search API.

**Comment by Span24** [comment]
Additionally, Discord support gets overwhelmed with reports of search failing.
This solution could alleviate much of those inquiries by informing the user that search is unavailable/down.

**Comment by bakerboy448** [comment]
Search is restored

**Comment by tmowbrey** [comment]
I don't think this should be closed. There is a valid use case for this ask. If we close this with the shown related issue, it's the same as removing functionally for indexer errors and asking the user to look at each indexer for status.

**Comment by mynameisbogdan** [comment]
It was implemented as requested, with a link to the wiki that can be updated without the need of a new build of Readarr. So, what you're talking about?

**Comment by tmowbrey** [comment]
All good, I didn't follow the thread all the way. I thought the answer was to only check the status page. I see thst the actual fix was implemented. Apologies for the incorrect prior comment.

**Comment by mynameisbogdan** [comment]
It looks like this:
![image](https://github.com/Readarr/Readarr/assets/707714/03115b5d-3c6b-4ce0-b37c-6b2f888868a0)

And the link is https://wiki.servarr.com/readarr/troubleshooting#invalid-response-received-from-metadata-api
