### ISSUE TITLE
readarr mode:service 0.1.0.148 unable to add indexer

### ISSUE THREAD

**Issue by garfield69** [Readarr/Readarr#355]
**Describe the bug**
unable to add indexer

**To Reproduce**
1. Go to settings > indexers
2. Click on plus button
```
Add Indexer
Unable to add a new indexer, please try again.
```

**Expected behavior**
expected torznab panel to define a jackett indexer

**Screenshots**
![image](https://user-images.githubusercontent.com/6933240/89579949-b9a56e80-d888-11ea-8f77-7cd11cfbc9c6.png)

**Logs**
Link to debug logs.
![image](https://user-images.githubusercontent.com/6933240/89579889-a5fa0800-d888-11ea-8e76-f70d43e009d0.png)

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.148
 - Operating System Win10Home
 - .net Framework (Windows) Version: 4.7.2

**Additional context**
readarr download package [Readarr.develop.0.1.0.148.windows-core-x64-installer.exe](https://artprodcus3.artifacts.visualstudio.com/Af2b01d57-4f38-4d91-acc9-412d59f0a070/34393bab-b896-4651-a109-cddb27254e55/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL1JlYWRhcnIvcHJvamVjdElkLzM0MzkzYmFiLWI4OTYtNDY1MS1hMTA5LWNkZGIyNzI1NGU1NS9idWlsZElkLzIwOS9hcnRpZmFjdE5hbWUvV2luZG93c0luc3RhbGxlcg2/content?format=file&subPath=%2FReadarr.develop.0.1.0.148.windows-core-x64-installer.exe)

**Comment by ta264** [comment]
Yes sorry, thanks for the report. Will get a fix out tomorrow.

**Comment by ta264** [comment]
Should be fixed now.
