### ISSUE TITLE
Unable to add new book/author

### ISSUE THREAD

**Issue by MadDucks** [Readarr/Readarr#360]
**Describe the bug**
Certain authors/books cannot be added to readarr. 

**To Reproduce**
1. Go to 'Library'
2. Click on 'Add New'
3. Search for the book  'The Sparrow'
4. Click on either the Author or the Book
4. Click on the 'Add [Authors Name]' and watch the button process

**Expected behavior**
Readarr should add the selected Author/Book.

**Logs**

ReadarrErrorPipeline | Request Failed. POST /api/v1/author: Sequence contains no matching element | 11:31am |  
-- | -- | -- | --
  | ReadarrErrorPipeline | System.InvalidOperationException: Sequence contains no matching element at System.Linq.ThrowHelper.ThrowNoMatchException() at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate) at NzbDrone.Core.MetadataSource.Goodreads.GoodreadsProxy.GetAuthorInfo(String foreignAuthorId) in d:\a\1\s\src\NzbDrone.Core\MetadataSource\Goodreads\GoodreadsProxy.cs:line 102 at NzbDrone.Core.Books.AddAuthorService.AddSkyhookData(Author newAuthor) in d:\a\1\s\src\NzbDrone.Core\Books\Services\AddAuthorService.cs:line 106 at NzbDrone.Core.Books.AddAuthorService.AddAuthor(Author newAuthor, Boolean doRefresh) in d:\a\1\s\src\NzbDrone.Core\Books\Services\AddAuthorService.cs:line 63 at Readarr.Api.V1.Author.AuthorModule.AddAuthor(AuthorResource authorResource) in d:\a\1\s\src\Readarr.Api.V1\Author\AuthorModule.cs:line 138 at Readarr.Http.REST.RestModule`1.<set_CreateResource>b__42_0(Object options) in d:\a\1\s\src\Readarr.Http\REST\RestModule.cs:line 190 at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args) at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct) at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken) at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context) at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken) at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines): Sequence contains no matching element

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.159
 - Operating System: Linux
 - .net Framework (Windows) or mono (macOS/Linux) Version: hotio Docker version

**Comment by blitzaxt** [comment]
I am having this same issue with the docker version.
Thanks!

**Comment by blitzaxt** [comment]
I'm having this issue as well, did you ever figure it out?
Thanks!

Edit:
I was able to workaround this by dropping back to unstable-13bb8ff.

Edit 2:
That workaround may not be stable I was able to add C.S. Lewis and Frank Herbert but not Nick Offerman. I wonder if that is a problem with Nick Offerman in particular.

**Comment by MadDucks** [comment]
No - Though the team asked me in Discord to put in this report.  I haven't really looked at the code, but it looks like the data coming back from goodreads doesn't contain all the info that readarr wants.  I haven't had a chance to chase that bug (and I could be totally wrong from my cursory view of what's causing the bug.)
