### ISSUE TITLE
Tasks are re-added after deletion if service is restarted.  And author Refresh/Scan triggers complete library scan. 

### ISSUE THREAD

**Issue by Paelsmoessan** [Readarr/Readarr#3627]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have searched for this issue and have not found an answer. 
When deleting queued tasks and then restarting Readarr the deleted tasks are re-added. Is there a way to scrub these deleted pending tasks?  Also when scanning/refreshing single Author Readarr keeps starting complete library scans for some reason. 

### Expected Behavior

When tasks are deleted they should stay deleted. Scanning should just be performed on Author Folder. 

### Steps To Reproduce

Start some refresh author tasks, delete the ones in queue and restart service. 

### Environment

```markdown
- OS: Windows server 2019
- Readarr: 0.3.32.2587
- Docker Install: N/A
- Using Reverse Proxy: yes /nginx
- Browser: Chromium
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[logs.zip](https://github.com/user-attachments/files/16529359/logs.zip)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Additionally: 
- invalid bug report, zipped logs are not appropriate
- not a bug

**Comment by Paelsmoessan** [comment]
@bakerboy448, What was wrong with the logs?
I started trace logs, deleted the tasks and restarted service. 
Tasks got added...

**Comment by Paelsmoessan** [comment]
Where are the pending tasks stored? In the DBs or somewhere else? Help me find why it's going wrong. 
The DBs do not have any obvious pending task entries.

**Comment by bakerboy448** [comment]
Please use [Discord](http://readarr.com/discord) for support/questions.
