### ISSUE TITLE
Exclude certain library folders from import-scans (Unmapped Files).

### ISSUE THREAD

**Issue by Paelsmoessan** [Readarr/Readarr#3628]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be excellent if there was an option to exclude certain library folders from import-scans, especially while bookinfo is not working correctly. The current state makes it practically impossible to manage the library since when you add files to folders and perform a scan on that author it triggers scanning of all unmapped files which are not mappable. This takes a long time due to having quite a few authors that aren't available in bookinfo. 

### Describe the solution you'd like

A comma-separated list of folder exclusions for library-paths.  

### Describe alternatives you've considered

Using multiple libraries I guess, one with functioning authors and one without. Would be great with a complete list in that case.

### Anything else?

Nothing of interest to add.

**Comment by bakerboy448** [comment]
No Plans.
Readarr owns its root folder. Remove the files from Readarr's folder if you don't want readarr to manage it

**Comment by bhaveman** [comment]
With respect, I'm not sure why owning the root folder has much bearing on having a table with an ignore list.

**Comment by bakerboy448** [comment]
Again, no plans.
