### ISSUE TITLE
[Feature Request] Send Series Info to Calibre on import

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#371]
Readarr is now doing an excellent job at pushing most of the metadata into Calibre. One of the more notable fields missing is Series info, which Readarr does seem to have already. Is this something that can be pushed.

The other fields missing are
1. Genres -- No way to get these from GR
2. Page Count -- Readarr can pull this from GR, but it would have to be mapped with custom columns in Calibre as it does not have a readily available field to house this data

**Comment by ta264** [comment]
Fixed in 515751b1e
