### ISSUE TITLE
Manga support

### ISSUE THREAD

**Issue by ThaDaVos** [Readarr/Readarr#3722]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently there's no *Arr application with good Manga support

### Describe the solution you'd like

Readarr to perhaps support Manga

### Describe alternatives you've considered

Manually downloading or using apps like Mihon

### Anything else?

N/A

**Comment by bakerboy448** [comment]
no plans for manga nor comic support
