### ISSUE TITLE
[Feature Request] Book genres

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#375]
Goodreads does not expose genres for a book via its API, but it is a useful parameter that the Calibre GR plugin is able to pull on its metadata download. It helps organize the books in your library, so it definitely is useful to grab. Since I would have to manually do a metadata download in calibre after each import to get this data, I wanted Readarr to be able to push this data by itself.

I know it is not feasible with GR as of now, but opening the issue for transparency and in case anyone else has any other ideas or ways to get this data.

[AB#912](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/912)

**Comment by rg9400** [comment]
The best option for this I think is to use popular shelves from Goodreads, then remap them to genres. The Goodreads plugin does this, and the results are fairly great in my opinion. See the mapping from the plugin source code below

```
                'Anthologies': ['Anthologies'],
                'Adventure': ['Adventure'],
                'Adult Fiction': ['Adult'],
                'Adult': ['Adult'],
                'Art': ['Art'],
                'Biography': ['Biography'],
                'Biography Memoir': ['Biography'],
                'Business': ['Business'],
                'Chick-lit': ['Chick-lit'],
                'Childrens': ['Childrens'],
                'Classics': ['Classics'],
                'Comics': ['Comics'],
                'Graphic Novels Comics': ['Comics'],
                'Contemporary': ['Contemporary'],
                'Cookbooks': ['Cookbooks'],
                'Crime': ['Crime'],
                'Fantasy': ['Fantasy'],
                'Feminism': ['Feminism'],
                'Gardening': ['Gardening'],
                'Gay': ['Gay'],
                'Glbt': ['Gay'],
                'Health': ['Health'],
                'History': ['History'],
                'Historical Fiction': ['Historical'],
                'Horror': ['Horror'],
                'Comedy': ['Humour'],
                'Humor': ['Humour'],
                'Health': ['Health'],
                'Inspirational': ['Inspirational'],
                'Sequential Art > Manga': ['Manga'],
                'Modern': ['Modern'],
                'Music': ['Music'],
                'Mystery': ['Mystery'],
                'Non Fiction': ['Non-Fiction'],
                'Paranormal': ['Paranormal'],
                'Religion': ['Religion'],
                'Philosophy': ['Philosophy'],
                'Politics': ['Politics'],
                'Poetry': ['Poetry'],
                'Psychology': ['Psychology'],
                'Reference': ['Reference'],
                'Romance': ['Romance'],
                'Science': ['Science'],
                'Science Fiction': ['Science Fiction'],
                'Science Fiction Fantasy': ['Science Fiction', 'Fantasy'],
                'Self Help': ['Self Help'],
                'Sociology': ['Sociology'],
                'Spirituality': ['Spirituality'],
                'Suspense': ['Suspense'],
                'Thriller': ['Thriller'],
                'Travel': ['Travel'],
                'Paranormal > Vampires': ['Vampires'],
                'War': ['War'],
                'Western': ['Western'],
                'Language > Writing': ['Writing'],
                'Writing > Essays': ['Writing'],
                'Young Adult': ['Young Adult'],
                }
```

**Comment by lyz-code** [comment]
Another option would be to use other metadata providers, for example Calibre implements genres with tags. Behind the scenes it looks like it uses the
[`fetch-ebook-metadata`](https://manual.calibre-ebook.com/generated/en/fetch-ebook-metadata.html) command line to fetch the data from Google, Google Images, Amazon.com, Edelweiss, Open Library and Big Book Search. With the `-o` flag returns a parseable xml, maybe it could be used within Readarr

**Comment by lyz-code** [comment]
It looks that the genres are already in [the model of the book](https://readarr.com/docs/api/#/Book/get_api_v1_book__id_) so "only" the filling of those genres needs to be implemented

**Comment by ta264** [comment]
Closed by https://github.com/Readarr/Readarr/commit/eb95fe265a960f72c8f1649d341e2f034cf79c5a

**Comment by lyz-code** [comment]
Thank you for the implementation @ta264. I'm using Readarr without Calibre, and I'd like to benefit from the genres too. Do you think the request makes sense for the project scope?  If it is, do you want me to open a new issue?
