### ISSUE TITLE
Readarr no longer removes downloads from qBittorrent

### ISSUE THREAD

**Issue by vincentkoevoets** [Readarr/Readarr#3777]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

Ever since qBittorrent 5.0.0, Readarr no longer seems to interact correctly with qBittorrent. Two things stand out:
- Completed downloads are no longer removed from qBittorrent queue (with or without seeding time).
- Every now and then a download which is still present in qBittorrent, disappears from the Activity tab in Readarr.

I've downgraded qBittorrent to 4.6.7, and everything works fine again. I will attach two trace logs, where I will download the same file in Readarr twice. I'm suspecting qBittorrent has new statuses that Readarr isn't expecting (yet), and this leaves Readarr waiting forever for the correct status in the json response. (Might be this? https://github.com/Readarr/Readarr/issues/3463)

### Expected Behavior

Readarr should remove completed downloads from qBittorrent queue, if this is enabled in Readarr settings. 

### Steps To Reproduce

Enable 'Automatically import completed downloads from download client' in Settings > Download Clients, and enable 'Remove imported downloads from download client history' in qBittorrent download client settings. Then, download a book (an audiobook in my case), and when completed, check the media folder to see the new file present, but also check the download folder to see the file present still. And also, check qBittorrent queue to see the torrent still sitting there, completed. 

### Environment

```markdown
- OS: Debian 12
- Readarr: 0.4.0.2634
- Docker Install: yes (Linuxserver.io)
- Using Reverse Proxy: no
- Browser: - 
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs?

[qbittorrent4.6.7.readarr.trace.txt](https://github.com/user-attachments/files/17229202/qbittorrent4.6.7.readarr.trace.txt)
[qbittorrent5.0.0.readarr.trace.txt](https://github.com/user-attachments/files/17229270/qbittorrent5.0.0.readarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by brokenalarms** [comment]
seconded, the issue is new status codes in qBitTorrent 5 that readarr doesn't recognize, as mentioned here:
https://www.reddit.com/r/sonarr/comments/1fvg31u/solved_issues_with_qbittorrent_500_not_importing/

This also seems to break Calibre integration, since it doesn't know the file is finished so as to add to Calibre.

**Comment by vincentkoevoets** [comment]
> seconded, the issue is new status codes in qBitTorrent 5 that readarr doesn't recognize, as mentioned here: https://www.reddit.com/r/sonarr/comments/1fvg31u/solved_issues_with_qbittorrent_500_not_importing/
> 
> This also seems to break Calibre integration, since it doesn't know the file is finished so as to add to Calibre.

Yes, the new status codes are probably the problem. **However downgrading qBittorrent as mentioned in the subreddit is no longer recommended because of the recently published security vulnerabilities.** 
Let's hope Readarr team will pick up the changes sometime soon.

**Comment by brokenalarms** [comment]
ok well I don't want the vulnerability, and I don't want qBitTorrent to no longer export to Calibre, so I did the PR myself since it looked straightforward - #3874 🙂 . Hopefully that can speed things up.
