### ISSUE TITLE
Readarr starts crashing after adding root folder

### ISSUE THREAD

**Issue by KmtqaxCX** [Readarr/Readarr#3782]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi all.

I installed Readarr on TrueNAS Core and I added a root a folder with default settings.
When clicking the save button, an exclamation mark appears on the button it self, but the root path is created and visible in the  Media Management section including the three green boxes (path and choosen profiles)
After that, the instance begins to be unstable = when navigating through menus, getting the "Failed to load translations from API
Version X.XX.XX", unable to load the WebUI, instance needs many refreshes (F5) to show the WebUI again, unable to add / find any books online (Harry Potter etc...).
When I remove all the files from the AppData Directory : /usr/local/readarr ,the instance is reset to defaults and works again.

I have this issue on both versions : 0.4.0.2634 and 0.3.32.2587
I made no config changes on the instance besides the login authentication screen.
I tested several root folders = chown readarr:readarr and chmod 0777 - no luck.
I tested the default TrueNAS plugin installation with both versions mentioned above and also a clean jail with 0.4.0.2634 version downloaded from the official website.
I also tested the windows version - works fine :/ 
It seems that its specific for TrueNAS / My installation.

I pulled the standard,debug and trace log. The timestamp when I added the root folder and the instance started crashing is around : 2024-10-05 20:10:00

Any pointers are really welcome.

Thank you

### Expected Behavior

Readarr not crashing when adding a root folder.

### Environment

```markdown
- OS: TrueNAS-13.0-U5.3
- Readarr: tested 0.4.0.2634 and 0.3.32.2587
- Docker Install: TrueNAS Jail
- Using Reverse Proxy:
- Browser: Firefox, Chromium
- Database: Sqlite 3.46.1
```

### What branch are you running?

Develop

### Trace Logs?

[readarr.debug.txt](https://github.com/user-attachments/files/17267070/readarr.debug.txt)
[readarr.trace.txt](https://github.com/user-attachments/files/17267071/readarr.trace.txt)
[readarr.txt](https://github.com/user-attachments/files/17267072/readarr.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> TrueNAS-13.0-U5.3

EOL and thus not officially supported

may or may not be related

**Comment by mynameisbogdan** [comment]
Have you tried disabling Watch Folder functionality before adding a new root folder? It's known to be buggy on BSD.

**Comment by KmtqaxCX** [comment]
> > TrueNAS-13.0-U5.3
> 
> EOL and thus not officially supported
> 
> may or may not be related

I am planning a migration to TrueNAS Scale in the near future.



> Have you tried disabling Watch Folder functionality before adding a new root folder? It's known to be buggy on BSD.

Thank you for this, it looks like that this was indeed the problem.
I disabled the functionality and the instance is stable now. I added a root folder with a goodreads integration and all is working as intended.

Cheers :)
