### ISSUE TITLE
Add ability to ignore certain file extensions from being detected / added

### ISSUE THREAD

**Issue by AhmedNSidd** [Readarr/Readarr#3803]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The problem is that suppose I have a folder structure with the folder hierarchy: `Author -> Book -> Book file`. Imagine the `Book` folder can containe `Book files` of two types, audio files (m4b, mp3, etc.) AND eBook files (epub, azw3, mobi, etc.). The problem arises that if I want to use Readarr to maintain this library, then I need two separate Readarr deployments: One that manages Audiobooks and the other that manages eBooks.

This is fine, but the problem arises that each Readarr deployment will end up detecting and adding the books that is supposed to be managed by the other Readarr deployment, so the Audiobook Readarr will end up detecting epub files as well, when I don't want it to.

### Describe the solution you'd like

The best and simplest solution would be to add a field that allows you to ignore certain file extensions from being added / detected. At the moment, I believe Readarr wholesale tries to detect all files of the following types: PDF, MOBI, EPUB, AZW3, Unknown Audio (any audio type?), MP3, M4B, FLAC.

What would be nice is to have the configuration option somewhere that allows us to control which of these formats we actually want to be detected / added from a library.

### Describe alternatives you've considered

The best alternative is to keep the audiobooks and ebooks in separate folders / libraries so they won't interfere with each other, but this is not possible in my use case..

### Anything else?

An example of the tree structure that I'm trying to work with for my library, which Readarr is having a hard time rectifying (since it can't ignore certain file extensions that I want to be ignored):

```
.
└── Eckhart Tolle
    └── The Power of Now
        ├── playlist.ll
        ├── The Power of Now.epub
        ├── The Power of Now.jpg
        ├── The Power of Now.m4b
        └── The Power of Now.opf
```

**Comment by bakerboy448** [comment]
No plans.
As stated in the docs each Readarr instance needs its own root folder
