### ISSUE TITLE
Safari (Only?) Bug Update All Not Working

### ISSUE THREAD

**Issue by rothnd** [Readarr/Readarr#3857]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

'Update all' authors/books does not work at least in Safari on Apple platforms. Must select all in Author Editor then Update selected to get a refresh.

### Expected Behavior

Update All should update all.

### Steps To Reproduce

Open Readarr in Safari
Tap Update all
doesn't do anything

### Environment

```markdown
- OS: macOS 15, iOS 18
- Readarr: 0.4.4.2666
- Docker Install: N
- Using Reverse Proxy: N
- Browser: Safari
- Database: Sqlite 3.36.0
```

### What branch are you running?

Nightly

### Trace Logs?

Needed? Just look like spammy identification info at this point but can provide.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Closing; invalid bug report

**Comment by bobsdacool** [comment]
Hey, just a heads up that this is something that is impacting myself also, on Firefox. Fails for both instances of readarr that I'm running.

Mozilla Firefox 128.4.0esr

Readarr info
Version
    0.4.4.2686
Package Version
    0.4.4.2686-ls131 by [linuxserver.io](https://www.linuxserver.io/) 
.NET Core
    Yes (6.0.35)
Docker
    Yes
Database
    Sqlite 3.45.3
Database Migration
    158
AppData Directory
    /config
Startup Directory
    /app/readarr/bin
Mode
    Console

[readarr.trace.txt](https://github.com/user-attachments/files/17995183/readarr.trace.txt)

Hope this is of help!
