### ISSUE TITLE
Request: Support Regular Expressions (Regex) Patterns in "Must Not Contain" Profile Entries

### ISSUE THREAD

**Issue by sydlexius** [Readarr/Readarr#3873]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've found a similar issue (#1255) requesting for proper support for commas in the regex patterns, but this never seemed to be specifically addressed.  Instead, it seemed to merge a pull request related to custom formats.  Both solutions have good use cases, but I suspect the real world Venn diagram of usage would show some problems are exclusive to one domain ("must not contain") compared to the other "custom profiles").

### Describe the solution you'd like

I don't want to use custom formats to exclude, for example, illustrated or manga editions of books for audiobook profiles.  Additionally, I don't even want to see entries for box sets, omnibus editions, etc.  Variations on words like Volume/Vol/Vol. could easily be handled with proper regex support.

### Describe alternatives you've considered

I've considered and rejected using custom formats for this.  This seems fine when I want to have special cases for collectors editions, preference towards unabridged releases, etc.  This doesn't help with collected works, where there may not even be a digital media release.

### Anything else?

Nothing to suggest, other than I'd like the regex pattern support to be as equally robust as the ones available in custom formats.

**Comment by bakerboy448** [comment]
Regex can already be used in release profiles. Please visit discord for support.

**Comment by sydlexius** [comment]
I've asked my question in the #readarr channel.  In the meanwhile, it might make sense to update the documentation on Servarr so support requests like this don't end up having to be triaged.

**Comment by bakerboy448** [comment]
PR's welcomed https://github.com/Servarr/Wiki/blob/master/readarr/settings.md

**Comment by sydlexius** [comment]
I'd like to request this issue get reopened.  Simple tests like .* in the "Must Not Contain" field should in theory yield 0 books for any author with this profile, but such is not the case.

![image](https://github.com/user-attachments/assets/e9bf7ea1-1a50-449a-ba81-5d9bf5c5c17f)

**Comment by bakerboy448** [comment]
Again, this feature already exists.

`.*` is not regex, it is literal.

Regex needs to be wrapped in `/`

GitHub is not for support.

For support and inquiries, please use our [Discord](http://readarr.com/discord) channel. GitHub is designated solely for bug reports and feature requests. It seems that this issue may fall under a support request, so we kindly ask you to visit our Discord for assistance. Thank you.
