### ISSUE TITLE
[Enhancement] File management for Calibre libraries

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#390]
There are a few things that can be done to smoothen out the handling of Calibre Root Folders

1. Disable the rename option. I am not sure how this would work (only rename in Readarr or rename on disk as well), but it can only mess things up with Calibre since it should not be allowed.

2. Delete from Calibre on delete in Readarr. I tested this, and right now, it deletes the file on disk, but not in Calibre, so Calibre still shows the entry, just without any books. 

EDIT: Also worth noting that when deleting the book from Calibre, it remains shown as downloaded in Readarr, even after rescanning folders and refreshing the author

**Comment by rg9400** [comment]
Further thoughts on this

For deletion, there is an endpoint `@endpoint('/cdb/delete-books/{book_ids}/{library_id=None}',` that should make it easy to delete all the files in Calibre for that book. It might delete files that Readarr is not tracking, but that is probably reasonable.

For renames, instead of disabling it, we can maybe do another call to `set-fields` and `set-cover`. Not sure if this is really a rename or a retag, but it allows a user to leverage Readarr to refresh metadata rather than having to deal with the headache of doing it via Calibre

**Comment by gone** [comment]
+1 on the disable, you can bork over the entire calibre db with a mass rename.
