### ISSUE TITLE
Refresh and Scan Button on an author page scans the entire library instead of the author

### ISSUE THREAD

**Issue by misleadingrhino** [Readarr/Readarr#392]
**Describe the bug**
Refresh and Scan Button on an author page scans the entire library instead of the author

**To Reproduce**
1. Go to any author page. 
2. Click the Refresh and Scan button. 

**Expected behavior**
Only the author's folder is scanned. 

**System info (please complete the following information):**
 - Version 0.1.0.219
 - hotio Docker

**Comment by ta264** [comment]
This is by design since there's no requirement for files to be in author folders (though new downloads will be placed in author folders).

**Comment by misleadingrhino** [comment]
That makes sense. Thank you for your had work!
