### ISSUE TITLE
Unable to reach api.bookinfo.club: Unable to communicate with ReadarrAPI, returning status code: 522.

### ISSUE THREAD

**Issue by DarkGuenther** [Readarr/Readarr#3925]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am not able to use the search function in readarr as when I enter anything I get the following error message in Readarr:
Search for 'test' failed. Unable to communicate with ReadarrAPI, returning status code: 522.
![image](https://github.com/user-attachments/assets/af6569d7-ca25-4363-a60e-81c477658f27)

In journalctl log the following error occurs:
![image](https://github.com/user-attachments/assets/7057542b-a972-4225-a2f8-a7c533851b67)

When I tried to access https://api.bookinfo.club/ manually I would get the following cloudflare error:
![image](https://github.com/user-attachments/assets/ae81b740-6b86-4cb8-8342-5e14ca5eb9ed)

I've tried looking in the Readarr Discord but all publicly avarilable invites I could find seemed to be expired.

### Expected Behavior

Readarr Search function returns found books

### Steps To Reproduce

1. In the Readarr WebUI
2. Search any book

### Environment

```markdown
- OS: Ubuntu 24.04 LTS
- Readarr: 0.4.5.2699
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
- Database: Sqlite 3.45.1
```

### What branch are you running?

Master

### Trace Logs?

Dec 14 11:58:24 media Readarr[3825647]: [Warn] HttpClient: HTTP Error - Res: HTTP/2.0 [POST] https://api.bookinfo.club/v1/book/bulk: 522.522 (15 bytes)
Dec 14 11:58:24 media Readarr[3825647]: error code: 522
Dec 14 11:58:24 media Readarr[3825647]: [Warn] BookInfoProxy: NzbDrone.Common.Http.HttpException: HTTP request failed: [522:522] [POST] at [https://api.bookinfo.club/v1/book/bulk]
Dec 14 11:58:24 media Readarr[3825647]: [v0.4.5.2699] NzbDrone.Common.Http.HttpException: HTTP request failed: [522:522] [POST] at [https://api.bookinfo.club/v1/book/bulk]
Dec 14 11:58:24 media Readarr[3825647]:    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 119
Dec 14 11:58:24 media Readarr[3825647]:    at NzbDrone.Common.Http.HttpClient.PostAsync[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 372
Dec 14 11:58:24 media Readarr[3825647]:    at NzbDrone.Common.Http.HttpClient.Post[T](HttpRequest request) in ./Readarr.Common/Http/HttpClient.cs:line 377
Dec 14 11:58:24 media Readarr[3825647]:    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.MapSearchResult(List`1 ids) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 493
Dec 14 11:58:24 media Readarr[3825647]:    at NzbDrone.Core.MetadataSource.BookInfo.BookInfoProxy.Search(String query, Boolean getAllEditions) in ./Readarr.Core/MetadataSource/BookInfo/BookInfoProxy.cs:line 296
Dec 14 11:58:24 media Readarr[3825647]: error code: 522

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by HJebbour** [comment]
I have the same issue..

**Comment by ghost** [comment]
My best understanding is that the metadata servers are offline. Given that these servers are not operated by the Readarr team (as far as I know), this issue is not under the control of said developers. I think the only thing we can do is wait until the servers are back...

**Comment by bakerboy448** [comment]
> Given that these servers are not operated by the Readarr team

False.

> this issue is not under the control of said developers

It is. It'll be looked into.


The primary development team is engaged in over five applications, including Lidarr, Prowlarr, Radarr, Readarr, Whisparr, and Sonarr. Currently, there is approximately one active developer contributing to these projects, with none of the contributors working on them full-time. Additionally, all members involved, whether in development or support roles, are volunteers and do not receive compensation for their contributions. Each team member balances their commitments alongside full-time jobs, family responsibilities, and other personal obligations.

Readarr has no active developers for the app and the few members that have access to the servers have very limited time at this time.

As a result, the list of tasks to be completed across these projects, along with the various backends and modules, is extensive, while the available time for addressing these tasks is limited.

**Comment by Parabux** [comment]
hope this get resolved soon. thanks for your hard work!

**Comment by bryjogar** [comment]
Would it be possible to also self-host a copy of the API in question here? If the external servers are overloaded and/or struggling for other reasons, enabling users to self host a copy could be an easy path forward. I have ideas on how I could write my own API and redirect DNS traffic to my version so that my data can update, but that's an awful lot of work when you guys have a great API already.

**Comment by bakerboy448** [comment]
No plans for self hosting metadata. Please see the wiki link mentioned in other issues for metadata status and details.

https://wiki.servarr.com/readarr/metadata-issues

**Comment by PriamX** [comment]
Same issue here. Thank you for looking into it.

**Comment by Firenza1972** [comment]
Same issue here, seems new, was it from the update?

Understand you are busy, appreciate the work/time invested in this great app, so no rush.

**Comment by bdorr1105** [comment]
I can confirm this is as well, the same exact issue as well

**Comment by peastuti** [comment]
same here

**Comment by bakerboy448** [comment]
"Me too" and "same here" comments are spam.  

The issue is known.

**Comment by 99brae** [comment]
Anybody have a workaround for this yet?

**Comment by bakerboy448** [comment]
This is not any workaround.

**Comment by 1knueller** [comment]
im new to readarr. i dont have a library yet. i just would be happy to download some books.
my current workaround is to use prowlarr for just downloading books.

id be happy to test a branch where metadata comes from somewhere else

**Comment by bdorr1105** [comment]
> "Me too" and "same here" comments are spam.  
> 
> The issue is known.

That’s great, I will double check telepathically with you next time and read your mind so I know you know

**Comment by lklynet** [comment]
Is it down completely or just intermittently?

**Comment by bakerboy448** [comment]
> Is it down completely or just intermittently?

Completely officially. But some users have reported some authors may work.

Note that this issue is specially the metadata server itself acting up. A change of pace from the other metadata issues specific to Goodreads as the provider.

**Comment by bdorr1105** [comment]
> > > "Me too" and "same here" comments are spam.  
> > > 
> > > The issue is known.
> > 
> > That’s great, I will double check telepathically with you next time and read your mind so I know you know 
> 
> It's clearly pinned and labeled.
> 
> > Is it down completely or just intermittently?
> 
> Completely officially. But some users have reported some authors may work.
> 
> Note that this issue is specially the metadata server itself acting up. A change of pace from the other metadata issues specific to Goodreads as the provider.

Except it isn't, it just says open in the app I don't see a label anywhere. Could be user error but you went out of way to be dbag when all you have to do is ignore it so I'm doing what you would do in this situation and return the favor.

It isn't that serious. This is a cool project and I appreciate the hard work that the developers put into this kind of stuff, just don't appreciate the extra effort to be a dbag

**Comment by bdorr1105** [comment]
> > > "Me too" and "same here" comments are spam.  
> > > 
> > > The issue is known.
> > 
> > That’s great, I will double check telepathically with you next time and read your mind so I know you know 
> 
> It's clearly pinned and labeled.
> 
> > Is it down completely or just intermittently?
> 
> Completely officially. But some users have reported some authors may work.
> 
> Note that this issue is specially the metadata server itself acting up. A change of pace from the other metadata issues specific to Goodreads as the provider.

Who cares, just ignore it. You volunteered to give the extra effort to be a dbag, like went out of your way. This stuff happens all the time. Don't be surprised when you get out what you put in. Great work though

**Comment by yokonzo** [comment]
Apparently this has the unfortunate side effect of removing any authors from readarr when refresh and scan is pressed in the authors page, along with any books, downloaded or not.

**Comment by bakerboy448** [comment]
> Apparently this has the unfortunate side effect of removing any authors from readarr when refresh and scan is pressed in the authors page, along with any books, downloaded or not. 

Please visit Discord with your trace logs if this is the case.

**Comment by yokonzo** [comment]
I will have to do so tomorrow afternoon, but sure thing

**Comment by ProjectInkfish** [comment]
I am setting up a new library and trying to get existing books matched. I am dead in the water until this is fixed, correct?

**Comment by bakerboy448** [comment]
> I am setting up a new library and trying to get existing books matched. I am dead in the water until this is fixed, correct?

Correctish.

> > Is it down completely or just intermittently?
> 
> Completely officially. But some users have reported some authors may work.
> 
> Note that this issue is specially the metadata server itself acting up. A change of pace from the other metadata issues specific to Goodreads as the provider.



> This is not any workaround.

**Comment by rboylesDev** [comment]
> The primary development team is engaged in over five applications, including Lidarr, Prowlarr, Radarr, Readarr, Whisparr, and Sonarr. Currently, there is approximately one active developer contributing to these projects, with none of the contributors working on them full-time. Additionally, all members involved, whether in development or support roles, are volunteers and do not receive compensation for their contributions. Each team member balances their commitments alongside full-time jobs, family responsibilities, and other personal obligations.
> 
> Readarr has no active developers for the app and the few members that have access to the servers have very limited time at this time.
> 
> As a result, the list of tasks to be completed across these projects, along with the various backends and modules, is extensive, while the available time for addressing these tasks is limited.

I think most other developers can understand the feeling of being the sole person and having way too much to do. What I do NOT understand is building an open-source project and then hamstringing it with a tight integration of a closed-source hosted service that can't be easily self-hosted. It's great that Readarr has a backing service for all the metadata, it's not great that it's soo coupled to that service that the software is almost completely unusable without it. The Readarr devs that are active here and on Discord have continually pushed back on any idea of an alternative, whether adding in a feature to use a different external metadata provider or to allow manual modification of the metadata. Yes, someone can fork the code and make those changes. We can totally split off, but it seems those features will never be a part of Readarr and this project and community will continue to suffer for it. 

Thank you for providing such a great piece of software for the audiobook community.

**Comment by gleneccles** [comment]
> Readarr has no active developers for the app and the few members that have access to the servers have very limited time at this time.
> 
> As a result, the list of tasks to be completed across these projects, along with the various backends and modules, is extensive, while the available time for addressing these tasks is limited.

Thanks for this reminder. I hope to have a fix soon, but I have no room to complain. I am capable of doing some dev work so if you need a helping hand I can try my hand at it. But this sounds like it is a problem with a 3rd party API and we would need to integrate with a separate source.

**Comment by bakerboy448** [comment]
Please see the previously linked wiki entry that has the details.

**Comment by bakerboy448** [comment]
Resolved

> Metadata should be fixed, it'll take a day or so to get back to normal reponse times and expect some 429s in that period, but it should be answering requests again
