### ISSUE TITLE
Issue with permissions, container won't start with anything other than PUID/PGID 1000

### ISSUE THREAD

**Issue by oliroe** [Readarr/Readarr#393]
I'm using Docker on a Synology NAS with the same PUID/PGID settings i use for many other containers but I get an error message that the config folder isn't writable.

Image with my usual PUID/PGID settings
![image](https://user-images.githubusercontent.com/4500141/90886204-e0e05d80-e3a9-11ea-9cee-01c23f348c0a.png)

The container will start using PUID/PGID 1000 but the directories are not writable when I'm trying to configure within Readarr

![image](https://user-images.githubusercontent.com/4500141/90886456-53513d80-e3aa-11ea-887b-c92acf14a055.png)

**Comment by ta264** [comment]
I dont think this is a readarr issue. Either your setup is wrong or something is messed up with hotio's container (but I think that's unlikely). Check the actual permissions on disk.

**Comment by oliroe** [comment]
Sorry for wasting your time @ta264 
I originally created the container with PUID/PGID 1000 and subsequently changed it to my 1024/101. As expected the files were then only writable by 1000/1000.
