### ISSUE TITLE
[Feature Request] Import lists can flip monitored status for existing authors

### ISSUE THREAD

**Issue by rg9400** [Readarr/Readarr#397]
**Is your feature request related to a problem? Please describe.**
My library consists of a wide range of authors, but I often leave them unmonitored with only select wanted books as monitored. This is because authors often can write quite a bit, and Goodreads data can sometimes pull duplicates, part books, sets, etc. which may be garbage. For this reason, using LL, I would just add them to my wanted list and import that list into LL. This flow does not work with Readarr since Readarr cannot flip the status of a single book, so if I already have the author, it will just ignore that book and keep it unmonitored. 

**Describe the solution you'd like**
If Specific Book is selected as the monitor type for a list, and if an existing author is found, then the list flips just that book from unmonitored to monitored (or ignores if already monitored). If a new author is found, it does this exact thing. If all books are selected, then it can flip all the books for the existing author. Basically, allow the import list to interact with existing authors.

**Describe alternatives you've considered**
The alternative is to find the books you want on Goodreads, then manually add them in Readarr. You can't just "add new" and do the automated search either since it will show up as an existing book, so you'd have to navigate to that book and flip the monitored status, then search

[AB#923](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/923)

**Comment by ta264** [comment]
Done
