### ISSUE TITLE
Tornab API v2 Error: [POST] /api/v1/indexer/test: 400.BadRequest for TPB

### ISSUE THREAD

**Issue by iot-resister** [Readarr/Readarr#398]
**Describe the bug**

**To Reproduce**
1. Go to 
Indexers -> Torznab

2. Click on  url
- paste url (that works in lidarr, radarr, sonarr, etc)
`http://192.168.0.14:9117/api/v2.0/indexers/thepiratebay/results/torznab/`
- paste  api key
- click `Test`

```
Query successful, but no results were returned from your indexer. This may be an issue with the indexer or your indexer category settings.
```
In the Logs
```
 /api/v1/indexer/test: 400.BadRequest
```

**Logs**
Link to debug logs.
https://pastebin.com/raw/dqGHS6e7

**System info (please complete the following information):**
 - Readarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]: debian buster/docker
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Comment by ta264** [comment]
This is expected behaviour if there are no book results
