### ISSUE TITLE
Delete Multiple Books from Author Page

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#400]
**Is your feature request related to a problem? Please describe.**
It takes a long time to keep clicking through to the book hit delete - go back to the author page - repeat, especially for authors with a lot of books and "crappy" colouring books/ graphic novels / foreign versions etc

**Describe the solution you'd like**
Tickbox beside each book and a delete button at the bottom to delete all ticked books. Delete button only clickable when 1 or more books are selected.

**Describe alternatives you've considered**
Alternatively - a delete button beside each book on the Author page so that you don't have to click through to the book.

[AB#928](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/928)

**Comment by ta264** [comment]
Done
