### ISSUE TITLE
Only Show Individual "Novels" in Author list

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#402]
**Is your feature request related to a problem? Please describe.**
There are a lot of random types of books: colouring books, graphic novels, short stories, collections, foreign language versions etc. Which makes it very messy for some authors - the solution is to delete all the extra books, but perhaps this can be done in a more automated/optional way.

**Describe the solution you'd like**
An option in the "meta-data profiles" to only include "ONLY single full novels" by the author. Looking at the GoodReads API data for "series" by author ID which is being used in the Author Series Tab/link in Readarr (which should be much more prominent as it is a great feature and one which I think most people are really looking for), perhaps limiting the book which appear on the main Author page to just those that are in the series - with some filtering for "graphic novel", "collection", "short story" to exclude those and any titles with multiple slashes in. 
API series "descriptions" with words likes "spanish", "german" can be used for language filtering.

Similar to the way lidarr finds "Just albums" or "Include EPs" or "Include Live", this could be applied to Readarr "Include Short Stories" "include Collections" "include multi book editions". It wont be perfect as the Goodreads data isn't consistent, but personally I just would like the main novels by each author, not all the other fluff.

**Describe alternatives you've considered**
Clicking delete on all the books i don't want - see previous Feature Request re Deleting for a faster way to do this.

[AB#932](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/932)

**Comment by ta264** [comment]
If only it were that easy :)

You might need a tweaked metadata profile for the author in question with a higher popularity criteria.  I'm open to adding a list of excluded words to a metadata profile, that's not a bad idea.

Are there any other concrete changes you'd suggest?  We already filter books by language.  I haven't seen many series descriptions with a language in - do you have an example?

**Comment by sebclark** [comment]
Yeah - I know it is a massive ask - as I was looking through the GoodReads API and fields I was thinking how well Readarr already does with regard to the processing the hundreds of titles per author into mainly just novels - just trying to throw out a few extra ideas/tweaks that might help a bit more.

This is an example of a series with language: https://pastebin.com/SLTHxBRe

On Setting-> Profiles -> Release Profiles what do the "Must Contain" and "Must Not Contain" match against at the moment?

**Comment by claym** [comment]
👍

**Comment by bakerboy448** [comment]
> open to adding a list of excluded words to a metadata profile

this exists and has been previously completed
