### ISSUE TITLE
Manual Import - Not Finding Author (when at the end of the filename)

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#407]
**Describe the bug**
If the book file name starts **fname lname** or **lname, fname** then the auto-matching works well when manually importing books from a folder. If however the name is at the end or after a hyphen or "by" matching doesn't seem to work very well. e.g. The Big Book by Author Name doesn't match for many authors, neither does The Big Book - Author Name

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Wanted'
2. Click on 'Manual Import'
3. Find the folder of Books you want to import
4. Click "Interactive Import"

**Expected behaviour**
Authors and book titles should match if they appear at the front of the file name or the end.

**Comment by ta264** [comment]
author and title are generally pulled from the internal book metadata, not the filename
