### ISSUE TITLE
Individual Interactive Searches Not Showing Results - Logs Show Results

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#409]
**Describe the bug**
When searching for a book using the "interactive search" on the "series" page of the author. Sometimes the search results come back to say none found. Reading the logs and checking the sites there are actually multiple matches:

https://pastebin.com/2DW94K6u
https://pastebin.com/RpBMkJr0

**To Reproduce**
1. Go to 'Authors page'
2. Click on 'Series'
3. Scroll down to 'Any book and press the little person "interactive search" icon'
![image](https://user-images.githubusercontent.com/5827360/91627696-0e806480-e9b1-11ea-98a2-a65522173f61.png)

**Expected behavior**
Pop up window should say xx results and list them as it does on some other occasions

[AB#936](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/936)

**Comment by bakerboy448** [comment]
This is more than likely due to the releases not having a download link.

And is this still an issue on the new builds?

**Comment by bakerboy448** [comment]
Closing due to lack of reports and issue activity.
