### ISSUE TITLE
Couldn't Find Similar Book for [Error} ... With selected correctly matching book

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#410]
**Describe the bug**
Trying to manually assign a book in the queue to the correct book from the author results in a Couldnt Find Similar Book Error

**To Reproduce**
1. Go to 'Queue'
2. Click on 'A book that needs manual intervention'
![image](https://user-images.githubusercontent.com/5827360/91628020-a97a3e00-e9b3-11ea-92f0-d5420e1270a9.png)
3. See reason for manual intervention - low % match
![image](https://user-images.githubusercontent.com/5827360/91628042-f2ca8d80-e9b3-11ea-8c7d-8237ca62af5a.png)

4. Change book to the correct book
![image](https://user-images.githubusercontent.com/5827360/91628058-083fb780-e9b4-11ea-894f-407793632d09.png)

Error message in logs: https://pastebin.com/SzHLJGx7

**Expected behavior**
Book should map nicely to existing record.

[AB#938](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/938)

**Comment by ta264** [comment]
@sebclark it would be more useful if you joined the discord channel to discuss these and make sure we understand the issue and have all the info required to replicate in the bug report

**Comment by ta264** [comment]
I think this is probably fixed now, let me know if not
