### ISSUE TITLE
Get "Book ID does not exist" when attempting to rename files

### ISSUE THREAD

**Issue by misleadingrhino** [Readarr/Readarr#411]
**Describe the bug**
When attempting to do a rename, get the error 

`Failed to rename file /books/Zora Neale Hurston/Their Eyes Were Watching God (437)/Their Eyes Were Watching God - Zora Neale Hurston; Edwidge Danticat.mobi: Book with ID 11927 does not exist`

despite the fact that the file is in the database on the author page 

![image](https://user-images.githubusercontent.com/14330129/91639819-27a40800-e9e7-11ea-922d-96c080a89d30.png)

**To Reproduce**
Only happens to some works by some authors. Seems to be random and will clear itself up randomly. 

**Expected behavior**
File is renamed as indicated on the rename popup. 

**Logs**
```
20-8-29 10:58:51.4|Debug|MediaInfoFormatter|Unknown audio format: ''.
20-8-29 10:58:51.4|Debug|Api|[GET] /api/v1/rename?authorId=424: 200.OK (13 ms)
20-8-29 10:58:51.4|Debug|Api|[GET] /api/v1/config/naming: 200.OK (1 ms)
20-8-29 10:58:52.8|Debug|Api|[POST] /api/v1/command: 201.Created (6 ms)
20-8-29 10:58:52.8|Info|RenameBookFileService|Renaming 1 files for Zora Neale Hurston
20-8-29 10:58:52.8|Debug|RenameBookFileService|Renaming book file: [4429] /books/Zora Neale Hurston/Their Eyes Were Watching God (437)/Their Eyes Were Watching God - Zora Neale Hurston; Edwidge Danticat.mobi
20-8-29 10:58:52.8|Error|RenameBookFileService|Failed to rename file /books/Zora Neale Hurston/Their Eyes Were Watching God (437)/Their Eyes Were Watching God - Zora Neale Hurston; Edwidge Danticat.mobi

[v0.1.0.239] NzbDrone.Core.Datastore.ModelNotFoundException: Book with ID 11927 does not exist
   at NzbDrone.Core.Datastore.BasicRepository`1.Get(Int32 id) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 96
   at NzbDrone.Core.MediaFiles.BookFileMovingService.MoveBookFile(BookFile bookFile, Author author) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\BookFileMovingService.cs:line 71
   at NzbDrone.Core.MediaFiles.RenameBookFileService.RenameFiles(List`1 bookFiles, Author author) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\RenameBookFileService.cs:line 121


20-8-29 10:58:52.8|Info|RenameBookFileService|Selected book files renamed for Zora Neale Hurston
20-8-29 10:58:52.9|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
20-8-29 10:58:52.9|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
20-8-29 10:58:53.0|Debug|Api|[GET] /api/v1/series?authorId=424: 200.OK (9 ms)
20-8-29 10:58:53.0|Debug|Api|[GET] /api/v1/queue/details?authorId=424: 200.OK (4 ms)
20-8-29 10:58:53.0|Debug|MediaInfoFormatter|Unknown audio format: ''.
20-8-29 10:58:53.0|Debug|Api|[GET] /api/v1/bookFile?authorId=424: 200.OK (17 ms)
20-8-29 10:58:53.0|Debug|Api|[GET] /api/v1/book?authorId=424: 200.OK (34 ms)
20-8-29 10:58:58.1|Debug|DiskScanService|Scanning '/books/Zora Neale Hurston' for ebook files
20-8-29 10:58:58.2|Debug|DiskScanService|1 book files were found in /books/Zora Neale Hurston
20-8-29 10:58:58.2|Debug|Parser|Parsing string 'Zora Neale Hurston'

```
**System info (please complete the following information):**
Version 0.1.0.239
Package Version unstable-befb4e4-17 by hotio 
.NET Core Yes
Docker Yes
DB Migration 2

I'm misleadingrhino on the Discord if you need more information. 

[AB#940](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/940)

**Comment by ta264** [comment]
Do not try to rename books in calibre (looks like they might be) it'll totally screw up your calibre database...

Is it a calibre database? I need to disable the option in that case.

**Comment by misleadingrhino** [comment]
No, not using calibre, just Readarr. (per Discord discussion)

**Comment by misleadingrhino** [comment]
This seems to clear itself up over time. It's possible there's a scheduled task that cleans up the library and fixes this issue.

**Comment by bakerboy448** [comment]
Any recent occurrences of this on current readarr versions?

**Comment by misleadingrhino** [comment]
Have not seen this in years. Appears to have been resolved. Thanks!
