### ISSUE TITLE
Object reference not set to an instance of an object. During "Manual Import" of books

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#415]
**Describe the bug**
"Object reference not set to an instance of an object." error when trying to Manually import a folder of books (gets to book 110 out of 450).

Looks like the issue here:

/mnt/local/downloads/torrents/qbittorrent/completed/C.D. Reiss - Breathe/Breathe - CD Reiss.azw3
20-9-1 16:55:46.4|Debug|IdentificationService|Trying Release [26206569][Breathe]
20-9-1 16:55:46.4|Trace|DistanceCalculator|artist: 'CD Reiss' vs 'C.D. Reiss'; 0
20-9-1 16:55:46.4|Trace|ReadarrErrorPipeline|Handling Exception
20-9-1 16:55:46.4|Warn|ReadarrErrorPipeline|System.NullReferenceException: Object reference not set to an instance of an object.

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Manual Import'
3. Scroll down to 'Folder of Books'

**Expected behavior**
Should add all books :)

**Screenshots**
See video: https://fluvid.com/videos/detail/zj5DaiGzD3ug7w8zn (password: readarr)

**Logs**
https://pastebin.com/mbTCwYLa

**Comment by ta264** [comment]
I believe this is fixed
