### ISSUE TITLE
Manual Import - Error when a book already exists (with same file size) using Overwrite (Existing Files will be Deleted)

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#418]
**Update** This actually seems to corrupt the Calibre .db file requiring a rescan of the library in Calibre. 
![image](https://user-images.githubusercontent.com/5827360/91878756-add67d80-ec77-11ea-8c85-3e9a0d62139c.png)

**Describe the bug**
Error/Faiure, when trying to import a book via Readarr that already exists in the Calibre library, with the same file size the import fails (using Files will be deleted option). 

**To Reproduce**
Steps to reproduce the behaviour:

Go to 'Wanted'
Click on 'Manual Import'
Scroll down to 'Interactive'
Change the drop down to "Existing files will be deleted"
Pick a book that has "file with same size already exists" then try to import. 

Expected behavior
Delete book and upload file book.

**NOTE** It has deleted the file from the folder, but not uploaded a new one - so now there is an error when trying to do anything in Readarr due to the book existing in Calibre but not in the file system: https://pastebin.com/RZinbzSd
Trying to add the book through "Manual Import" no longer shows the alert for "file exists with the same size", but also wont import the book still: https://fluvid.com/videos/detail/QK5p2Cm3gLURM6K5e (https://pastebin.com/VKUq3VT9)

Screenshots
https://fluvid.com/videos/detail/daLDVT-BOkfA92Zr9 (password: readarr)

Logs
https://pastebin.com/5mziRAaQ

**Comment by ta264** [comment]
I think this has been fixed, let me know if not
