### ISSUE TITLE
Wanted List Broken After Reverse Author Sort

### ISSUE THREAD

**Issue by sebclark** [Readarr/Readarr#420]
**Describe the bug**
After pressing the Author Sort for a-z and then for z-a the page doesn't load any results anymore: Error fetching missing items

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Author Column Header Twice'
3. Scroll down to 'no results show when reloading the page'

**Expected behavior**
Wanted list sorted by author

**Screenshots**

![image](https://user-images.githubusercontent.com/5827360/91922563-2b28df00-ecc6-11ea-9ad8-2dd4ce7ffa8b.png)

**Logs**
https://pastebin.com/7nfcWahX

**Comment by ta264** [comment]
I believe this was fixed in 6e398b3a57fcfa1c11eb7ce9dee21324d34cb4b2
