### ISSUE TITLE
Manual Import from Unmapped Files leads to a green alien image when picking author or book

### ISSUE THREAD

**Issue by misleadingrhino** [Readarr/Readarr#423]
**Describe the bug**
When attempting to manually import files from the Unmapped Files subsection under Library, attempting to select the author or book will pop up with a green alien and an error. 

**To Reproduce**
1. Click on Library. 
2. Click on UnmappedFiles
3. Pick any unmapped file. 
4. Select any field that isn't auto-populated. 
5. Green alien monster and below error. 

**Expected behavior**
Pick the author or book and then click import to import. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14330129/92020069-98b82800-ed25-11ea-8617-9a657ac0a259.png)
![image](https://user-images.githubusercontent.com/14330129/92020174-bf765e80-ed25-11ea-8606-c9b3950306ad.png)
![image](https://user-images.githubusercontent.com/14330129/92020211-cef5a780-ed25-11ea-906a-095697b3d095.png)

Click on the author section in the second book line.

![image](https://user-images.githubusercontent.com/14330129/92020265-e03eb400-ed25-11ea-9b89-ecb99376686c.png)

**Logs**
https://pastebin.com/CYLmzL5d

**System info (please complete the following information):**
Version 0.1.0.243
Package Version unstable-f1499ec-20 by hotio 
.NET Core Yes
Docker Yes
DB Migration 2

[AB#949](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/949)

**Comment by misleadingrhino** [comment]
After seeing this a few more times, it seems to happen when the new file has the same filesize as the existing.

**Comment by ta264** [comment]
I think this will be fixed now
