### ISSUE TITLE
Infinite loop while searching under an author

### ISSUE THREAD

**Issue by tingtom** [Readarr/Readarr#5]
**Describe the bug**
A lot of the same requests to a release endpoint are executed after clicking on the search tab under an author (or lidarr artist), a lot of console errors are printed and eventually the tab will crash or the browser itself. If you stop the script then a loading icon appears and the tab looks selected.

**To Reproduce**
1. Add a book or author
2. Click library
3. Click on a author
4. Click on the search tab header

**Expected behavior**
Search tab should be selected and you should be able to begin a search for books I guess

**Screenshots**
![image](https://user-images.githubusercontent.com/473174/78077417-4488d080-73a0-11ea-9c18-4bb563356858.png)

**Logs**
There's nothing in the logs about it for some reason

**System info (please complete the following information):**
 - Readarr Version: [e.g. 0.3.0.430]
 - Operating System [e.g. iOS]
 - .net Framework (Windows) or mono (macOS/Linux) Version: [e.g. 4.5 or 5.12]

**Additional context**

**Comment by Qstick** [comment]
Fixed dd8db6437202716d91587029155e973c7b89ed57
