### ISSUE TITLE
Missing Books on foreign languages

### ISSUE THREAD

**Issue by kesm** [Readarr/Readarr#547]
**Describe the bug**
Books are missing when profile is set for foreign languages

**To Reproduce**
1. Go to Metadata Profile
2. Set a metadata profile with "fre,fr, fr-fr,french" with all skip disabled
3. Add any author (J.K Rowling for instance)
4. Only some books are retrieved : [Harry Potter a l'ecole des sorciers](https://www.goodreads.com/book/show/31349309-harry-potter-a-l-ecole-des-sorciers?from_search=true&from_srp=true&qid=IDLVYLBRwk&rank=1) is available but [Harry Potter et la Chambre des Secrets](https://www.goodreads.com/book/show/31349309-harry-potter-a-l-ecole-des-sorciers?from_search=true&from_srp=true&qid=IDLVYLBRwk&rank=1) is not available

**Expected behavior**
All books with foreign language should be available

**Screenshots**
![image](https://user-images.githubusercontent.com/6907912/95957899-a1aa1800-0e00-11eb-8fe5-add98a0ed295.png)
![image](https://user-images.githubusercontent.com/6907912/95957922-aa025300-0e00-11eb-9ce2-acffbafaaabd.png)

**Logs**
Link to debug logs.

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.291nightly-ad3adf9-63 by hotio
 - Operating System Unraid

[AB#492](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/492)

**Comment by ta264** [comment]
Nothing I can do about this I'm afraid, it's a constraint of the goodreads API.  You can manually search and add the french editions if you want.

**Comment by kesm** [comment]
I tried but it looks like it still search for original name : 
![image](https://user-images.githubusercontent.com/6907912/95966809-dd96aa80-0e0b-11eb-8ddc-9a8f1d42a18f.png)

20-10-14 10:53:55.0|Info|NzbSearchService|Searching 4 indexers for [J.K. Rowling - Harry Potter and the Chamber of Secrets (1998)]
20-10-14 10:54:09.4|Info|DownloadDecisionMaker|No results found

**Comment by ta264** [comment]
I think you misunderstood me.  Join the discord channel and I can try to explain better.  https://discord.gg/WWd5ZGg

**Comment by kesm** [comment]
Clarified on discord, that's another issue

**Comment by GregTroar** [comment]
Same issue here, whenever we want only French books no books appear as they should even for French authors.
For example Joel Dicker i should find at least 6 books from him but only find one when i use "French" language in metadata profiles.
That is a pitty i was excited to use a *arr for books

**Comment by almottier** [comment]
+1
It looks this project is only for english readers... Goodreads is very poor in terms of foreign books. I have much more results with LazyLibrarian with Google API. Feedbooks API has tons of results for french books too.
I hope this project could implement other APIs. 🤞

**Comment by zeppelinlg** [comment]
Hello

Another api for metadata will be good. The ISBN Key will be usefull for Sync the data.

Readarr seem to be a good app but in french there is many missing Books.

**Comment by ta264** [comment]
This is as good as it can be now.  No plans to implement other metadata providers.
