### ISSUE TITLE
Original book name is used when searching for a foreign book edition

### ISSUE THREAD

**Issue by kesm** [Readarr/Readarr#548]
**Describe the bug**
Original book name is used when searching for a foreign book edition

**To Reproduce**
1. Search for a foreign edition of a book (in my case : Harry Potter et la Chambre des Secrets)
2. Foreign edition is added to author page
3. Do a manual search on foreign edition
4. Foreign title is not used for the manual search and original title is used

**Expected behavior**
Foreign title should be used

**Screenshots**
![image](https://user-images.githubusercontent.com/6907912/95969031-85ad7300-0e0e-11eb-93b4-4147e052bff6.png)

**Logs**
20-10-14 10:53:55.0|Info|NzbSearchService|Searching 4 indexers for [J.K. Rowling - Harry Potter and the Chamber of Secrets (1998)]
20-10-14 10:54:09.4|Info|DownloadDecisionMaker|No results found

**System info (please complete the following information):**
 - Readarr Version: 0.1.0.291nightly-ad3adf9-63 by hotio
 - Operating System: Unraid

[AB#493](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/493)

**Comment by ta264** [comment]
It's used the edition title (not the work title) for a little while now.
