### ISSUE TITLE
Unable to add torznab feed for audiobookbay

### ISSUE THREAD

**Issue by crogers2287** [Readarr/Readarr#567]
Seems like torznab is only feeding category 3030, but readarr is looking for 7020 and 8010. It will not let me add this because of the category mismatch (I'm assuming).

See attached logs and images:

https://pastebin.com/fmPB0Xe8

https://i.imgur.com/JHhxAhU.png

**Comment by spijkey87** [comment]
this is probably because you come from the netherlands. What you can do is setup a openvpn docker with your vpn provider and tunnel your jackett true the vpn docker (set up your vpn not for a dutch server)

**Comment by crogers2287** [comment]
Nope, I'm in the USA 

    On Friday, October 30, 2020, 08:57:46 AM EDT, spijkey87 <notifications@github.com> wrote:  
 
 


this is probably because you come from the netherlands. What you can do is setup a openvpn docker with your vpn provider and tunnel your jackett true the vpn docker (set up your vpn not for a dutch server)

**Comment by mixednutts** [comment]
@crogers2287 I'm experiencing a similar issue and found that some indexes will return 0 results unless a query term is passed in the request.

If you tried ` http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=book&q=jack&cat=7020,8010&extended=1&apikey=(removed)&offset=0&limit=100` in a browser by itself what happens?

Remember to put your jackett api key in where it says `(removed)`.  

Currently readarr won't allow you to save the indexer unless it validates - maybe this needs to be reviewed???

**Comment by crogers2287** [comment]
This is the error that gives me:

`<error code="201" description="audiobookbay does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported."/>`

**Comment by mixednutts** [comment]
@crogers2287 I configured with the 3030 category in readarr and everything validated ok.  I'm running version 0.1.0.303 of readarr.

https://imgur.com/a/pPDAa1y

**Comment by crogers2287** [comment]
Ah, it was not showing the advanced for me, didnt realize I needed to show it on the indexer page to get it to pop up. It will let me add it after changing the category, but still returns 0 results.

**Comment by mixednutts** [comment]
@crogers2287 what book are you looking for?  You can do a manual search straight from jackett and see if it works there?

**Comment by crogers2287** [comment]
It actually says it finds the release but is unable to process it. The releases do show up in jackett.

`20-11-4 01:44:37.2|Debug|Torznab|Downloading Feed http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=search&cat=3030&extended=1&apikey=(removed)&offset=0&limit=100&q=Sebastien%20de%20Castell%20Soulbinder
20-11-4 01:44:39.3|Debug|NzbSearchService|Total of 1 reports were found for [Sebastien de Castell - Soulbinder (2018)] from 1 indexers
20-11-4 01:44:39.3|Info|DownloadDecisionMaker|Processing 1 releases
20-11-4 01:44:39.3|Debug|DownloadDecisionMaker|Processing release 'Spellslinger (1-4) - Sebastien de Castell' from 'Torznab'
20-11-4 01:44:39.3|Debug|Parser|Parsing string 'Spellslinger (1-4) - Sebastien de Castell'
20-11-4 01:44:39.3|Debug|Parser|Unable to parse Spellslinger (1-4) - Sebastien de Castell
20-11-4 01:44:39.3|Debug|Parser|Parsing string 'Spellslinger (1-4) - Sebastien de Castell' using search criteria author: 'Sebastien de Castell' books: 'Soulbinder'
20-11-4 01:44:39.3|Debug|Api|[GET] /api/v1/release?bookId=100: 200.OK (22890 ms)
20-11-4 01:44:52.2|Debug|Api|[GET] /api/v1/queue/details?authorId=3: 200.OK (9 ms)
20-11-4 01:44:52.2|Debug|Api|[GET] /api/v1/series?authorId=3: 200.OK (13 ms)
20-11-4 01:44:52.2|Debug|Api|[GET] /api/v1/bookFile?authorId=3: 200.OK (13 ms)
20-11-4 01:44:52.2|Debug|Api|[GET] /api/v1/book?authorId=3: 200.OK (21 ms)
20-11-4 01:44:56.1|Debug|IndexerFactory|Temporarily ignoring indexer NZBgeek till 11/4/2020 1:46:09 AM due to recent failures.
20-11-4 01:44:56.1|Info|NzbSearchService|Searching 1 indexers for [Sebastien de Castell - Charmcaster (2018)]
20-11-4 01:44:56.1|Debug|Torznab|Downloading Feed http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=search&cat=3030&extended=1&apikey=(removed)&offset=0&limit=100&q=Charmcaster%20Sebastien%20de%20Castell
20-11-4 01:45:01.0|Debug|Torznab|Downloading Feed http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=search&cat=3030&extended=1&apikey=(removed)&offset=0&limit=100&q=Sebastien%20de%20Castell%20Charmcaster
20-11-4 01:45:01.6|Debug|Api|[GET] /api/v1/log?page=1&pageSize=50&sortDirection=descending&sortKey=time: 200.OK (4 ms)
20-11-4 01:45:04.1|Debug|NzbSearchService|Total of 2 reports were found for [Sebastien de Castell - Charmcaster (2018)] from 1 indexers
20-11-4 01:45:04.1|Info|DownloadDecisionMaker|Processing 2 releases
20-11-4 01:45:04.1|Debug|DownloadDecisionMaker|Processing release 'Spellslinger (1-4) - Sebastien de Castell' from 'Torznab'
20-11-4 01:45:04.1|Debug|Parser|Parsing string 'Spellslinger (1-4) - Sebastien de Castell'
20-11-4 01:45:04.1|Debug|Parser|Unable to parse Spellslinger (1-4) - Sebastien de Castell
20-11-4 01:45:04.1|Debug|Parser|Parsing string 'Spellslinger (1-4) - Sebastien de Castell' using search criteria author: 'Sebastien de Castell' books: 'Charmcaster'
20-11-4 01:45:04.1|Debug|DownloadDecisionMaker|Processing release 'Charmcaster: Spellslinger, Book 3  - Sebastien de Castell' from 'Torznab'
20-11-4 01:45:04.1|Debug|Parser|Parsing string 'Charmcaster: Spellslinger, Book 3  - Sebastien de Castell'
20-11-4 01:45:04.1|Debug|Parser|Unable to parse Charmcaster: Spellslinger, Book 3  - Sebastien de Castell
20-11-4 01:45:04.1|Debug|Parser|Parsing string 'Charmcaster: Spellslinger, Book 3  - Sebastien de Castell' using search criteria author: 'Sebastien de Castell' books: 'Charmcaster'
20-11-4 01:45:04.1|Debug|Api|[GET] /api/v1/release?bookId=99: 200.OK (8075 ms)
20-11-4 01:45:25.7|Debug|Api|[GET] /api/v1/config/indexer: 200.OK (1 ms)
20-11-4 01:45:25.7|Debug|Api|[GET] /api/v1/indexer: 200.OK (13 ms)
20-11-4 01:45:29.8|Debug|Api|[PUT] /api/v1/indexer/1: 202.Accepted (75 ms)
20-11-4 01:45:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
20-11-4 01:45:29.9|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
20-11-4 01:45:31.6|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
20-11-4 01:45:31.6|Debug|Api|[GET] /api/v1/command: 200.OK (0 ms)
20-11-4 01:45:37.3|Info|NzbSearchService|Searching 1 indexers for [Sebastien de Castell - Spellslinger 5: Queenslayer (2019)]
20-11-4 01:45:37.3|Debug|Torznab|Downloading Feed http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=search&cat=3030&extended=1&apikey=(removed)&offset=0&limit=100&q=Spellslinger%205%20Queenslayer%20Sebastien%20de%20Castell
20-11-4 01:45:40.8|Debug|Torznab|Downloading Feed http://192.168.1.4:9117/api/v2.0/indexers/audiobookbay/results/torznab/api?t=search&cat=3030&extended=1&apikey=(removed)&offset=0&limit=100&q=Sebastien%20de%20Castell%20Spellslinger%205%20Queenslayer
20-11-4 01:45:43.9|Debug|NzbSearchService|Total of 1 reports were found for [Sebastien de Castell - Spellslinger 5: Queenslayer (2019)] from 1 indexers
20-11-4 01:45:43.9|Info|DownloadDecisionMaker|Processing 1 releases
20-11-4 01:45:43.9|Debug|DownloadDecisionMaker|Processing release 'Queenslayer (Spellslinger #5) - Sebastien de Castell' from 'Torznab'
20-11-4 01:45:43.9|Debug|Parser|Parsing string 'Queenslayer (Spellslinger #5) - Sebastien de Castell'
20-11-4 01:45:43.9|Debug|Parser|Unable to parse Queenslayer (Spellslinger #5) - Sebastien de Castell
20-11-4 01:45:43.9|Debug|Parser|Parsing string 'Queenslayer (Spellslinger #5) - Sebastien de Castell' using search criteria author: 'Sebastien de Castell' books: 'Spellslinger 5: Queenslayer'`

**Comment by crogers2287** [comment]
Here is the debug log if it helps: https://bit.ly/326ckpp

**Comment by mixednutts** [comment]
@crogers2287 sorry but that hits the limit of my understanding of the app (only dl it recently myself).  Maybe a parsing error but not sure.  Maybe try another title that isn't part of a series and see if that works?  There is an interactive search option too but I haven't played with that too much.  Good luck.

**Comment by xorbital** [comment]
@crogers2287 I think Readarr isn't fully ready for audiobooks yet.
You can take a look at the source code, in which category 3000 (audio, including 3030 audiobooks) is explicitly on the blocklist :(

**Comment by ta264** [comment]
Readarr has basic audiobook support now
