### ISSUE TITLE
Allow direct download of post-processed files

### ISSUE THREAD

**Issue by claym** [Readarr/Readarr#578]
**Describe the solution you'd like**
It would be really great if I could directly download a file that readarr has downloaded and post-processed. Perhaps from the History page, the EPUB / MOBI / etc element in the "Quality" column could be a link to the download. Additionally, the "File" tab for an author or book would be another good option.

**Describe alternatives you've considered**
Since Readarr has integration with Calibre + Calibre-Web, I can download the file through Calibre-Web, but it's pretty crazy to need 2 other pieces of software to download pretty small file :)

**Comment by austinwbest** [comment]
If readarr has already grabbed it, why do you need a download link? It is already on disk. If the root folder is setup with calibre then it would be imported there too.

Goes im not understanding

**Comment by claym** [comment]
Ah - I run Readarr on a box on the other side of the planet, and I like to send books to my Kindle via USB (obviously on my local machine). I suppose it's easier to pull up a "what's the been downloaded recently" list on Readarr than sshing into the box and digging around to find those books.

**Comment by austinwbest** [comment]
As mentioned on discord, just for the case someone had this same idea, it would be much wiser to use an automated solution to sync to your local or worse case something like sshfs
