### ISSUE TITLE
Config option for ImportDecisionMaker threshold

### ISSUE THREAD

**Issue by virtualadept** [Readarr/Readarr#588]
Currently for an item to be auto-imported, ImportDecisionMaker's analysis must hit at least an 80% match.

Readarr.debug.0.txt:20-11-3 11:02:26.5|Debug|ImportDecisionMaker|Book rejected for the following reasons: [Permanent] Album match is not close enough: 78.3% vs 80% [album]

Requesting an option to lower that threshold from 80% to user-defined depending on how sloppy we want ImportDecisionMaker to be when auto-importing.

[AB#544](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/544)

**Comment by j33p4meplz** [comment]
Seeing this as well.

**Comment by FlipABit** [comment]
Same here, especially when I to an interactive search/download, specifically picking a release, and then having the importer tell me that it's not a close enough match.

**Comment by Mushin** [comment]
I'm often seeing this with more downloads than are actually successfully imported. Would be nice to have the option to lower the threshold, since most seem to be correct matches anyway.

**Comment by bakerboy448** [comment]
No particular plans for this.

the common issue for books not importing is due to poor tags - readarr looks at the metadata tags rather than the file name.

if there are some close matches or garbage to filter out -  trace logs and info => discord so devs can take a look

**Comment by ta264** [comment]
No plans for this
