### ISSUE TITLE
[Feature Request] Stable database

### ISSUE THREAD

**Issue by flying-sausages** [Readarr/Readarr#666]
**Is your feature request related to a problem? Please describe.**
I'd like the stability of a database that does not need to be reset 

**Describe the solution you'd like**
the certainty that readarr won't borkybork on updates

**Describe alternatives you've considered**
I'm struggling to find something funny, I'm just making this ticket so I can be alerted when it's closed so i can close some outstanding PRs.

**Additional context**
https://github.com/swizzin/swizzin/pull/542 lesssssgooooooooooo

cheers and credits to @bakerboy448 

Just close this when the DB is declared stable enough and you're happy with the installer for readarr going live in swizzin production environment :)

[AB#597](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/597)

**Comment by bakerboy448** [comment]
Safe for public breaking, just to clarify that would be a stable-alpha (ironic) version that is.

**Comment by ta264** [comment]
Calling it stable
