### ISSUE TITLE
Can't remove root folders

### ISSUE THREAD

**Issue by johnistheman** [Readarr/Readarr#681]
There is nowhere to remove Root folders. The way it's done in Radarr/Sonarr, removing it when mass editing/manual importing, doesn't work in Readarr (the "x" doesn't exist to remove folders)

**Comment by bakerboy448** [comment]
I’m guessing there may be an outstanding Sonarr pull for this.

anyway, fill out the template you either blew away or your 3rd party app ignored.
https://github.com/Readarr/Readarr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by bakerboy448** [comment]
For now, check under settings -> media management -> root folders

**Comment by johnistheman** [comment]
> For now, check under settings -> media management -> root folders

🤦🏼‍♂️ I'm sorry about this... For some reason I kept having some visual aversion to those top cards used for the root folders. I was looking for a UI more like the Remote Path Mappings and just wasn't seeing them. This solves my issue, thank you!
