### ISSUE TITLE
Full works list not being pulled from GoodReads

### ISSUE THREAD

**Issue by daFreeMan** [Readarr/Readarr#711]
**Describe the bug**
The full list of works is not being pulled from GoodReads

**To Reproduce**
1. Go to GoodReads, look up A. Bertram Chandler - you'll see he has 259 distinct works
2. Add A. Bertram Chandler to Readarr - when it's finished updating you'll see he has 59 works
4. 59 != 259

**Expected behavior**
Readarr should pick up all the works listed in GoodReads so that I can import all the works I actually have for this author and others.

**Screenshots**
Here is the author info from GoodReads:
![image](https://user-images.githubusercontent.com/11889733/103647388-3bc5bc00-4f29-11eb-95e6-e9fe4511c8aa.png)

Here's what Readarr shows for him:
![image](https://user-images.githubusercontent.com/11889733/103647919-0d94ac00-4f2a-11eb-9c60-afd5dea10823.png)

**Platform Information (please complete the following information):**
- Version    0.1.0.365
- Package Version    nightly-b54d863 by hotio 
- .NET Core     Yes
- Docker     Yes
- DB Migration    4
- AppData directory    /config/app
- Startup directory    /app/bin
- Mode    Console
 - Browser and Version Firefox 84.0.1

**Trace Logs**
[Readarr.trace.25.txt](https://github.com/Readarr/Readarr/files/5770234/Readarr.trace.25.txt)
[Readarr.trace.24.txt](https://github.com/Readarr/Readarr/files/5770235/Readarr.trace.24.txt)
(Note: I only included the 2 files where it was specifically searching for Chandler. I can include the other 23 files if necessary.)

**Comment by ta264** [comment]
As commented in discord, this is by design. Edit your metadata profile if you want everything.
