### ISSUE TITLE
Windows Install?

### ISSUE THREAD

**Issue by tjsnow** [Readarr/Readarr#783]
I see there is not yet an installer package put together for windows. I am very interested in this as I am already a big user of Sonarr and Radarr with NZBget.

I am currently using LazyLibrarian which has some functionality I want, but it is difficult to use and very buggy.

I am in software QA by trade and would be happy to throw my hat in for a windows beta test when available.

**Comment by bakerboy448** [comment]
Readarr is pre-alpha

if you want to help test; hop on discord

[Discord](https://discord.gg/rkEXY2Rbgn)

**Comment by tjsnow** [comment]
Sure I figured as much. Thanks!
