### ISSUE TITLE
Container: Folder is not writable by user hotio

### ISSUE THREAD

**Issue by teuteuguy** [Readarr/Readarr#827]
Trying the latest (nightly) container build, when adding a writable volume to the container, and trying to add it as a root folder fails with: "Folder is not writable by user hotio".

**To Reproduce**
I've simply deployed the hotio/readarr:nightly container.
My settings are: 
PUID | 1000
PGID | 1000
And I've tried adding a volume on /mnt/media.

I also run sonarr using the same method and same PUID and PGID of 1000, using the same /mnt/media volume and it works no issues.

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/readarr/) or [Discord](https://discord.gg/rkEXY2Rbgn)  Bring your docker compose https://trash-guides.info/Misc/how-to-provide-a-docker-compose/

See the docker guides
https://wiki.servarr.com/Docker_Guide
and
https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/
