### ISSUE TITLE
[413:RequestEntityTooLarge] when importing books

### ISSUE THREAD

**Issue by dwilliamhouston** [Readarr/Readarr#840]
When trying to do a manual import of books of existing authors I receive the following error:

Unable to connect to calibre library: HTTP request failed: [413:RequestEntityTooLarge] [GET] at [http://172.18.0.4:8081/ajax/books/Books?ids=22011%2C22012%2C22006%2C22005%2C22004%2C22003%2C22002%2C22001%2C22000%2C21999%2C21998%2C21997%2C21996%2C21995%2C21993%2C21994%2C21991%2C21992%2C21990%2C21989%2C21988%2C21987%2C21986%2C21985%2C21984%2C21983%2C21982%2C21981%2C21980%2C21979%2C21978%2C21977%2C21976%2C21975%2C21974%2C21973%2C21972%2C21971%2C21964%2C21965%2C21966%2C21967%2C21968%2C21969%2C21970%2C21960%2C21961%2C21962%2C21963%2C21954%2C21955%2C21956%2C21958%2C21959%2C21949%2C21950%2C21951%2C21952%2C21953%2C21944%2C21945%2C21946%2C21947%2C21948%2C21939%2C21940%2C21941%2C21942%2C21924%2C21925%2C21926%2C21927%2C21928%2C21929%2C21930%2C21931%2C21932%2C21933%2C21934%2C21935%2C21936%2C21937%2C21909%2C21910%2C21911%2C21912%2C21913%2C21914%2C21915%2C21916%2C21917%2C21918%2C21919%2C21920%2C21921%2C21922%2C21923%2C21893%2C21894%2C21895%2C21896%2C21897%2C21899%2C21900%2C21901%2C21903%2C21904%2C21906%2C21907%2C21908%2C21892%2C21880%2C21881%2C21882%2C21883%2C21884%2C21885%2C21886%2C21887%2C21888%2C21889%2C21890%2C21891%2C21871%2C21872%2C21873%2C21874%2C21875%2C21876%2C21877%2C21878%2C21879%2C21859%2C21860%2C21861%2C21862%2C21863%2C21864%2C21865%2C21866%2C21867%2C21868%2C21869%2C21870%2C21850%2C21851%2C21852%2C21853%2C21854%2C21856%2C21857%2C21858%2C21849%2C21836%2C21837%2C21838%2C21839%2C21840%2C21841%2C21842%2C21843%2C21844%2C21845%2C21846%2C21847%2C21848%2C21823%2C21824%2C21825%2C21826%2C21827%2C21828%2C21829%2C21830%2C21831%2C21832%2C21833%2C21834%2C21835%2C21818%2C21819%2C21820%2C21821%2C21822%2C21812%2C21813%2C21814%2C21815%2C21816%2C21817%2C21800%2C21801%2C21802%2C21803%2C21804%2C21805%2C21806%2C21807%2C21808%2C21809%2C21810%2C21811%2C21796%2C21797%2C21798%2C21799%2C21793%2C21794%2C21795%2C21782%2C21783%2C21784%2C21785%2C21786%2C21787%2C21788%2C21789%2C21790%2C21791%2C21792%2C21769%2C21770%2C21771%2C21772%2C21773%2C21774%2C21775%2C21776%2C21777%2C21778%2C21779%2C21780%2C21781%2C21767%2C21768%2C21762%2C21763%2C21766%2C21745%2C21747%2C21748%2C21749%2C21750%2C21751%2C21752%2C21754%2C21755%2C21756%2C21757%2C21741%2C21742%2C21743%2C21744%2C21732%2C21733%2C21734%2C21735%2C21736%2C21737%2C21738%2C21739%2C21740%2C21726%2C21727%2C21728%2C21729%2C21730%2C21731%2C21723%2C21724%2C21687%2C21688%2C21689%2C21690%2C21691%2C21692%2C21693%2C21694%2C21695%2C21696%2C21697%2C21698%2C21699%2C21700%2C21701%2C21702%2C21703%2C21704%2C21705%2C21706%2C21707%2C21708%2C21709%2C21710%2C21711%2C21712%2C21713%2C21714%2C21715%2C21716%2C21717%2C21718%2C21719%2C21720%2C21721%2C21722%2C21681%2C21682%2C21683%2C21684%2C21685%2C21686%2C21666%2C21667%2C21668%2C21669%2C21670%2C21671%2C21672%2C21673%2C21674%2C21675%2C21676%2C21677%2C21678%2C21679%2C21680%2C21655%2C21656%2C21657%2C21658%2C21659%2C21660%2C21661%2C21662%2C21663%2C21664%2C21641%2C21642%2C21643%2C21644%2C21645%2C21646%2C21647%2C21648%2C21649%2C21650%2C21651%2C21652%2C21653%2C21654%2C21611%2C21612%2C21613%2C21614%2C21615%2C21616%2C21617%2C21618%2C21619%2C21620%2C21623%2C21624%2C21625%2C21626%2C21627%2C21628%2C21629%2C21630%2C21631%2C21632%2C21633%2C21634%2C21635%2C21636%2C21637%2C21638%2C21639%2C21640%2C21591%2C21592%2C21593%2C21594%2C21595%2C21596%2C21597%2C21598%2C21599%2C21600%2C21601%2C21602%2C21603%2C21604%2C21605%2C21606%2C21607%2C21608%2C21609%2C21610%2C21581%2C21582%2C21583%2C21584%2C21585%2C21586%2C21587%2C21588%2C21589%2C21567%2C21568%2C21569%2C21570%2C21571%2C21572%2C21573%2C21574%2C21575%2C21576%2C21577%2C21578%2C21580%2C21555%2C21556%2C21557%2C21558%2C21559%2C21560%2C21561%2C21562%2C21563%2C21564%2C21565%2C21566%2C21550%2C21551%2C21552%2C21553%2C21554%2C21549%2C21538%2C21539%2C21540%2C21541%2C21542%2C21543%2C21544%2C21545%2C21546%2C21547%2C21548%2C21504%2C21505%2C21506%2C21507%2C21508%2C21509%2C21510%2C21511%2C21512%2C21513%2C21514%2C21515%2C21516%2C21517%2C21519%2C21520%2C21521%2C21522%2C21523%2C21525%2C21526%2C21527%2C21528%2C21529%2C21530%2C21531%2C21532%2C21533%2C21534%2C21535%2C21536%2C21537%2C21486%2C21487%2C21488%2C21489%2C21490%2C21491%2C21492%2C21493%2C21494%2C21495%2C21496%2C21497%2C21498%2C21499%2C21500%2C21501%2C21502%2C21503%2C21471%2C21472%2C21473%2C21475%2C21476%2C21477%2C21478%2C21479%2C21480%2C21481%2C21482%2C21483%2C21484%2C21485%2C21446%2C21390%2C21391%2C21392%2C21379%2C21378%2C21377%2C21376%2C21375%2C21374%2C21366%2C21350%2C21358%2C21359%2C21360%2C21361%2C21312%2C21301%2C21303%2C21275%2C21277%2C21279%2C21282%2C21283%2C21288%2C21289%2C21291%2C21292%2C21253%2C21256%2C21259%2C21261%2C21262%2C21232%2C21233%2C21240%2C21248%2C21250%2C21212%2C21218%2C21219%2C21195%2C21196%2C21197%2C21201%2C21202%2C21173%2C21178%2C21179%2C21182%2C21184%2C21186%2C21188%2C21189%2C21190%2C21191%2C21192%2C21158%2C21159%2C21160%2C21161%2C21162%2C21164%2C21165%2C21166%2C21169%2C21171%2C21172%2C21152%2C21153%2C21141%2C21147%2C21149%2C21150%2C21151%2C21136%2C21137%2C21138%2C21139%2C21134%2C21135%2C21133%2C21126%2C21127%2C21128%2C21129%2C21130%2C21131%2C21132%2C21071%2C21072%2C21073%2C21074%2C21075%2C21076%2C21077%2C21078%2C21079%2C21080%2C21081%2C21082%2C21083%2C21084%2C21085%2C21086%2C21087%2C21088%2C21089%2C21090%2C21091%2C21092%2C21093%2C21094%2C21095%2C21096%2C21097%2C21098%2C21099%2C21100%2C21101%2C21102%2C21103%2C21104%2C21105%2C21106%2C21107%2C21108%2C21109%2C21110%2C21111%2C21112%2C21113%2C21114%2C21115%2C21116%2C21117%2C21118%2C21119%2C21120%2C21121%2C21122%2C21123%2C21124%2C21125%2C21050%2C21051%2C21052%2C21053%2C21054%2C21055%2C21056%2C21057%2C21058%2C21059%2C21060%2C21061%2C21062%2C21063%2C21064%2C21065%2C21066%2C21067%2C21068%2C21069%2C21070%2C21047%2C21048%2C21049%2C21034%2C21035%2C21036%2C21037%2C21038%2C21039%2C21040%2C21041%2C21042%2C21043%2C21044%2C21045%2C21046%2C21023%2C21024%2C21025%2C21026%2C21027%2C21028%2C21029%2C21030%2C21031%2C21032%2C21033%2C21014%2C21015%2C21016%2C21017%2C21018%2C21019%2C21020%2C21021%2C21022%2C21002%2C21003%2C21004%2C21005%2C21006%2C21007%2C21008%2C21009%2C21011%2C21012%2C21013%2C20988%2C20989%2C20990%2C20991%2C20992%2C20993%2C20994%2C20995%2C20996%2C20997%2C20998%2C20999%2C21000%2C21001%2C20977%2C20978%2C20979%2C20980%2C20981%2C20982%2C20983%2C20984%2C20985%2C20986%2C20987%2C20958%2C20959%2C20960%2C20962%2C20963%2C20964%2C20965%2C20966%2C20967%2C20968%2C20969%2C20950%2C20951%2C20952%2C20953%2C20954%2C20955%2C20956%2C20957%2C20936%2C20939%2C20933%2C20934%2C20935%2C20925%2C20929%2C20906%2C20907%2C20908%2C20909%2C20910%2C20911%2C20912%2C20913%2C20915%2C20881%2C20882%2C20883%2C20884%2C20885%2C20886%2C20888%2C20889%2C20890%2C20891%2C20892%2C20893%2C20894%2C20895%2C20898%2C20901%2C20902%2C20863%2C20864%2C20866%2C20867%2C20868%2C20869%2C20870%2C20871%2C20873%2C20874%2C20875%2C20877%2C20841%2C20842%2C20843%2C20844%2C20845%2C20850%2C20853%2C20854%2C20812%2C20813%2C20814%2C20815%2C20816%2C20817%2C20818%2C20819%2C20820%2C20821%2C20822%2C20824%2C20825%2C20826%2C20829%2C20833%2C20834%2C20792%2C20795%2C20796%2C20797%2C20798%2C20801%2C20772%2C20773%2C20774%2C20775%2C20776%2C20779%2C20786%2C20790%2C20791%2C20763%2C20764%2C20766%2C20767%2C20739%2C20741%2C20742%2C20744%2C20745%2C20749%2C20750%2C20751%2C20752%2C20755%2C20722%2C20723%2C20724%2C20726%2C20727%2C20728%2C20729%2C20730%2C20731%2C20732%2C20733%2C20735%2C20736%2C20737%2C20738%2C20698%2C20699%2C20700%2C20701%2C20708%2C20679%2C20680%2C20681%2C20691%2C20657%2C20661%2C20662%2C20664%2C20665%2C20669%2C20670%2C20653%2C20654%2C20655%2C20656%2C20639%2C20640%2C20641%2C20642%2C20625%2C20626%2C20628%2C20629%2C20632%2C20633%2C20634%2C20636%2C20614%2C20615%2C20616%2C20617%2C20618%2C20619%2C20620%2C20621%2C20622%2C20623%2C20624%2C20596%2C20598%2C20599%2C20600%2C20601%2C20602%2C20603%2C20604%2C20605%2C20606%2C20607%2C20612%2C20589%2C20590%2C20592%2C20593%2C20595%2C20584%2C20572%2C20573%2C20575%2C20581%2C20565%2C20550%2C20556%2C20559%2C20560%2C20561%2C20540%2C20541%2C20548%2C20520%2C20524%2C20525%2C20527%2C20529%2C20532%2C20533%2C20536%2C20505%2C20509%2C20511%2C20514%2C20515%2C20516%2C20518%2C20503%2C20504%2C20498%2C20499%2C20500%2C20488%2C20489%2C20490%2C20482%2C20483%2C20484%2C20485%2C20486%2C20487%2C20476%2C20477%2C20478%2C20479%2C20480%2C20481%2C20471%2C20472%2C20474%2C20475%2C20466%2C20467%2C20468]

Connection to Calibre is fine as it is connecting to add new books and get new authors.

This happens on all authors.

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Click on Author
2. Click on Manual Import
3. Error appears.

**Expected behavior**
Would expect that it would see what books are available for that author in Calibre and mark Status as such and also remove the book from Wanted.

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Docker running on Ubuntu 
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET Core 5.0.3
 - Browser and Version (Only needed for UI issues): N/A
 - Readarr Version: 01.0.500
 - Readarr Branch: nightly

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[Readarr.trace.txt](https://github.com/Readarr/Readarr/files/6016471/Readarr.trace.txt)

**Comment by bakerboy448** [comment]
Can you fill out the template you butchered

And Pastebin or code block the spew

**Comment by dwilliamhouston** [comment]
Apologies.  

See above.

**To Reproduce**


1. Go to Library
2. Click on Author
3. Select Manual Import and you will receive error.
**Expected behavior**

Expect to go to Calibre and get book info to import into Readarr and mark in Readarr that the book is downloaded. 

**Screenshots**
 
N/A

**Platform Information (please complete the following information):**
 - OS: Ubuntu 
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET Core 5.0.3
 - Browser and Version (Only needed for UI issues): N/A
 - Readarr Version: 0.1.0.500
 - Readarr Branch: nightly

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/3cvqisKf

**Comment by dwilliamhouston** [comment]
Wanted to add that same error occurs when the Rescan Folders task is run.

**Comment by ta264** [comment]
I can't replicate this @dwilliamhouston @CrypticOne.  Please can you hop on the discord channel so we can try to figure it out?

**Comment by dwilliamhouston** [comment]
Go ahead and close.  I stopped using the software as it was causing me too many issues.  Will try again when things get more stable.  Thanks.
________________________________

**Comment by CrypticOne** [comment]
I think the fix is to set  private const int PAGE_SIZE = 1000; on line 38 of CalibreProxy.cs to PAGE_SIZE = 200. This should keep readarr from making URLs longer then 2048 character limit.

From my case.

Readarr needs to import the books in smaller groups to keep under URL limit of 2048 characters. URL is 8000+ characters long. Each book adds 8 characters.

Can at most safely import maybe 200 books at a time to stay under limit.

**Comment by ta264** [comment]
@CrypticOne yes that would work around it, but I can't replicate the problem with using longer URLs so I'm curious to get to the bottom of what's causing it. Please can you join the discord channel so we can investigate?

**Comment by CrypticOne** [comment]
@ta264 Does your Calibre content server require a user/pass to access?

**Comment by ta264** [comment]
> @ta264 Does your Calibre content server require a user/pass to access?

Yes it does.  If you want to debug this please can you join the discord server?  https://readarr.com/discord.

**Comment by CrypticOne** [comment]
@ta264 I ran some tests in Chrome tonight. I tried shortening the URL to about half the current length and it runs okay. Seems to run okay at about 75% as well.  I think the key is just to request the books in smaller groups as the more books a library contains the longer each ID is causing the URI to grow beyond what the Calibre server will accept.

https://github.com/kovidgoyal/calibre/blob/3dd95981398777f3c958e733209f3583e783b98c/src/calibre/srv/opts.py#L56 

Without authentication I can send a raw get command to the server and get a response but by the time all the extra header info is added it passes the threshold.

Calibre allows for 8K of header data before it throws a 413 error.  I think if you assume most people have less then 1M books, each book becomes 9 characters. You need to save enough room for authentication info and other http header info. 

Seems like a simple fix with the Page Size variable.

**Comment by ta264** [comment]
Header size isn't the same as query string length unless I am missing something. Like I said, I can't replicate locally, nor can others with big libraries.

Are you using a reverse proxy? What version of calibre?

Until I can understand the issue I don't want to make any changes to page size.

**Comment by CrypticOne** [comment]
Generally the uri is part of the header with authenticated connections. 

Calibre set to no user/password -> uri not included in header, header smaller then 8k, no 413 error
Calibre set to ask for user/pass -> uri included in header, header above 8k limit, throws 413 error if library is over approx. 11K books.

No reverse proxy. Calibre 5.16.1 running in Linuxserver.io docker container.

**Comment by subhuman-zz** [comment]
I'm having the same issue. 
Host OS: Ubuntu. 
Readarr 0.1.0.599 (hotio's Docker image). NET Core 5.0.4. 
Calibre (not running in docker), version 5.17.0.

Library size: 11687 books

How to trigger it: enable username and password on Calibre. If I do this and try and import, I see the 413 error in the initial bug post. If I disable authentication, I am able to import.

**Comment by ta264** [comment]
@CrypticOne I get it now, thank you for your patience.  I use basic auth which is why I couldn't replicate initially, and hadn't clocked that the URI was part of the `Authorization` header for digest.

Running through the calculation you suggest, I think 865 books ought to work given a reasonable allowance for length of the other components of the header.  I'll set it to 750 to be safe.
