### ISSUE TITLE
Synology DownloadStation API Breaking Change | Downloads cannot be added to Download Station

### ISSUE THREAD

**Issue by bakerboy448** [Readarr/Readarr#899]
### It is advised users use a different download client at this time or if possible downgrade DownloadStation.  It is not known when or even if this can be fixed.  Please do not comment on this GHI asking for updates or when this will be fixed.

Xref
https://github.com/Sonarr/Sonarr/issues/4388

[AB#758](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/758)

**Comment by bakerboy448** [comment]
Can be fixed by
- https://github.com/Radarr/Radarr/commit/143067621c4a0065365c2446a1cdda19dcd1a378
- https://github.com/Radarr/Radarr/commit/94c685a5caf30dbef5708dca0018ba8df436b6d2

**Comment by ta264** [comment]
Already done
