### ISSUE TITLE
Sorting books by there title/cover

### ISSUE THREAD

**Issue by jarnohissink** [Readarr/Readarr#964]
**Is your feature request related to a problem? Please describe.**
Its not really a problem, just a surgestion for people who are to look at a books cover and think i will read that 

**Describe the solution you'd like**
I would like to sort books by there title like sonarr or radarr with the books cover as a poster 

**Describe alternatives you've considered**
The sorting systems i have considered are really old or are websites where you see the cover of a book and then click further for the rest of the information 

**Additional context**
![books1 (1)](https://user-images.githubusercontent.com/5670564/114593461-6cd22d00-9c8c-11eb-8700-d60755a0b20a.jpg)

**Comment by ta264** [comment]
Are you saying you want readarr to show books on the main page and not authors?

**Comment by jarnohissink** [comment]
Yes, if this is possible that would be great.
